function initialize_cf(parentResource) {
	parentResource.setMessage("cf.info.confirm.usernick.0", "It\'\'s an available nickname.");
	parentResource.setMessage("cf.error.not.exist.menuId.0", "The menu ID does not exist.");
	parentResource.setMessage("cf.error.cant.change.same.state.0", "it includes the users who have the state which will be changed.");
	parentResource.setMessage("cf.error.cant.change.sysop.grade.0", "The grade of café manager is an irrevocable grade.");
	parentResource.setMessage("cf.error.cnat.change.wx2bjigi.0", "Operator  and café\'\'s manager can\'\'t be a board\'\'s manager.");
	parentResource.setMessage("cf.error.open.denied.0", "It\'\'s a cafe which open is denied.");
	parentResource.setMessage("cf.info.myPeople.0", "We cafe in a note or useful information, you can receive Daum Cafe easier to My People.");
	parentResource.setMessage("cf.info.completeRegistration.modifiabl.0", "Application has been completed. Representatives approved before it can be modified.");
	parentResource.setMessage("cf.info.ggum.gate.apply.0", "Would you like to apply the edit details of the present gate ?");
	parentResource.setMessage("cf.error.not.exist.rcmd.cafe.0", "The cafe which recommend is nonexistent.");
	parentResource.setMessage("cf.error.cafejigi.cant.resign.0", "Caf? manager can not withdraw.");
	parentResource.setMessage("cf.info.not.existImg.0", "No properties of the original.");
	parentResource.setMessage("cf.info.confirm.closeCafe.0", "Do you want to close the cafe?");
	parentResource.setMessage("cf.prop.info.area.0", "Information Area");
	parentResource.setMessage("cf.error.cant.move2qna.0", "The post of the Q \/ A type board can\'t be moved to a different type board.");
	parentResource.setMessage("cf.info.recognize.requestEstablishment .0", "Are you sure you want to approve the establishment request for the selected group?");
	parentResource.setMessage("cf.error.improper.stateFlag.0", "It isn\'\'t a normal state of member.");
	parentResource.setMessage("cf.error.not.exist.cmnt.0", "It\'\'s a non-existent community.");
	parentResource.setMessage("cf.error.not.exist.rcnt.cafe.0", "Recently visited cafe not exists");
	parentResource.setMessage("cf.prop.cafe.basic.info.0", "Cafe Basic information");
	parentResource.setMessage("cf.prop.my.info.update.0", "Edit my info");
	parentResource.setMessage("cf.info.input.TimesLimit.0", "To use policies Enter one or more limited number of");
	parentResource.setMessage("cf.error.not.correspondUser.0", "Does not correspond to the state to release now includes the user.");
	parentResource.setMessage("cf.info.not.use.cafeDeco.0", "Is a version of a browser, you can not use the cafe decorating.");
	parentResource.setMessage("cf.info.reallyLeave.0", "Are you sure you want to leave?");
	parentResource.setMessage("cf.error.not.set.zeroBoard.0", "You can\'\'t set count of board to 0. Instead of empty bulletin board can be selected.");
	parentResource.setMessage("cf.info.reenter.cafeURL.0", "Please enter the cafe address.");
	parentResource.setMessage("cf.info.recognize.requestEstablishment.0", "Are you sure you want to approve the establishment request for the selected group?");
	parentResource.setMessage("cf.info.cancelProcessing.0", "Application for admission has been processed successfully canceled.");
	parentResource.setMessage("cf.info.already.requestInvitation.cancel.0", "It has already canceled the invitation.");
	parentResource.setMessage("cf.info.input.searchWord.0", "Enter your search terms");
	parentResource.setMessage("cf.info.confirm.url.0", "It\'\'s the available cafés address.");
	parentResource.setMessage("cf.info.input.onlyNumber.0", "You can enter only numbers.");
	parentResource.setMessage("cf.error.not.exist.my.cafe.0", "The café which you join isn\'\'t exisit.");
	parentResource.setMessage("cf.info.irreparable.closeCafe.0", "When the café closed, you can not recover any data, including the posts!");
	parentResource.setMessage("cf.info.choose.boardManager.0", "Please select the bulletin being released to parties.");
	parentResource.setMessage("cf.info.sameBoard.0", "It\'\'s the same board.");
	parentResource.setMessage("cf.error.incorrect.dateType.0", "This is not a valid date format.");
	parentResource.setMessage("cf.info.complete.cafeCreation.0", "Cafe generation has been completed.");
	parentResource.setMessage("cf.error.not.exist.favor.cafe.0", "The registered café which you often visit is nonexistent.");
	parentResource.setMessage("cf.info.choose.upperMenu.0", "Select the top menu of the menu you want to add.");
	parentResource.setMessage("cf.info.continueModify.0", "Do you want to fix it?");
	parentResource.setMessage("cf.error.not.set.Board.0", "The Board can not be set to exceed 7.");
	parentResource.setMessage("cf.error.not.exist.colorSet.0", "The three colors that does not exist.");
	parentResource.setMessage("cf.info.processed.deleteNotice.0", "Delete posts that have been properly processed.");
	parentResource.setMessage("cf.info.closeCafe.0", "Do you want to force the closure of the selected group?");
	parentResource.setMessage("cf.info.processed.recommendCafe.0", "Café recommendation has been successfully processed.");
	parentResource.setMessage("cf.info.board.prop2.0", "Even with the same type of board that has already been opened cafe affects.");
	parentResource.setMessage("cf.prop.join.info.0", "Subscription Information");
	parentResource.setMessage("cf.info.already.request.closeCafe.0", "You have already applied for cafes closed.");
	parentResource.setMessage("cf.info.already.cancel.closeCafe.0", "It has already canceled the cafe closed.");
	parentResource.setMessage("cf.error.not.exist.cafe.skin.0", "Café skin is nonexistent.");
	parentResource.setMessage("cf.error.closed.cafe.0", "It\'\'s the closed café.");
	parentResource.setMessage("cf.error.already.used.usernick.0", "It\'\'s the nickname which already use.");
	parentResource.setMessage("cf.error.open.request.0", "It\'\'s a cafe which applied for open.");
	parentResource.setMessage("cf.info.already.rejoin.0", "You have already reactivation.");
	parentResource.setMessage("cf.info.cancel.invitationRequest.0", "The invitation has been processed successfully canceled.");
	parentResource.setMessage("cf.info.complete.joinCafe.0", "Sign Up Café is complete.");
	parentResource.setMessage("cf.info.choose.addCafe.0", "Please select the cafe can add");
	parentResource.setMessage("cf.info.change.recommendList.order.0", "Do you want to change the order of the list of selected recommended Cafe?");
	parentResource.setMessage("cf.info.warning.deleteAll.0", "WARNING!. All data is deleted. Do you want to delete?");
	parentResource.setMessage("cf.prop.basic.info.0", "Basic Information");
	parentResource.setMessage("cf.prop.cafe.rank.info.0", "Cafe ranking information");
	parentResource.setMessage("cf.info.confirm.closeCafe.cancel.0", "Do you want to close the cafe?");
	parentResource.setMessage("cf.info.delete.noticeList.0", "Do you want to delete notice history?");
	parentResource.setMessage("cf.error.select.wrongPeriod.0", "The selected period is invalid.");
	parentResource.setMessage("cf.error.favorMng.request.fail.0", "It\'\'s the change request of wrong café list which often go.");
	parentResource.setMessage("cf.prop.member.info.admin.0", "Account Management");
	parentResource.setMessage("cf.prop.employee.info.0", "Employee information");
	parentResource.setMessage("cf.info.cancel.closeCafe.0", "Are you sure you want to disable the closing of the selected group?");
	parentResource.setMessage("cf.info.really.delete.0", "Do you really want to delete?");
	parentResource.setMessage("cf.info.processed.closing.0", "Forced closure has been processed normally.");
	parentResource.setMessage("cf.info.processed.cancelClosing.0", "Closed-off has been processed successfully.");
	parentResource.setMessage("cf.info.processed.deleteComment.0", "Comments (notes) has been deleted successfully processed.");
	parentResource.setMessage("cf.info.board.prop1.0", "You can set the type of board selected property.");
	parentResource.setMessage("cf.info.againTryout.0", "Please try again in a few minutes.");
	parentResource.setMessage("cf.info.already.permit.0", "It is already approved");
	parentResource.setMessage("cf.info.o.chooseMember.0", "Selected members");
	parentResource.setMessage("cf.error.different.dateType.0", "It does not conform to the date format.");
	parentResource.setMessage("cf.prop.my.info.0", "My Info");
	parentResource.setMessage("cf.info.input.replyList.0", "Enter the answer surveys more than two entries in the Register");
	parentResource.setMessage("cf.error.cannot.delete.0", "These boards can not be deleted.");
	parentResource.setMessage("cf.info.preparing.0", "It is coming soon.");
	parentResource.setMessage("cf.error.cant.change.self.grade.0", "You can\'\'t change your grade.");
	parentResource.setMessage("cf.info.ttl.none.board.0", "No Board");
	parentResource.setMessage("cf.error.not.exist.mmbr.cmntVO.cafe.0", "Favorite cafe not exists");
	parentResource.setMessage("cf.prop.operator.info.0", "Company Information");
	parentResource.setMessage("cf.info.choose.deleteCafe.0", "Please select the cafe to be removed");
	parentResource.setMessage("cf.info.delete.recommendCafe.0", "Are you sure you want to remove the selected cafe in the cafe recommended list?");
	parentResource.setMessage("cf.error.cant.move2one.0", "The post of the selected type board can\'\'t move to the one-line memo type board.");
	parentResource.setMessage("cf.error.already.used.url.0", "It already being used the address of the cafe. Please input the different address.");
	parentResource.setMessage("cf.error.grdup.request.fail.0", "It\'\'s the change request of incorrect terms of grade .");
	parentResource.setMessage("cf.error.menuMng.request.fail.0", "It\'\'s the wrong request which change menu.");
	parentResource.setMessage("cf.error.not.exist.cafe.0", "It\'\'s a non-existent cafe.");
	parentResource.setMessage("cf.info.already.rcmd.cafe.0", "It\'\'s the café which is already recommended and registered café.");
	parentResource.setMessage("cf.prop.my.info.view.button.0", "My Info View button");
	parentResource.setMessage("cf.info.o.joinQuiz.answer.0", "Join the quiz answers");
	parentResource.setMessage("cf.info.leaveProcessing.0", "Withdrawal was properly handled.");
	parentResource.setMessage("cf.error.not.decorate.0", "You can not proceed any more decorating. Shut down and restart your decorating");
	parentResource.setMessage("cf.prop.cafe.info.0", "Cafe Information");
	parentResource.setMessage("cf.info.goOut.invitationRequest.mail.0", "Mail invitation has been sent successfully.");
	parentResource.setMessage("cf.info.mustLogin.0", "You need to login.");
	parentResource.setMessage("cf.error.not.allow.read.0", "The author did not allow read articles.");
	parentResource.setMessage("cf.info.by.0", "With");
	parentResource.setMessage("cf.info.already.requestInvitation.0", "I have already requested an invitation.");
	parentResource.setMessage("cf.info.add.recommendCafe.0", "Do you want to add the selected cafe cafe on the recommendation list?");
	parentResource.setMessage("cf.info.create.department.0", "Are you sure you want to create a department yard?");
	parentResource.setMessage("cf.info.o.joinQuiz.question.0", "Join the quiz questions");
	parentResource.setMessage("cf.error.already.existMenu.0", "Already there is a set menu as cafe home board.");
	parentResource.setMessage("cf.info.save.noticeList.0", "Do you want to save a notice history?");
	parentResource.setMessage("cf.info.inputEmail.0", "Please enter your e-mail.");
	parentResource.setMessage("cf.error.layout.corrupt.0", "Layout can\'\'t be changed because ");
	parentResource.setMessage("cf.info.reallyCancel.0", "Are you sure you want to cancel?");
	parentResource.setMessage("cf.info.really.cancel.RequestIbvitation.0", "Are you sure you want to cancel the invitation?");
	parentResource.setMessage("cf.info.really.rejoin.0", "Are you sure you want to rejoin?");
	parentResource.setMessage("cf.info.already.join.0", "I have already signed up.");
	parentResource.setMessage("cf.info.processed.acceptOpen.0", "Opened approval has been processed successfully.");
	parentResource.setMessage("cf.info.processed.deleteCafe.0", "Delete cafe has been processed normally.");
	parentResource.setMessage("cf.info.processed.recommendCafe.cancel.0", "Cafe clear recommendation has been successfully processed.");
	parentResource.setMessage("cf.error.email.not.exist.0", "The e-mail address does not exist.");
	parentResource.setMessage("cf.prop.cafe.info.admin.0", "Cafe Information Management");
	parentResource.setMessage("cf.prop.etc.info.0", "More info");
	parentResource.setMessage("cf.error.cant.change.staff.grade.0", "Operator can\'\'t change the grade of operator.");
	parentResource.setMessage("cf.info.ggum.apply.0", "Would you like to apply the decoration of the present board ?");
	parentResource.setMessage("cf.error.not.exist.cmnt.img.0", "A representation image of café is nonexistent.");
	parentResource.setMessage("cf.error.not.exist.cafe.theme.0", "Café theme is nonexistent.");
	parentResource.setMessage("cf.error.gradeNm.fail.0", "It\'\'s an incorrect name of grade.");
	parentResource.setMessage("cf.info.define.iconName.0", "Please forward the Menu icon name");
	parentResource.setMessage("cf.error.not.exist.cafe2.1", "Cafe does not exist.");
	parentResource.setMessage("cf.error.not.exist.member.0", "Do not exist the members.");
	parentResource.setMessage("cf.error.not.exist.leaveMember.0", "There are no members to leave.");
	parentResource.setMessage("cf.info.todayActivities.0", "Today\'s activities");
	parentResource.setMessage("cf.info.selectBoard.0", "Please select a board.");
	parentResource.setMessage("cf.info.keep.board.0", " Archived bulletin boards are automatically deleted after {0} days");
	parentResource.setMessage("cf.info.appoint.sysop.0", "Appoint to Sysop");
	parentResource.setMessage("cf.error.noPermissions.write.0", "You have no write permissions");
	parentResource.setMessage("cf.info.selectLayout.0", "Please select the layout of the bulletin board to be added to the cafe home.");
	parentResource.setMessage("cf.error.not.exist.data.0", "Do not exist the data.");
	parentResource.setMessage("cf.info.setting.cafeHome.0", "The current setting applies only to Cafe Home.");
	parentResource.setMessage("cf.info.deco.useColor.0", "It is a method to decorate by using color.");
	parentResource.setMessage("cf.info.remoteControl.0", "It is convenient to use while checking the preview of the bottom of the remote control.");
	parentResource.setMessage("cf.info.closing.Info.0", "You can close the cafe because there are no members.");
	parentResource.setMessage("cf.info.closing.Info2.0", "After the closure, cafe data can not be recovered.");
	parentResource.setMessage("cf.info.not.exist.notice.0", "Do not exist the notice.");
	parentResource.setMessage("cf.error.not.exist.department.0", "Do not exist the department by searching");
	parentResource.setMessage("cf.info.margin.0", "The margin is set.");
	parentResource.setMessage("cf.info.cafeHome.main.0", "Set cafe home as main");
	parentResource.setMessage("cf.info.makeTitle.0", "Create great titles quickly and easily");
	parentResource.setMessage("cf.info.please.selectBoard.1", "Please select a board.");
	parentResource.setMessage("cf.info.shutDown.font.0", " The font you are using has been shut down. Please choose a different font.");
	parentResource.setMessage("cf.info.chooseDesign.0", "Please choose your favorite design.");
	parentResource.setMessage("cf.info.makeTitle.easy.0", "Create a great title quickly and easily");
	parentResource.setMessage("cf.info.employee.notSeen.0", "The employee was not seen.");
	parentResource.setMessage("cf.error.not.exist.approval.member.0", "There are no members waiting for approval.");
	parentResource.setMessage("cf.error.not.exist.wait.levelUp.0", "There are no members to waiting for level up.");
	parentResource.setMessage("cf.info.advertise.0", "Advertise!");
	parentResource.setMessage("cf.info.htmlEdit.0", "After editing the HTML, Save it and it will appear in the main area.");
	parentResource.setMessage("cf.error.not.exist.content.0", "Do not exist the content.");
	parentResource.setMessage("cf.error.not.exist.post.0", "Do not exsit the post.");
	parentResource.setMessage("cf.info.separator.0", "The separator is set.");
	parentResource.setMessage("cf.info.privateCafe.0", "This is a private cafe.");
	parentResource.setMessage("cf.info.wantJoin.0", "If you want to join, please send an invitation to sysop.");
	parentResource.setMessage("cf.info.inviteMail.0", "The invitation e-mail will be sent to the e-mail address registered in the member information.");
	parentResource.setMessage("cf.info.send.requestEmail.0", "You have sent an invitation request email to sign up.");
	parentResource.setMessage("cf.info.canJoin.0", "You can join the cafe after you receive the invitation e-mail from the cafe.");
	parentResource.setMessage("cf.info.joinLink.0", "You can join this cafe through the link.");
	parentResource.setMessage("cf.info.rejectReason.0", "The cafe invitation has been rejected for the following reasons.");
	parentResource.setMessage("cf.info.needApprove.0", "To become a member, you need to approve the cafe.");
	parentResource.setMessage("cf.info.accessCafe.0", "Please access the cafe after receiving the registration approval e-mail from the sysop.");
	parentResource.setMessage("cf.info.needLogin.0", "You need to login.");
	parentResource.setMessage("cf.info.selectFile.0", "Please select a file.");
	parentResource.setMessage("cf.error.not.exist.my.cafe2.0", "Open a new cafe or find a variety of cafes and sign up.");

}
