---------------------------------------------------------------------------------------------------
-- 이 파일은 enBoard 시스템 내에서 독립형테이블 생성 시 사용되므로 제거하지 말것.
-- 이 파일의 형식을 'ANSI 인코딩'에서 다른 것으로 바꾸지 말것.
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
-- BULLETIN::게시물
---------------------------------------------------------------------------------------------------
CREATE TABLE BULLETIN (
	BOARD_ID		VARCHAR2(30),
	BLTN_NO			VARCHAR2(17),
	BLTN_GID		VARCHAR2(100),
	BLTN_GN			NUMBER(10),
	BLTN_GQ			NUMBER(5),
	BLTN_LEV		NUMBER(3),
	DEL_FLAG		CHAR(1),
	CATE_ID			VARCHAR2(10),
	USER_ID			VARCHAR2(30),
	USER_PASS		VARCHAR2(512),
	USER_NICK		VARCHAR2(30),
	USER_IP			VARCHAR2(39),
	BLTN_READ_CNT	NUMBER(9),
	BLTN_REPLY_CNT	NUMBER(9),
	BLTN_MEMO_CNT	NUMBER(9),
	BLTN_FILE_CNT	NUMBER(9),
	BLTN_TOP_TAG	CHAR(1),
	BLTN_BEST_LEVEL	CHAR(1),
	BLTN_SECRET_YN	CHAR(1),
	BLTN_PERMIT_YN	CHAR(1),
	BET_PNT			NUMBER(6),
	BLTN_ICON		CHAR(1),
	BLTN_BGN_YMD	DATE,
	BLTN_END_YMD	DATE,
	SUB_BOARD_ID	VARCHAR2(30),
	BLTN_SUBJ		VARCHAR2(120),
	REG_DATIM		TIMESTAMP,
	UPD_DATIM		TIMESTAMP,
  CONSTRAINT BULLETINP1 PRIMARY KEY (
	BOARD_ID,
	BLTN_NO ));

-- 기본 정렬
CREATE INDEX BULLETINIDEF ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	BLTN_PERMIT_YN,
	BLTN_GN DESC,
	BLTN_GQ DESC );

-- 제목 검색
CREATE INDEX BULLETINISUBJ ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	BLTN_GN DESC,
	BLTN_GQ DESC,
	BLTN_SUBJ );

-- 최신글, 작성일 검색
CREATE INDEX BULLETINIREG ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	BLTN_GN DESC,
	BLTN_GQ DESC,
	REG_DATIM );

-- 작성자 검색
CREATE INDEX BULLETINIUSER ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	BLTN_GN DESC,
	BLTN_GQ DESC,
	USER_NICK );

-- 게시기간 검색
CREATE INDEX BULLETINIYMD ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	BLTN_GN DESC,
	BLTN_GQ DESC,
	BLTN_BGN_YMD,
	BLTN_END_YMD );
	
-- 실삭제기능을 사용하지 않는 게시판의 경우에 필요한 인덱스.
CREATE INDEX BULLETINIDEL ON BULLETIN (
	BOARD_ID,
	BLTN_GID,
	DEL_FLAG,
	BLTN_PERMIT_YN,
	BLTN_GN DESC,
	BLTN_GQ DESC );

-- 통합 최신글
CREATE INDEX BULLETININEW ON BULLETIN (
	REG_DATIM DESC,
	BOARD_ID,
	BLTN_GID );

-- 인기글
CREATE INDEX BULLETINIREAD ON BULLETIN (
	BLTN_READ_CNT DESC,
	BOARD_ID,
	BLTN_GID );

-- 나만의자료실
CREATE INDEX BULLETINIMINE ON BULLETIN (
	USER_ID,
	BOARD_ID,
	BLTN_GID,
	BLTN_GN DESC,
	BLTN_GQ DESC );	

COMMENT ON TABLE BULLETIN IS '게시물';
COMMENT ON COLUMN BULLETIN.BOARD_ID			IS '게시판 아이디';
COMMENT ON COLUMN BULLETIN.BLTN_NO			IS '게시물 번호';
COMMENT ON COLUMN BULLETIN.BLTN_GID			IS '게시물 그룹아이디';
COMMENT ON COLUMN BULLETIN.BLTN_GN			IS '게시물 그룹번호';
COMMENT ON COLUMN BULLETIN.BLTN_GQ			IS '게시물 그룹내순서';
COMMENT ON COLUMN BULLETIN.BLTN_LEV			IS '게시물 깊이';
COMMENT ON COLUMN BULLETIN.DEL_FLAG			IS '삭제 여부';
COMMENT ON COLUMN BULLETIN.CATE_ID			IS '카테고리 아이디';
COMMENT ON COLUMN BULLETIN.USER_ID			IS '작성자 아이디';
COMMENT ON COLUMN BULLETIN.USER_PASS		IS '작성자 암호';
COMMENT ON COLUMN BULLETIN.USER_NICK		IS '작성자 닉네임';
COMMENT ON COLUMN BULLETIN.USER_IP			IS '작성자 아이피';
COMMENT ON COLUMN BULLETIN.BLTN_READ_CNT	IS '게시물 조회수';
COMMENT ON COLUMN BULLETIN.BLTN_REPLY_CNT	IS '게시물 답글수';
COMMENT ON COLUMN BULLETIN.BLTN_MEMO_CNT	IS '게시물 댓글수';
COMMENT ON COLUMN BULLETIN.BLTN_FILE_CNT	IS '게시물 첨부파일수';
COMMENT ON COLUMN BULLETIN.BLTN_TOP_TAG		IS '공지글 구분';
COMMENT ON COLUMN BULLETIN.BLTN_BEST_LEVEL	IS '최고 답변 레벨';
COMMENT ON COLUMN BULLETIN.BLTN_SECRET_YN	IS '비밀글 여부';
COMMENT ON COLUMN BULLETIN.BLTN_PERMIT_YN	IS '승인 여부';
COMMENT ON COLUMN BULLETIN.BET_PNT			IS '공모 점수';
COMMENT ON COLUMN BULLETIN.BLTN_ICON		IS '게시물 아이콘';
COMMENT ON COLUMN BULLETIN.BLTN_BGN_YMD		IS '게시 시작 일자';
COMMENT ON COLUMN BULLETIN.BLTN_END_YMD		IS '게시 종료 일자';
COMMENT ON COLUMN BULLETIN.SUB_BOARD_ID		IS '연결 게시판 아이디';
COMMENT ON COLUMN BULLETIN.BLTN_SUBJ		IS '게시물 제목';
COMMENT ON COLUMN BULLETIN.REG_DATIM		IS '작성일시';
COMMENT ON COLUMN BULLETIN.UPD_DATIM		IS '수정일시';

---------------------------------------------------------------------------------------------------
-- BLTN_MEMO::댓글
---------------------------------------------------------------------------------------------------
CREATE TABLE BLTN_MEMO (
	BOARD_ID	VARCHAR2(30),
	BLTN_NO		VARCHAR2(17),
	MEMO_SEQ	NUMBER(6),
	MEMO_GN		NUMBER(10),
	MEMO_GQ		NUMBER(5),
	MEMO_LEV	NUMBER(3),
	USER_ID		VARCHAR2(30),
	USER_PASS	VARCHAR2(512),
	USER_NICK	VARCHAR2(30),
	USER_IP		VARCHAR2(30),
	MEMO_CNTT	VARCHAR2(3000),
	BAD_CNT		NUMBER(4),
	REG_DATIM	TIMESTAMP,
	UPD_DATIM	TIMESTAMP,
  CONSTRAINT BLTN_MEMOP1 PRIMARY KEY (
	BOARD_ID,
	BLTN_NO,
	MEMO_SEQ ));

CREATE INDEX BLTN_MEMOI1 ON BLTN_MEMO (
	BOARD_ID,
	BLTN_NO,
	MEMO_GN DESC,
	MEMO_GQ DESC );	

COMMENT ON TABLE BLTN_MEMO IS '댓글';
COMMENT ON COLUMN BLTN_MEMO.BOARD_ID	IS '게시판 아이디';
COMMENT ON COLUMN BLTN_MEMO.BLTN_NO		IS '게시물 번호';
COMMENT ON COLUMN BLTN_MEMO.MEMO_SEQ	IS '댓글 일련번호';
COMMENT ON COLUMN BLTN_MEMO.MEMO_GN		IS '댓글 그룹번호';
COMMENT ON COLUMN BLTN_MEMO.MEMO_GQ		IS '댓글 그룹내순서';
COMMENT ON COLUMN BLTN_MEMO.MEMO_LEV	IS '댓글 깊이';
COMMENT ON COLUMN BLTN_MEMO.USER_ID		IS '사용자 아이디';
COMMENT ON COLUMN BLTN_MEMO.USER_PASS	IS '작성자 암호';
COMMENT ON COLUMN BLTN_MEMO.USER_NICK	IS '사용자 닉네임';
COMMENT ON COLUMN BLTN_MEMO.USER_IP		IS '사용자 아이피';
COMMENT ON COLUMN BLTN_MEMO.MEMO_CNTT	IS '메모내용';
COMMENT ON COLUMN BLTN_MEMO.BAD_CNT		IS '악플 피신고 건수';
COMMENT ON COLUMN BLTN_MEMO.REG_DATIM	IS '작성일시';
COMMENT ON COLUMN BLTN_MEMO.UPD_DATIM	IS '최종수정일시';

---------------------------------------------------------------------------------------------------
-- BLTN_CNTT::게시물 본문
---------------------------------------------------------------------------------------------------
CREATE TABLE BLTN_CNTT (
	BOARD_ID		VARCHAR2(30),
	BLTN_NO			VARCHAR2(17),
	BLTN_CNTT		CLOB,
  CONSTRAINT BLTN_CNTTP1 PRIMARY KEY (
	BOARD_ID,
	BLTN_NO ));

COMMENT ON TABLE BLTN_CNTT IS '게시물 본문';
COMMENT ON COLUMN BLTN_CNTT.BOARD_ID		IS '게시판 아이디';
COMMENT ON COLUMN BLTN_CNTT.BLTN_NO			IS '게시물 번호';
COMMENT ON COLUMN BLTN_CNTT.BLTN_CNTT		IS '게시물 내용';

---------------------------------------------------------------------------------------------------
-- BLTN_FILE::첨부파일
---------------------------------------------------------------------------------------------------
CREATE TABLE BLTN_FILE (
	BOARD_ID	VARCHAR2(30),
	BLTN_NO		VARCHAR2(17),
	FILE_SEQ	NUMBER(2),
	ATCH_TYPE	CHAR(1),
	FILE_NM		VARCHAR2(120),
	FILE_MASK	VARCHAR2(32),
	FILE_SIZE	NUMBER(12),
	DOWN_CNT	NUMBER(12),
	ATCH_DATIM	TIMESTAMP,
  CONSTRAINT BLTN_FILEP1 PRIMARY KEY (
	BOARD_ID,
	BLTN_NO,
	FILE_SEQ ));

COMMENT ON TABLE BLTN_FILE IS '첨부파일';
COMMENT ON COLUMN BLTN_FILE.BOARD_ID	IS '게시판 아이디';
COMMENT ON COLUMN BLTN_FILE.BLTN_NO		IS '게시물 번호';
COMMENT ON COLUMN BLTN_FILE.FILE_SEQ	IS '첨부파일 일련번호';
COMMENT ON COLUMN BLTN_FILE.ATCH_TYPE	IS '첨부 유형';
COMMENT ON COLUMN BLTN_FILE.FILE_NM		IS '첨부파일 명';
COMMENT ON COLUMN BLTN_FILE.FILE_MASK	IS '첨부파일 MASK';
COMMENT ON COLUMN BLTN_FILE.FILE_SIZE	IS '첨부파일 크기';
COMMENT ON COLUMN BLTN_FILE.DOWN_CNT	IS '다운로드 횟수';
COMMENT ON COLUMN BLTN_FILE.ATCH_DATIM	IS '첨부 일시';

---------------------------------------------------------------------------------------------------
-- BLTN_EVAL::추천/평가내역
---------------------------------------------------------------------------------------------------
CREATE TABLE BLTN_EVAL (
	BOARD_ID		VARCHAR2(30),
	BLTN_NO			VARCHAR2(17),
	EVAL_DATIM		TIMESTAMP,
	EVAL_TYPE		CHAR(1),
	EVAL_USER_ID	VARCHAR2(30),
	EVAL_USER_IP	VARCHAR2(39),
	EVAL_PNT		NUMBER(6),
  CONSTRAINT BLTN_EVALP1 PRIMARY KEY (
	BOARD_ID,
	BLTN_NO,
	EVAL_DATIM ));

COMMENT ON TABLE BLTN_EVAL IS '추천내역';
COMMENT ON COLUMN BLTN_EVAL.BOARD_ID		IS '게시판 아이디';
COMMENT ON COLUMN BLTN_EVAL.BLTN_NO			IS '게시물 번호';
COMMENT ON COLUMN BLTN_EVAL.EVAL_DATIM		IS '평가/선정 일시';
COMMENT ON COLUMN BLTN_EVAL.EVAL_TYPE		IS '평가/선정 유형';
COMMENT ON COLUMN BLTN_EVAL.EVAL_USER_ID	IS '평가/선정인 아이디';
COMMENT ON COLUMN BLTN_EVAL.EVAL_USER_IP	IS '평가/선정인 아이피';
COMMENT ON COLUMN BLTN_EVAL.EVAL_PNT		IS '평가/선정 점수';
---------------------------------------------------------------------------------------------------
-- 이 파일은 enBoard 시스템 내에서 독립형테이블 생성 시 사용되므로 제거하지 말것.
---------------------------------------------------------------------------------------------------
