function initialize_eb(parentResource) {
	parentResource.setMessage("eb.error.invalid.term.0", "한번에 저장 가능한 시간이 지나지 않았습니다 잠시후 다시 시도하세요 ");
	parentResource.setMessage("eb.error.last.boardCateBoard.0", "현재 게시판의 유일한 카테고리 배속 정보이므로 삭제할 수 없습니다. ");
	parentResource.setMessage("eb.error.make.atch.dir.0", "첨부파일 디렉터리 생성에 실패했습니다. ");
	parentResource.setMessage("eb.error.memoCntt.required.0", "메모 내용이 필요합니다 ");
	parentResource.setMessage("eb.error.mmb.over.0", "신고건수 초과로 자동 삭제 되었습니다.");
	parentResource.setMessage("eb.error.moveBltn.extn.not.match.0", "확장필드 테이블이 일치하지 않습니다.");
	parentResource.setMessage("eb.error.must.auth.realMan.0", "실명인증을 하셔야 합니다.");
	parentResource.setMessage("eb.error.need.login.0", "로그인하셔야 합니다.");
	parentResource.setMessage("eb.error.no.attachedBoard.0", "배속된 게시판이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.allow.replyComment.0", "작성자가 댓답글쓰기를 허용하지 않았습니다.");
	parentResource.setMessage("eb.error.not.allowComment.0", "작성자가 댓글쓰기를 허용하지 않았습니다.");
	parentResource.setMessage("eb.error.not.allowReply.0", "작성자가 답글쓰기를 허용하지 않았습니다.");
	parentResource.setMessage("eb.error.not.exist.0", "Records of {0} are not exist.");
	parentResource.setMessage("eb.error.not.exist.board.0", "가상게시판이나 통합게시판에는 실 게시물이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.boardId.0", "게시판 아이디가 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.file.0", "파일이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.id.0", "존재하지 않은 아이디입니다.");
	parentResource.setMessage("eb.error.not.exist.registeredContent.0", "등록된 컨텐츠가 없습니다.");
	parentResource.setMessage("eb.error.not.exist.registeredNotice.0", "등록된 게시물이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.registeredReply.0", "등록된 답변이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.replyList.0", "해당 답변항목의 답변 내역이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.surveyGrademark.0", "배속된 설문평점이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.surveyQuestion.0", "등록된 설문문항이 존재하지 않습니다.");
	parentResource.setMessage("eb.error.not.exist.text.0", "작성된 글이 없습니다");
	parentResource.setMessage("eb.error.not.existMethod.0", "호출에러 : 메소드가 없음");
	parentResource.setMessage("eb.error.notType.0", "대상자 부여 유형이 사용자\/그룹\/역할 별이 아닙니다.");
	parentResource.setMessage("eb.error.notice.limit.0", "?????？??？ ????({0}??)?? ？??？?????？？");
	parentResource.setMessage("eb.error.orgDelYn.change.fromM.0", "답글있는 글의 삭제 정책을 현재의   삭제 표시만  에서 다른 정책으로 바꾸셨습니다.");
	parentResource.setMessage("eb.error.orgDelYn.real.delete.0", "기존의 삭제 표시된 게시글들을 실제로 삭제합니다. 정말 변경하시겠습니까?");
	parentResource.setMessage("eb.error.owntbl.conflict.0", "동일 카테고리에 속한 게시판들의 독립테이블 일치 여부를 확인하십시오 ");
	parentResource.setMessage("eb.error.parameter.invalid.0", "부적절한 파라미터 값입니다 ");
	parentResource.setMessage("eb.error.poll.inactive.0", "활성화되지 않은 설문입니다.");
	parentResource.setMessage("eb.error.pollId.already.deleted.0", "존재하지 않는 설문 아이디입니다");
	parentResource.setMessage("eb.error.pollSeq.required.0", "투표 시퀀스가 필요합니다 ");
	parentResource.setMessage("eb.error.secret.0", "비밀글 입니다 권한이 없습니다 ");
	parentResource.setMessage("eb.error.upload.atch.file.0", "파일 업로드에 실패하였습니다.");
	parentResource.setMessage("eb.error.userPass.required.0", "사용자 비밀번호가 필요합니다 ");
	parentResource.setMessage("eb.info.Class.ExtendedField.0", "확장필드 테이블 클래스");
	parentResource.setMessage("eb.info.NoLimit.0", "제한없음");
	parentResource.setMessage("eb.info.add.recommendCafe.0", "선택된 카페를 추천카페 목록에 추가하시겠습니까?");
	parentResource.setMessage("eb.info.after.0", "후");
	parentResource.setMessage("eb.info.all.numberOfvotes.0", "전체투표수");
	parentResource.setMessage("eb.info.alreadyJoin.0", "이미 참여하셨습니다.");
	parentResource.setMessage("eb.info.anon.notUse.0", "선택된 게시판은   익명\/실명인증 게시판기능  이   미사용  으로 설정되어 있습니다.");
	parentResource.setMessage("eb.info.anyone.0", "누구나");
	parentResource.setMessage("eb.info.anyone.login.0", "누구나 (로그인후)");
	parentResource.setMessage("eb.info.anyone.notlogin.0", "누구나 (로그인전)");
	parentResource.setMessage("eb.info.assert.del.0", "정말정말 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.assignGroup.curGrade.0", "현재 등급에 배속된 그룹");
	parentResource.setMessage("eb.info.assignGroup.curUser.0", "현재 대상자에 속한 그룹");
	parentResource.setMessage("eb.info.assignGroup.grade.0", "등급별 그룹 배속");
	parentResource.setMessage("eb.info.assignRole.curGrade.0", "현재 등급에 배속된 역할");
	parentResource.setMessage("eb.info.assignRole.curUser.0", "현재 대상자에 속한 역할");
	parentResource.setMessage("eb.info.assignRole.grade.0", "등급별 역할 배속");
	parentResource.setMessage("eb.info.assignUser.0", "현재 배속된 사용자");
	parentResource.setMessage("eb.info.assignUser.curGrade.0", "현재 등급에 배속된 사용자");
	parentResource.setMessage("eb.info.assignUser.curUser.0", "현재 대상자에 속한 사용자");
	parentResource.setMessage("eb.info.assignUser.grade.0", "등급별 사용자 배속");
	parentResource.setMessage("eb.info.assignedAuthority.0", "현재 선택된 사용자유형에 부여된 권한입니다.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.0", "Checkbox로 선택한 사용자유형에 부여할 권한을 설정하십시오.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.G.0", "Checkbox로 선택한 그룹들에 부여할 권한을 설정하십시오.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.R.0", "Checkbox로 선택한 역할들에 부여할 권한을 설정하십시오.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.U.0", "Checkbox로 선택한 사용자들에 부여할 권한을 설정하십시오.");
	parentResource.setMessage("eb.info.assignedAuthority.Group.0", "현재 선택된 그룹에 부여된 권한입니다.");
	parentResource.setMessage("eb.info.assignedAuthority.Role.0", "현재 선택된 역할에 부여된 권한입니다.");
	parentResource.setMessage("eb.info.assignedAuthority.User.0", "현재 선택된 사용자에 부여된 권한입니다.");
	parentResource.setMessage("eb.info.attach.reorg.0", "성공적으로 재편성 되었습니다.");
	parentResource.setMessage("eb.info.authority.Access.0", "접근권한 설정");
	parentResource.setMessage("eb.info.authority.Anyone.0", "누구나 권한 설정");
	parentResource.setMessage("eb.info.authority.Grade.0", "등급별 권한 설정");
	parentResource.setMessage("eb.info.authority.Group.0", "그룹별 권한 설정");
	parentResource.setMessage("eb.info.authority.Role.0", "역할별 권한 설정");
	parentResource.setMessage("eb.info.authority.User.0", "사용자별 권한 설정");
	parentResource.setMessage("eb.info.authorize.respondents.0", "설문 참여 대상자를 전체사용자에 대해서 또는 사용자별\/그룹별\/역할별로 부여하실 수 있습니다.");
	parentResource.setMessage("eb.info.before.0", "전");
	parentResource.setMessage("eb.info.bltn.notSelected.0", "선택된 게시물이 없습니다.");
	parentResource.setMessage("eb.info.bltnExtnProp.update.0", "수정할 확장필드 정보를 선택하세요.");
	parentResource.setMessage("eb.info.board.notSelect.0", "선택된 게시판이 없습니다.");
	parentResource.setMessage("eb.info.boardId.ok.0", "사용 가능한 게시판 아이디입니다.");
	parentResource.setMessage("eb.info.boardTbl.0", "게시물 저장 테이블을 선택하십시오.");
	parentResource.setMessage("eb.info.btn.edit.0", "수정");
	parentResource.setMessage("eb.info.btn.write.0", "작성");
	parentResource.setMessage("eb.info.cancel.closeCafe.0", "선택된 카페의 폐쇄를 해제하시겠습니까?");
	parentResource.setMessage("eb.info.cant.bad.0", "에 {0}를 사용할 수 없습니다!");
	parentResource.setMessage("eb.info.cant.copy.board.domain.0", "서로 다른 도메인에 속한 카테고리로 게시판을 복사할 수 없습니다.");
	parentResource.setMessage("eb.info.cant.copy.in.same.board.0", "동일 게시판내에서는 복사할 수 없습니다.");
	parentResource.setMessage("eb.info.cant.move.board.domain.0", "서로 다른 도메인에 속한 카테고리에 게시판을 이동할 수 없습니다.");
	parentResource.setMessage("eb.info.cant.move.in.same.board.0", "동일 게시판내에서는 이동할 수 없습니다.");
	parentResource.setMessage("eb.info.cases.0", "건씩");
	parentResource.setMessage("eb.info.change.recommendList.order.0", "선택된 카페의 추천목록 순서를 변경하시겠습니까?");
	parentResource.setMessage("eb.info.check.MileageCode.policyList.0", "마일리지 코드를 선택하시면 코드내역과 마일리지 정책 목록을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.answerItem.0", "답변항목을 선택하시면 답변항목을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.answerResult.0", "응답결과를 확인하고자 하는 사용자를 선택하여 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.email.addr.format.0", "이메일주소가 올바르지 않습니다.\\n다시 확인해주세요!");
	parentResource.setMessage("eb.info.check.independentTable.0", "테이블 어근명으로 독립테이블들을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.independentTable.detail.0", "테이블 어근명을 클릭하시면 독립테이블의 자세한 사항을 조회 하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.mileagePolicyList.U.0", "사용자그룹이나 롤을 클릭하시면 해당 사용자\/롤별 마일리지 정책을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.question.replyList.0", "설문문항을 클릭하시면 문항내역과 답변항목 목록을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.check.replyResult.0", "사용자 아이디를 클릭하시면 선택된 사용자의 응답결과를 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.checkMileage.0", "발생일시를 클릭하시면 마일리지 내역을 조회하실 수 있습니다.");
	parentResource.setMessage("eb.info.choose.Feed.0", "피드를 선택하세요.");
	parentResource.setMessage("eb.info.choose.application.0", "어플리케이션을 선택하세요.");
	parentResource.setMessage("eb.info.choose.authorize.respondents.0", "설문 참여 대상자 부여 유형을 선택하십시오.");
	parentResource.setMessage("eb.info.choose.calendar.0", "캘린더를 선택하세요.");
	parentResource.setMessage("eb.info.choose.searchMileage.0", "마일리지 내역 검색 기준을 선택하십시오.");
	parentResource.setMessage("eb.info.choose.searchMileageCode.0", "마일리지 코드 검색 기준을 선택하십시오.");
	parentResource.setMessage("eb.info.choose.searchValue.0", "검색할 값을 선택해주세요.");
	parentResource.setMessage("eb.info.choose.skin.0", "스킨을 선택하세요.");
	parentResource.setMessage("eb.info.choose.skinPath.0", "스킨 경로를 선택하세요");
	parentResource.setMessage("eb.info.chooseBoard.0", "대상 게시판 선택 ");
	parentResource.setMessage("eb.info.chooseEntry.0", "Entry를 선택하세요.");
	parentResource.setMessage("eb.info.chooseGrade.G.0", "그룹을 배속시킬 등급을 선택하십시오.");
	parentResource.setMessage("eb.info.chooseGrade.R.0", "역할을 배속시킬 등급을 선택하십시오.");
	parentResource.setMessage("eb.info.chooseGrade.U.0", "사용자를 배속시킬 등급을 선택하십시오.");
	parentResource.setMessage("eb.info.chooseText.0", "선택한 게시물(들)을");
	parentResource.setMessage("eb.info.chooseType.portalDesign.0", "포털시스템 디자인 중 선호하는 유형을 선택하세요.");
	parentResource.setMessage("eb.info.chooseType.portalDesign.people.0", "포털시스템 디자인 중 선호하는 유형을 선택하세요. (총 참여인원 100명)");
	parentResource.setMessage("eb.info.chooseType.promotionVideo.0", "신용보증재단 홍보 동영상 중 선호하는 유형을 선택하세요.");
	parentResource.setMessage("eb.info.closeCafe.0", "선택된 카페를 강제로 폐쇄하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.Modify.0", "수정 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.active.0", "정말 활성화하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.addCategory.0", "카테고리를 추가하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.bookmark.add.0", "스크랩 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.cancelApproval.0", "승인취소 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.closeEntry.0", "선택된 Entry들을 비공개 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.copy.0", "정말 복사하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.create.0", "{0} 생성하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.create.board.0", "카테고리 {0}에 게시판을 생성하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.create.poll.0", "카테고리 {0}에 설문을 생성하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.del.0", "정말 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.delete.selectedSkin.0", "선택된 스킨들을 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.deleteCategory.0", "카테고리를 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.deleteFeed.0", "선택된 피드들을 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.inactive.0", "정말 비활성화하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.like.0", "호감을 표시하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.move.0", "정말 이동하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.permit.0", "이 게시물을 승인하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.prohibit.0", "이 계시물을 금지하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.recognize.0", "승인 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.recommend.0", "평가 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.refuse.0", "거절 하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.report.0", "정말 신고하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.rewrite.0", "정말 재작성하시겠습니까?\\n 지금까지 입력된 데이터를 복구할 수 없습니다.");
	parentResource.setMessage("eb.info.confirm.selectRspn.0", "이 답변을 {0} 선택하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.selectedApplication.0", "선택된 어플리케이션들을 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.spam.0", "정말 스팸 처리하시겠습니까?");
	parentResource.setMessage("eb.info.confirm.vote.0", "설문에 참여하시겠습니까?");
	parentResource.setMessage("eb.info.controlAnswer.0", "답변항목내역을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlMileage.0", "마일리지 내역을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlMileage.Code.0", "마일리지 코드를 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlMileage.policy.0", "그룹\/롤 별 마일리지 정책을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlSurvey.0", "설문을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlSurvey.question.0", "설문 문항을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.controlSurvey.score.0", "설문 평점을 생성\/수정\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.create.department.0", "부서마당을 생성하시겠습니까?");
	parentResource.setMessage("eb.info.create.newSurvey.0", "선택된 설문을 복사하여 새로운 설문을 생성하실 수 있습니다.");
	parentResource.setMessage("eb.info.date.o.invalid.0", "비 정상적인 날짜 설정입니다.");
	parentResource.setMessage("eb.info.define.iconNam.0", "메뉴 아이콘 이름을 정해주세요");
	parentResource.setMessage("eb.info.delete.recommendCafe.0", "선택된 카페를 추천카페 목록에서 제거하시겠습니까?");
	parentResource.setMessage("eb.info.deleteApplication.0", "어플리케이션이 삭제되었습니다.");
	parentResource.setMessage("eb.info.deleteFeed.0", "피드가 삭제되었습니다.");
	parentResource.setMessage("eb.info.deleteSkin.0", "스킨이 삭제되었습니다.");
	parentResource.setMessage("eb.info.deleteText.0", "삭제된 글입니다.");
	parentResource.setMessage("eb.info.deleted.post.0", "이미 삭제된 게시물입니다.");
	parentResource.setMessage("eb.info.dependGroup.0", "자체등급이 없는 게시판이므로 공통등급의 그룹정보에 의존합니다.");
	parentResource.setMessage("eb.info.dependRole.0", "자체등급이 없는 게시판이므로 공통등급의 역할정보에 의존합니다.");
	parentResource.setMessage("eb.info.dependUser.0", "자체등급이 없는 게시판이므로 공통등급의 사용자정보에 의존합니다.");
	parentResource.setMessage("eb.info.dependence.setting.0", "설정에 의존합니다.");
	parentResource.setMessage("eb.info.desc.not.exist.bltn.0", "등록된 게시물이 존재하지 않습니다.");
	parentResource.setMessage("eb.info.desc.not.exist.board.0", "등록된 게시판이 존재하지 않습니다.");
	parentResource.setMessage("eb.info.desc.operation.0", "이 게시판은 업무통합게시판 (https:\/\/board.kaist.ac.kr)에서 운영중인 게시판입니다.");
	parentResource.setMessage("eb.info.desc.push.select.board.0", "* 알림을 받고자하는 게시판을 선택하여 주세요");
	parentResource.setMessage("eb.info.descriptiveAnswer.0", "이 답변항목은   서술형  입니다");
	parentResource.setMessage("eb.info.descriptiveAnswer.item.0", "서술형 답변항목입니다");
	parentResource.setMessage("eb.info.designated.notice.0", "공지로 지정");
	parentResource.setMessage("eb.info.designated.top.notice.0", "최상위 공지로 지정");
	parentResource.setMessage("eb.info.dont.need.input.0", "입력하지 않음");
	parentResource.setMessage("eb.info.editDefault.0", "디폴트 값 편집");
	parentResource.setMessage("eb.info.evaluationLevel.0", "5=매우좋음,4=좋음,3=보통");
	parentResource.setMessage("eb.info.example.0", "예");
	parentResource.setMessage("eb.info.excelDownload.0", "설문결과를 Exel 파일로 다운로드 하실 수 있습니다");
	parentResource.setMessage("eb.info.express.delete.0", "사용이면  DB에서 삭제하지 않고 삭제표시만 한다");
	parentResource.setMessage("eb.info.file.0", "파일을 입력하세요.");
	parentResource.setMessage("eb.info.forbidden.inputWord2.0", "개XX;쪼다;씨X");
	parentResource.setMessage("eb.info.freeWrite.0", "자유롭게 이야기를 작성해 주세요. 입력 글자는 200자 내외로 작성해 주세요.");
	parentResource.setMessage("eb.info.grade.required.0", "등급이 필요합니다.");
	parentResource.setMessage("eb.info.gradecode.selectedBoard.0", "현재 선택된 게시판의 독자등급코드");
	parentResource.setMessage("eb.info.groupRole.0", "그룹\/롤 구분");
	parentResource.setMessage("eb.info.hnevent.common.chg.0", "변경");
	parentResource.setMessage("eb.info.how.respondentType.0", "응답자 유형은 어떻게 되나요? (총 참여인원 100명)");
	parentResource.setMessage("eb.info.how.respondentType.question.0", "응답자 유형은 어떻게 되나요?");
	parentResource.setMessage("eb.info.imageTest.0", "이미지 테스트");
	parentResource.setMessage("eb.info.independentTable.detailList.0", "독립테이블 상세 내역.");
	parentResource.setMessage("eb.info.input.ApplicationCode.0", "어플리케이션 코드를 입력하세요");
	parentResource.setMessage("eb.info.input.ApplicationName.0", "어플리케이션 이름을 입력하세요");
	parentResource.setMessage("eb.info.input.ApplicationVersion.0", "어플리케이션 버전을 입력하세요");
	parentResource.setMessage("eb.info.input.AttachmentfileExtension.0", "첨부를 허용할 파일 확장자를   ,   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.ImgFileName.0", "선택한 스킨 디렉터리에 있는 이미지 파일명을 입력!");
	parentResource.setMessage("eb.info.input.NoAttachmentfileExtension.0", "첨부를 금지할 파일 확장자를   ,   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.TimesLimit.0", "정책을 사용하시려면 하나 이상의 횟수 제한을 입력하십시오");
	parentResource.setMessage("eb.info.input.TwoMinute.0", "게시물 입력시 2분 경과후 재입력 가능. 즉, 2분동안 한번만 입력 가능합니다.");
	parentResource.setMessage("eb.info.input.accessible.IP.0", "게시판 접근을 허용할 아이피를   ;   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.evaluationLevel.0", "글평가 레벨의   점수=설명  을   ,   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.feedName.0", "피드 이름을 입력하세요.");
	parentResource.setMessage("eb.info.input.feedURL.0", "피드 주소를 입력하세요.");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.0", "닉네임(별명) 입력시 입력 금지 단어를   ;   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.example.0", "예)관리자;운영자");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.title.0", "제목\/본문 입력시 입력 제한 단어를   ;   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.title.example.0", "예)바보;멍청이");
	parentResource.setMessage("eb.info.input.independentTableName.0", "독립테이블 어근명을 입력하십시오.");
	parentResource.setMessage("eb.info.input.interruptAccess.ID.0", "게시판 접근을 차단할 아이디를   ;   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.interruptAccess.IP.0", "게시판 접근을 차단할 아이피를 &#039;;&#039; 구분으로 입력하십시오");
	parentResource.setMessage("eb.info.input.searchValue.0", "검색할 값을 입력해주세요.");
	parentResource.setMessage("eb.info.input.searchValue.overTwoletters.0", "검색 할 값은 두글자 이상을 입력해주세요.");
	parentResource.setMessage("eb.info.input.searchWord.0", "검색어를 입력하시오");
	parentResource.setMessage("eb.info.input.set.forbidden.inputWord.0", "게시물 입력시 입력 제한 단어를   ;   구분으로 입력하십시오.");
	parentResource.setMessage("eb.info.input.skinName.0", "스킨명을 입력하세요");
	parentResource.setMessage("eb.info.input.timesLimit.best.0", "베스트글의   레벨=제한횟수  를   ,   구분으로 입력하십시오");
	parentResource.setMessage("eb.info.integrated.board.0", "이 게시판은 \"통합형 게시판\" 입니다.");
	parentResource.setMessage("eb.info.integratedBoard.gradeCode.0", "통합게시판 공통등급코드");
	parentResource.setMessage("eb.info.invalid.content.0", "본문 내용 중 유효하지 않은 값이 포함되어 있습니다.");
	parentResource.setMessage("eb.info.knowledgeType.0", "지식형");
	parentResource.setMessage("eb.info.lateTime.0", "모든 게시물을 대상으로 함으로 다소 시간이 걸릴 수 있습니다.");
	parentResource.setMessage("eb.info.lateTime.survey.0", "모든 설문을 대상으로 함으로 다소 시간이 걸릴 수 있습니다.");
	parentResource.setMessage("eb.info.like.0", "좋아요");
	parentResource.setMessage("eb.info.liked.0", "좋아했음");
	parentResource.setMessage("eb.info.limit.commentLength.0", "50자(100byte) 이내로 댓글을 달아주시기 바랍니다.");
	parentResource.setMessage("eb.info.list.selectedCategory.0", "현재 선택된 카테고리에 소속된 게시판 목록");
	parentResource.setMessage("eb.info.message.cautionComment.0", "건전한 토론문화와 양질의 댓글 문화를 위해, 타인에게 불쾌감을 주는 욕설 또는 특정 계층\/민족, 종교 등을 비하하는 단어들은 표시가 제한됩니다.");
	parentResource.setMessage("eb.info.message.notAllowRead.0", "작성자가 글읽기를 허용하지 않았습니다");
	parentResource.setMessage("eb.info.message.notAllowWriteComent.0", "작성자가 댓글쓰기를 허용하지 않았습니다.");
	parentResource.setMessage("eb.info.message.reply.0", "댓글에 대한 답변글 등록입니다.");
	parentResource.setMessage("eb.info.mileCdMng.0", "선택된 마일리지 코드의 속성을 설정하실 수 있습니다.");
	parentResource.setMessage("eb.info.mileIo.0", "증가\/차감 구분");
	parentResource.setMessage("eb.info.move.copy.delete.0", "게시물을 이동\/복사\/삭제 하실 수 있습니다.");
	parentResource.setMessage("eb.info.move.otherCategory.0", "선택된 설문을 다른 카테고리로 이동할 수 있습니다.");
	parentResource.setMessage("eb.info.msg.copyUrl.done.0", "URL이 복사되었습니다.");
	parentResource.setMessage("eb.info.msg.event.selectCategory.0", "카테고리를 선택하세요.");
	parentResource.setMessage("eb.info.newTerm.should.be.more.than.0.0", "최신글형 게시판의 기준 경과 시간은 0 이상이어야 합니다.");
	parentResource.setMessage("eb.info.noDissent.read.0", "작성자가 글읽기를 허용하지 않았습니다");
	parentResource.setMessage("eb.info.not.apply.cafeFunction.0", "모바일(스마트폰, 테블릿피시 등)에서는 일부 카페 기능(관리, 꾸미기 기능 등)을 지원하지 않습니다.");
	parentResource.setMessage("eb.info.notUse.extendField.0", "선택된 게시판은 확장필드를 사용하지 않습니다.");
	parentResource.setMessage("eb.info.note.label.add.0", "추가");
	parentResource.setMessage("eb.info.o.cateNm.0", "카테고리 명을");
	parentResource.setMessage("eb.info.o.changeFeed.0", "피드신청 내용을 변경");
	parentResource.setMessage("eb.info.o.gradeNm.0", "등급명을");
	parentResource.setMessage("eb.info.o.lang.0", "언어를");
	parentResource.setMessage("eb.info.o.reasonCode.0", "사유코드를");
	parentResource.setMessage("eb.info.o.recommendList.order.0", "추천 목록 순서를");
	parentResource.setMessage("eb.info.o.requestFeed.0", "피드를 신청");
	parentResource.setMessage("eb.info.p.listSetCnt.0", "목록화면 목록수에");
	parentResource.setMessage("eb.info.p.recommendList.order.0", "추천 목록 순서에");
	parentResource.setMessage("eb.info.participate.0", "정상적으로 참여 되었습니다.");
	parentResource.setMessage("eb.info.point.limit.input.0", "당신의 입력 가능한 최대 포인트는 {0}입니다.");
	parentResource.setMessage("eb.info.poll.chkEvalRange.0", "시작평점은 종료평점보다 클 수 없습니다.");
	parentResource.setMessage("eb.info.poll.dupEval.0", "중복되는 평점구간이 있습니다. 평점구간을 조정하십시오.");
	parentResource.setMessage("eb.info.poll.limit.item.0", "설문 보기는 최대 9개까지 가능합니다!");
	parentResource.setMessage("eb.info.poll.min.item.0", "설문 보기는 최소 2개까지 가능합니다!");
	parentResource.setMessage("eb.info.poll.notSelect.0", "선택된 설문이 없습니다.");
	parentResource.setMessage("eb.info.pollBltn.notSelect.0", "선택된 설문문항이 없습니다.");
	parentResource.setMessage("eb.info.pollBltnCntt.0", "설문문항");
	parentResource.setMessage("eb.info.pollBltnGq.0", "설문문항 번호");
	parentResource.setMessage("eb.info.pollEval.0", "평점");
	parentResource.setMessage("eb.info.pollEval.notSelect.0", "선택된 설문평점이 없습니다.");
	parentResource.setMessage("eb.info.pollPoll.already.desc.0", "이미 서술형 답변항목이 존재합니다.");
	parentResource.setMessage("eb.info.pollPoll.notSelect.0", "선택된 답변항목이 없습니다.");
	parentResource.setMessage("eb.info.processed.acceptOpen.0", "개설승인이 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.cancelClosing.0", "폐쇄해제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.closing.0", "강제폐쇄가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.deleteCafe.0", "카페삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.deleteComment.0", "댓글(메모) 삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.deleteNotice.0", "게시물 삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.recommendCafe.0", "카페 추천이 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.processed.recommendCafe.cancel.0", "카페 추천 취소가 정상적으로 처리되었습니다.");
	parentResource.setMessage("eb.info.provide.imageBoard.0", "통합형이며 이미지가 첨부된 게시물만의 목록을 제공합니다.");
	parentResource.setMessage("eb.info.provide.mergeBoard.0", "동일카테고리에 속한 모든 게시판의 통합목록을 제공합니다.");
	parentResource.setMessage("eb.info.provide.newestBoard.0", "통합형이며 최신 게시물의 목록을 제공합니다.");
	parentResource.setMessage("eb.info.provide.popularBoard.0", "통합형이며 조회수가 높은 게시물의 목록을 제공합니다.");
	parentResource.setMessage("eb.info.pseudoBoard.0", "가상게시판");
	parentResource.setMessage("eb.info.pseudoBoardAuth.0", "가상게시판의 권한은 원본게시판 설정에 따릅니다.");
	parentResource.setMessage("eb.info.qna.answers.0", "개의 답변");
	parentResource.setMessage("eb.info.raiseCnt.should.be.more.than.0.0", "인기글형 게시판의 기준 경과 시간은 0 이상이어야 합니다.");
	parentResource.setMessage("eb.info.really.delete.0", "정말 정말 삭제하십니까?");
	parentResource.setMessage("eb.info.really.use.default.value.0", "정말 디폴트값으로 복원하시겠습니까?");
	parentResource.setMessage("eb.info.recognize.requestEstablishment.0", "선택된 카페의 개설요청을 승인하시겠습니까?");
	parentResource.setMessage("eb.info.reference.board.0", "이 게시판은 \"나만의 자료실형 게시판\" 입니다.");
	parentResource.setMessage("eb.info.restorationDefault.0", "디폴트 값으로 복원");
	parentResource.setMessage("eb.info.rss.label.add.0", "추가");
	parentResource.setMessage("eb.info.sameCate.0", "현재 카테고리와 선택된 카테고리가 동일합니다.");
	parentResource.setMessage("eb.info.save.comprehensiveTable.0", "게시물이 게시물 통합테이블에 저장됩니다.");
	parentResource.setMessage("eb.info.save.exclusiveTable.0", "게시물이 게시판 전용의 테이블에 저장됩니다.");
	parentResource.setMessage("eb.info.save.required.name.0", "제목을 입력해주세요");
	parentResource.setMessage("eb.info.saveImg.change.0", "이미지를 올린 뒤 저장해야 이미지가 변경 됩니다.");
	parentResource.setMessage("eb.info.select.cate.update.0", "수정할 카테고리를 선택하세요.");
	parentResource.setMessage("eb.info.select.copy.trgtCate.0", "복사할 대상 카테고리를 선택하세요.");
	parentResource.setMessage("eb.info.select.file.delete.0", "삭제하고자 하는 파일을 선택하세요.");
	parentResource.setMessage("eb.info.select.group.auth.0", "권한을 설정할 그룹을 선택하십시오.");
	parentResource.setMessage("eb.info.select.move.trgtCateeb.info.move.trgtCate.0", "이동할 대상 카테고리를 선택하세요.");
	parentResource.setMessage("eb.info.select.multiBltn.0", "한번에 보실 글(동시보기할 글)을 선택해 주십시요.");
	parentResource.setMessage("eb.info.select.poll.0", "답변항목을 선택하세요.");
	parentResource.setMessage("eb.info.select.role.auth.0", "권한을 설정할 역할을 선택하십시오.");
	parentResource.setMessage("eb.info.select.srchTrgt.0", "검색대상을 선택하세요.");
	parentResource.setMessage("eb.info.select.trgtBoard.0", "이동\/복사할 대상 게시판을 선택하세요.");
	parentResource.setMessage("eb.info.select.trgtPoll.0", "이동\/복사할 대상 설문을 선택하세요.");
	parentResource.setMessage("eb.info.select.userCalendar.0", "사용자 캘린더 선택");
	parentResource.setMessage("eb.info.selected.board.0", "선택된 게시판");
	parentResource.setMessage("eb.info.set.forbidden.inputWord.0", "공통 금지어 설정");
	parentResource.setMessage("eb.info.setting.AdditionalFunction.0", "의 부가 기능 설정은 실게시판");
	parentResource.setMessage("eb.info.setting.AssistanceAttribute.0", "의 보조속성 설정은 실게시판");
	parentResource.setMessage("eb.info.settingAuthority.Grade.0", "의 등급별 권한 설정은 실게시판");
	parentResource.setMessage("eb.info.settingAuthority.Group.0", "의 그룹별 권한 설정은 실게시판");
	parentResource.setMessage("eb.info.settingAuthority.User.0", "의 사용자별 권한 설정은 실게시판");
	parentResource.setMessage("eb.info.settingAuthority.board.0", "의 역할별 권한 설정은 실게시판");
	parentResource.setMessage("eb.info.settingBasic.board.0", "의 기본 기능 설정은 실게시판");
	parentResource.setMessage("eb.info.settingFunction.board.0", "의 게시판 유형 설정은 실게시판");
	parentResource.setMessage("eb.info.srchKey.0", "검색어를 입력하세요.");
	parentResource.setMessage("eb.info.support.KnowlegeFunction.0", "Naver 지식iN과 같은 기능을 지원합니다.");
	parentResource.setMessage("eb.info.support.surveyFunction.0", "설문기능을 지원합니다.");
	parentResource.setMessage("eb.info.surveyType.0", "설문형");
	parentResource.setMessage("eb.info.title.download.0", "다운로드");
	parentResource.setMessage("eb.info.title.preview.0", "바로보기");
	parentResource.setMessage("eb.info.title.write.0", "글쓰기");
	parentResource.setMessage("eb.info.toMain.0", "메인으로");
	parentResource.setMessage("eb.info.ttl.adoption.0", "채택");
	parentResource.setMessage("eb.info.ttl.allday.0", "종일");
	parentResource.setMessage("eb.info.ttl.anon.0", "익명글 여부");
	parentResource.setMessage("eb.info.ttl.answer.0", "답변");
	parentResource.setMessage("eb.info.ttl.article.no.0", "게시물 고유번호");
	parentResource.setMessage("eb.info.ttl.attach.guide.0", "*첨부파일 선택  후 반드시 추가버튼을 클릭하세요");
	parentResource.setMessage("eb.info.ttl.attach.limit.0", "*개별 첨부파일 크기 제한:20MB");
	parentResource.setMessage("eb.info.ttl.author.0", "작성자");
	parentResource.setMessage("eb.info.ttl.author.cnt.0", "작성자수");
	parentResource.setMessage("eb.info.ttl.before.post.0", "이전글");
	parentResource.setMessage("eb.info.ttl.bltnCntt.0", "본문");
	parentResource.setMessage("eb.info.ttl.bltnCntt.en.0", "본문(영문)");
	parentResource.setMessage("eb.info.ttl.bltnCntt.ko.0", "본문(한글)");
	parentResource.setMessage("eb.info.ttl.bltnSubj.0", "제목");
	parentResource.setMessage("eb.info.ttl.bltnSubj.en.0", "제목(영문)");
	parentResource.setMessage("eb.info.ttl.bltnSubj.ko.0", "제목(한글)");
	parentResource.setMessage("eb.info.ttl.bltnWriter.0", "글쓴이");
	parentResource.setMessage("eb.info.ttl.board.choose.0", "게시판선택");
	parentResource.setMessage("eb.info.ttl.boardNm.0", "게시판명");
	parentResource.setMessage("eb.info.ttl.btn.all.clear.0", "초기화");
	parentResource.setMessage("eb.info.ttl.btn.all.subs.0", "전체 알림 받기");
	parentResource.setMessage("eb.info.ttl.cate.desc.en.0", "약어(영문)");
	parentResource.setMessage("eb.info.ttl.cate.desc.ko.0", "약어(한글)");
	parentResource.setMessage("eb.info.ttl.cate.id.0", "분류 아이디");
	parentResource.setMessage("eb.info.ttl.cate.nm.en.0", "분류명(영문)");
	parentResource.setMessage("eb.info.ttl.cate.nm.ko.0", "분류명(한글)");
	parentResource.setMessage("eb.info.ttl.commentYn.0", "댓글여부");
	parentResource.setMessage("eb.info.ttl.copyUrl.0", "URL복사");
	parentResource.setMessage("eb.info.ttl.date.0", "게시일");
	parentResource.setMessage("eb.info.ttl.displayYn.0", "표시여부");
	parentResource.setMessage("eb.info.ttl.do.recommend.0", "평가하기");
	parentResource.setMessage("eb.info.ttl.email.0", "이메일");
	parentResource.setMessage("eb.info.ttl.hide.org.bltn.0", "원문닫기");
	parentResource.setMessage("eb.info.ttl.hits.0", "조회");
	parentResource.setMessage("eb.info.ttl.input.0", "입력");
	parentResource.setMessage("eb.info.ttl.job.0", "소속");
	parentResource.setMessage("eb.info.ttl.l.gradeId.0", "*등급ID*");
	parentResource.setMessage("eb.info.ttl.l.gradeNm.0", "*등급명*");
	parentResource.setMessage("eb.info.ttl.l.groupId.0", "*그룹ID*");
	parentResource.setMessage("eb.info.ttl.l.groupNm.0", "*그룹명*");
	parentResource.setMessage("eb.info.ttl.l.id.0", "*아이디*");
	parentResource.setMessage("eb.info.ttl.l.mileCd.0", "*마일리지코드*");
	parentResource.setMessage("eb.info.ttl.l.mileNm.0", "*마일리지명*");
	parentResource.setMessage("eb.info.ttl.l.name.0", "*이름*");
	parentResource.setMessage("eb.info.ttl.l.roleId.0", "*롤ID*");
	parentResource.setMessage("eb.info.ttl.l.roleNm.0", "*롤명*");
	parentResource.setMessage("eb.info.ttl.l.userId.0", "*사용자ID*");
	parentResource.setMessage("eb.info.ttl.like.0", "좋아요");
	parentResource.setMessage("eb.info.ttl.load.0", "불러오기");
	parentResource.setMessage("eb.info.ttl.memo.0", "댓글");
	parentResource.setMessage("eb.info.ttl.memo.cnt.0", "댓글수");
	parentResource.setMessage("eb.info.ttl.memoReply.0", "댓댓글");
	parentResource.setMessage("eb.info.ttl.multi.write.0", "게시글 다중등록");
	parentResource.setMessage("eb.error.InvalidContentException.0", "유효한 내용이 아닙니다 ");
	parentResource.setMessage("eb.error.already.bad.0", "이미 신고하셨습니다 ");
	parentResource.setMessage("eb.error.already.bestLimit.0", "BEST 선정 제한 갯수를 초과하였습니다.");
	parentResource.setMessage("eb.error.already.bestSet.0", "이미 BEST로 선정되었습니다 ");
	parentResource.setMessage("eb.error.already.lang.0", "이미 존재하는 언어입니다.");
	parentResource.setMessage("eb.error.already.liked.0", "이미  좋아요 한 게시물 입니다.");
	parentResource.setMessage("eb.error.already.polled.0", "이미 투표하였습니다 ");
	parentResource.setMessage("eb.error.already.rcmded.0", "이미 평가하셨습니다 ");
	parentResource.setMessage("eb.error.atch.abnormal.file.0", "정상적인 파일이 아닙니다.");
	parentResource.setMessage("eb.error.atch.limit.maxdown.0", "첨부파일 다운로드 제한 횟수만큼 이미 다운로드하셨습니다.");
	parentResource.setMessage("eb.error.bad.cntt.0", "{0}에 {1}를(을) 사용할 수 없습니다!");
	parentResource.setMessage("eb.error.bltn.privacy.0", "개인정보 패턴이 발견되었습니다");
	parentResource.setMessage("eb.error.bltn.privacy.BANK.0", "계좌번호");
	parentResource.setMessage("eb.error.bltn.privacy.CARD.0", "신용카드번호");
	parentResource.setMessage("eb.error.bltn.privacy.DRIVER.0", "운전면허번호");
	parentResource.setMessage("eb.error.bltn.privacy.HEALTH.0", "건강보험번호");
	parentResource.setMessage("eb.error.bltn.privacy.HP.0", "핸드폰번호");
	parentResource.setMessage("eb.error.bltn.privacy.PASSPORT.0", "여권번호");
	parentResource.setMessage("eb.error.bltn.privacy.SSN.0", "주민등록번호");
	parentResource.setMessage("eb.error.bltnCntt.required.0", "게시물 내용이 필요합니다 ");
	parentResource.setMessage("eb.error.bltnNo.already.deleted.0", "존재하지 않는 게시물 번호입니다 ");
	parentResource.setMessage("eb.error.bltnNo.invalid.0", "부적절한 게시물 번호입니다 ");
	parentResource.setMessage("eb.error.bltnNo.required.0", "게시물 번호가 필요합니다 ");
	parentResource.setMessage("eb.error.bltnSubj.required.0", "게시물 제목이 필요합니다 ");
	parentResource.setMessage("eb.error.board.inactive.0", "활성화되지 않은 게시판입니다.");
	parentResource.setMessage("eb.error.boardId.invalid.0", "부적절한 게시판 아이디입니다.");
	parentResource.setMessage("eb.error.boardId.required.0", "게시판 아이디가 필요합니다 ");
	parentResource.setMessage("eb.error.boardId.select.0", "게시판을 선택하세요");
	parentResource.setMessage("eb.error.cannot.writeComment.0", "댓글을 작성할 수 없습니다. 실명인증을 받으십시오.");
	parentResource.setMessage("eb.error.cannot.writeComment.Login.0", "댓글을 작성할 수 없습니다. 로그인 하십시오.");
	parentResource.setMessage("eb.error.cant.creBoard.superCate.0", "최상위 카테고리에 게시판을 생성할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.delCate.contain.0", "소속된 게시판이 존재하므로 선택된 카테고리를 삭제할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.delCate.subCate.0", "하위 카테고리가 존재하므로 선택된 카테고리를 삭제할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.delCate.sysCate.0", "시스템 디폴트 카테고리를 삭제할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.delete.memo.exist.0", "댓글이 존재하므로 삭제할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.delete.reply.exist.0", "답글이 존재하므로 삭제할 수 없습니다.");
	parentResource.setMessage("eb.error.cant.down.grade.0", "더 이상 등급을 내릴 수 없습니다.");
	parentResource.setMessage("eb.error.cant.ordDown.0", "순서를 내릴 수 없습니다.");
	parentResource.setMessage("eb.error.cant.ordUp.0", "순서를 올릴 수 없습니다.");
	parentResource.setMessage("eb.error.cant.read.file.0", "파일을 읽을 수가 없습니다.");
	parentResource.setMessage("eb.error.cant.up.grade.0", "더 이상 등급을 올릴 수 없습니다.");
	parentResource.setMessage("eb.error.cant.write.file.0", "파일이 읽기 전용입니다.");
	parentResource.setMessage("eb.error.cant.writeComment.login.0", "댓글을 작성할 수 없습니다. 로그인 하십시오.");
	parentResource.setMessage("eb.error.cant.writeComment.realName.0", "댓글을 작성할 수 없습니다. 실명인증을 받으십시오.");
	parentResource.setMessage("eb.error.cateId.required.0", "카테고리 아이디가 필요합니다 ");
	parentResource.setMessage("eb.error.confirm.surveyRecipient.0", "설문대상자를 확정할 수 없습니다.");
	parentResource.setMessage("eb.error.delete.byManager.0", "관리자에 의해 삭제되었습니다.");
	parentResource.setMessage("eb.error.duplicated.0", "중복된 자료입니다.");
	parentResource.setMessage("eb.error.exist.boardId.0", "이미 사용중인 게시판 아이디입니다.");
	parentResource.setMessage("eb.error.exist.virtual.board.0", "해당 게시판을 실게시판으로 하는 가상 게시판({0})이 존재합니다.");
	parentResource.setMessage("eb.error.extension.invalid.0", "부적절한 파일 확장자입니다.");
	parentResource.setMessage("eb.error.extension.prohibit.0", "해당 확장자의 파일 업로드는 허용되지 않습니다.");
	parentResource.setMessage("eb.error.file.delete.0", "파일 삭제 시 오류입니다.");
	parentResource.setMessage("eb.error.file.format.invalid.0", "파일 포맷이 맞지 않습니다.");
	parentResource.setMessage("eb.error.fileNm.invalid.0", "부적절한 파일명입니다.");
	parentResource.setMessage("eb.error.grade.invalid.0", "접근이 차단되었습니다 ");
	parentResource.setMessage("eb.error.grade.userExist.0", "등급에 속한 사용자가 존재합니다. 우선 소속된 사용자(\/그룹\/롤)를 제거하십시오.");
	parentResource.setMessage("eb.error.invalid.ip.0", "유효하지 않은 IP 주소입니다 ");
	parentResource.setMessage("eb.error.invalid.pass.0", "비밀번호를 확인하세요 ");
	parentResource.setMessage("eb.error.invalid.referer.0", "유효한 레퍼러가 아닙니다 ");
	parentResource.setMessage("eb.error.invalid.request.0", "잘못된 요청입니다. ");
	parentResource.setMessage("eb.error.invalid.right.0", "권한이 부족합니다 ");
	parentResource.setMessage("eb.info.ttl.mybltn.0", "내가 작성한 게시물");
	parentResource.setMessage("eb.info.ttl.name.0", "이름");
	parentResource.setMessage("eb.info.ttl.next.post.0", "다음글");
	parentResource.setMessage("eb.info.ttl.notice.0", "공지");
	parentResource.setMessage("eb.info.ttl.notice.not.0", "일반");
	parentResource.setMessage("eb.info.ttl.notice.top.0", "최상위 공지");
	parentResource.setMessage("eb.info.ttl.noticePeriod.0", "공지기간");
	parentResource.setMessage("eb.info.ttl.noticePeriod.unlimited.0", "무기한");
	parentResource.setMessage("eb.info.ttl.noticePeriod.until.0", "지정기간까지");
	parentResource.setMessage("eb.info.ttl.noticeYn.0", "공지여부");
	parentResource.setMessage("eb.info.ttl.o.bltnCntt.0", "본문을");
	parentResource.setMessage("eb.info.ttl.o.bltnSubj.0", "제목을");
	parentResource.setMessage("eb.info.ttl.o.domainId.0", "도메인 아이디를");
	parentResource.setMessage("eb.info.ttl.o.file.0", "파일을");
	parentResource.setMessage("eb.info.ttl.o.memo.0", "댓글을");
	parentResource.setMessage("eb.info.ttl.o.mileActive.0", "활성화 여부를");
	parentResource.setMessage("eb.info.ttl.o.mileCd.0", "마일리지 코드를");
	parentResource.setMessage("eb.info.ttl.o.mileDatim.0", "발생일시를");
	parentResource.setMessage("eb.info.ttl.o.mileIo.0", "증가\/차감 구분을");
	parentResource.setMessage("eb.info.ttl.o.mileNm.0", "마일리지 명을");
	parentResource.setMessage("eb.info.ttl.o.milePnt.0", "마일리지를");
	parentResource.setMessage("eb.info.ttl.o.mileSttg.0", "마일리지 정책을");
	parentResource.setMessage("eb.info.ttl.o.mileSum.0", "누적 마일리지를");
	parentResource.setMessage("eb.info.ttl.o.mileSys.0", "시스템 코드를");
	parentResource.setMessage("eb.info.ttl.o.name.0", "이름을");
	parentResource.setMessage("eb.info.ttl.o.password.0", "비밀번호를");
	parentResource.setMessage("eb.info.ttl.o.pollBltnCntt.0", "설문문항을");
	parentResource.setMessage("eb.info.ttl.o.pollBltnGq.0", "설문문항 번호를");
	parentResource.setMessage("eb.info.ttl.o.pollCntt.0", "답변항목을");
	parentResource.setMessage("eb.info.ttl.o.pollEvalRemark.0", "평점내용을");
	parentResource.setMessage("eb.info.ttl.o.pollId.0", "설문 아이디를");
	parentResource.setMessage("eb.info.ttl.o.pollKind.0", "답변항목 유형을");
	parentResource.setMessage("eb.info.ttl.o.pollNm.0", "설문명을");
	parentResource.setMessage("eb.info.ttl.o.pollReply.0", "서술형 답변을");
	parentResource.setMessage("eb.info.ttl.o.pollSeq.0", "답변항목 번호를");
	parentResource.setMessage("eb.info.ttl.o.prinId.0", "그룹\/롤\/등급 ID를");
	parentResource.setMessage("eb.info.ttl.o.prinType.0", "그룹\/롤\/등급 구분을");
	parentResource.setMessage("eb.info.ttl.o.userId.0", "사용자ID를");
	parentResource.setMessage("eb.info.ttl.org.cntt.0", "원글내용");
	parentResource.setMessage("eb.info.ttl.organ.0", "소속");
	parentResource.setMessage("eb.info.ttl.outeropen.0", "외부 공개");
	parentResource.setMessage("eb.info.ttl.p.bestRspn.0", "최우수 답변으로");
	parentResource.setMessage("eb.info.ttl.p.dlimit.0", "일별제한횟수에");
	parentResource.setMessage("eb.info.ttl.p.mileDatim.0", "발생일시에");
	parentResource.setMessage("eb.info.ttl.p.milePnt.0", "마일리지에");
	parentResource.setMessage("eb.info.ttl.p.mileSum.0", "누적 마일리지에");
	parentResource.setMessage("eb.info.ttl.p.mlimit.0", "월별제한횟수에");
	parentResource.setMessage("eb.info.ttl.p.point.0", "포인트에");
	parentResource.setMessage("eb.info.ttl.p.pollBltnGq.0", "설문문항 번호에");
	parentResource.setMessage("eb.info.ttl.p.pollEvalFrom.0", "평점(FROM)에");
	parentResource.setMessage("eb.info.ttl.p.pollEvalTo.0", "평점(To)에");
	parentResource.setMessage("eb.info.ttl.p.pollId.0", "설문 아이디에");
	parentResource.setMessage("eb.info.ttl.p.pollPnt.0", "답변항목 배점에");
	parentResource.setMessage("eb.info.ttl.p.pollSeq.0", "답변항목 번호를");
	parentResource.setMessage("eb.info.ttl.p.tlimit.0", "시간별제한횟수에");
	parentResource.setMessage("eb.info.ttl.p.wlimit.0", "주별제한횟수에");
	parentResource.setMessage("eb.info.ttl.p.ylimit.0", "년별제한횟수에");
	parentResource.setMessage("eb.info.ttl.password.0", "비밀번호");
	parentResource.setMessage("eb.info.ttl.passwordGetter.0", "비밀번호 확인");
	parentResource.setMessage("eb.info.ttl.place.0", "장소");
	parentResource.setMessage("eb.info.ttl.place.en.0", "장소(영문)");
	parentResource.setMessage("eb.info.ttl.place.ko.0", "장소(한글)");
	parentResource.setMessage("eb.info.ttl.pollEvalRemark.0", "평점내용");
	parentResource.setMessage("eb.info.ttl.question.0", "질문");
	parentResource.setMessage("eb.info.ttl.read.date.0", "조회일");
	parentResource.setMessage("eb.info.ttl.readYn.0", "읽음여부");
	parentResource.setMessage("eb.info.ttl.reply.cnt.0", "답글수");
	parentResource.setMessage("eb.info.ttl.replyYn.0", "답글여부");
	parentResource.setMessage("eb.info.ttl.schedule.0", "기간");
	parentResource.setMessage("eb.info.ttl.search.detail.0", "상세옵션");
	parentResource.setMessage("eb.info.ttl.secret.0", "비밀글 여부");
	parentResource.setMessage("eb.info.ttl.select.lang.0", "언어선택");
	parentResource.setMessage("eb.info.ttl.select.lang.bilingual.0", "다중언어");
	parentResource.setMessage("eb.info.ttl.select.lang.en.0", "영어");
	parentResource.setMessage("eb.info.ttl.select.lang.ko.0", "한국어");
	parentResource.setMessage("eb.info.ttl.seq.0", "순번");
	parentResource.setMessage("eb.info.ttl.show.org.bltn.0", "원문보기");
	parentResource.setMessage("eb.info.ttl.stts.am.0", "연계게시판");
	parentResource.setMessage("eb.info.ttl.stts.ap.0", "연계게시판");
	parentResource.setMessage("eb.info.ttl.stts.em.0", "업무게시판");
	parentResource.setMessage("eb.info.ttl.stts.ep.0", "업무게시판");
	parentResource.setMessage("eb.info.ttl.stts.in.0", "통합게시판");
	parentResource.setMessage("eb.info.ttl.term.0", "게시일");
	parentResource.setMessage("eb.info.ttl.topbltn.0", "많이 읽은 게시물");
	parentResource.setMessage("eb.info.ttl.view.cntt.0", "본문보기");
	parentResource.setMessage("eb.info.ttl.work.flag.0", "메인공지여부");
	parentResource.setMessage("eb.info.ttl.work.yn.0", "작업구분");
	parentResource.setMessage("eb.info.ttl.write.cnt.0", "등록건수");
	parentResource.setMessage("eb.info.unit.0", "단위");
	parentResource.setMessage("eb.info.unused.attachment.0", "첨부 기능 사용 안함");
	parentResource.setMessage("eb.info.upload.0", "업로드중...");
	parentResource.setMessage("eb.info.upload.limit.cnt.0", "파일첨부 개수를 초과했습니다.");
	parentResource.setMessage("eb.info.upload.limit.size.0", "첨부파일 용량 초과입니다.");
	parentResource.setMessage("eb.info.use.anon.0", "선택된 게시판의   익명(로그인전)   등급에   글쓰기   이상의 권한이 설정되어 있습니다.");
	parentResource.setMessage("eb.info.virtual.board.0", "이 게시판은 \"가상 게시판\" 입니다.");
	parentResource.setMessage("eb.info.warning.deleteAll.0", "경고! 카페상태와 관계 없이 카페와 연관된 모든 데이터를 삭제합니다. 삭제하시겠습니까?");
	parentResource.setMessage("eb.info.writing.board.0", "이 게시판은 \"내게 온 글형 게시판\" 입니다.");
	parentResource.setMessage("eb.title.error.header.0", "시스템 메세지입니다.");
	parentResource.setMessage("eb.info.o.boardTtl.0", "게시판 타이틀을");
	parentResource.setMessage("eb.title.p.extn.info.0", "확장필드 정보를");
	parentResource.setMessage("eb.info.edit.default.0", "자신만의 설정이 없는 게시판 전체에 영향을 미치는 디폴트 값을 편집 중입니다");
	parentResource.setMessage("eb.info.ttl.mileSum.0", "누적 마일리지");
	parentResource.setMessage("eb.info.o.boardNm.0", "게시판 명을");
	parentResource.setMessage("eb.info.o.surveyNm.0", "설문명을");
	parentResource.setMessage("eb.info.o.surveyExp.0", "설문 설명을");
	parentResource.setMessage("eb.info.o.title.0", "확장필드 제목을");

}
