function initialize_hn(parentResource) {
	parentResource.setMessage("hn.error.fail.getSchedule.0", "Failed to invoke a schedule of the day.");
	parentResource.setMessage("hn.error.not.exist.openSchedule.0", "No public schedule.");
	parentResource.setMessage("hn.error.not.exist.schedule.0", "There is no schedule.");
	parentResource.setMessage("hn.error.not.exist.selectedNote.0", "There is no selected message.");
	parentResource.setMessage("hn.info.inputTitle.0", "Please enter a title");
	parentResource.setMessage("hn.info.invalid.delete.owner.0", "Can not delete default calendar.");
	parentResource.setMessage("hn.info.keepNote.0", "Message has been kept,");
	parentResource.setMessage("hn.info.not.exist.registeredBanner.0", "There is no list of registered banners.");
	parentResource.setMessage("hn.info.note.delete.0", "Do you want to delete selected notes?");
	parentResource.setMessage("hn.info.permanent.deleteNote.0", "The message has been deleted.");
	parentResource.setMessage("hn.info.readingCheck.0", "All unreas notes marked readcheck.");
	parentResource.setMessage("hn.info.registeredBanner.0", "Registered banner.");
	parentResource.setMessage("hn.info.required.calendar.name.0", "Please enter calendar name.");
	parentResource.setMessage("hn.info.required.schedule.rrule.until.0", "Please select repeat end date.");
	parentResource.setMessage("hn.info.restoreNote.0", "The message has been recovered.");
	parentResource.setMessage("hn.info.save.changePoint.0", "Do you want to save changes?");
	parentResource.setMessage("hn.info.save.invaild.date.0", "Dates are incorrect.");
	parentResource.setMessage("hn.info.save.invaild.time.0", "Time selection is incorrect.");
	parentResource.setMessage("hn.info.save.required.calendar.name.0", "Please enter the calendar title.");
	parentResource.setMessage("hn.info.save.required.schedule.name.0", "Please enter schedule title.");
	parentResource.setMessage("hn.info.save.required.schedule.nameList.0", "Please enter all calendar titles in each language.");
	parentResource.setMessage("hn.info.schedule.empty.0", "Registered schedule is empty.");
	parentResource.setMessage("hn.info.schedule.rrule.byday.all.0", "Alldays");
	parentResource.setMessage("hn.info.schedule.rrule.byday.fr.0", "Friday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.mo.0", "Monday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.sa.0", "Saturday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.su.0", "Sunday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.th.0", "Thursday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.tu.0", "Tuesday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.we.0", "Wednesday");
	parentResource.setMessage("hn.info.schedule.rrule.byday.weekdays.0", "Weekdays");
	parentResource.setMessage("hn.info.schedule.rrule.noRepeat.0", "Repeating schedule is released.");
	parentResource.setMessage("hn.info.search.required.words.0", "Please enter search word at least two characters .");
	parentResource.setMessage("hn.info.selectReceiver.0", "Please select the receiver");
	parentResource.setMessage("hn.info.shippedNote.0", "The message has been sent.");
	parentResource.setMessage("hn.info.skin.is.0", "Skin is");
	parentResource.setMessage("hn.info.title.calendar.permissions.r.0", "Readonly");
	parentResource.setMessage("hn.info.title.calendar.permissions.ru.0", "Modify Schedule");
	parentResource.setMessage("hn.info.title.name.title.0", "Title");
	parentResource.setMessage("hn.info.title.name.title.en.0", "Title(English)");
	parentResource.setMessage("hn.info.title.name.title.ko.0", "Title(Korean)");
	parentResource.setMessage("hn.info.userGrp.GRP_OUT.0", "Visitor");
	parentResource.setMessage("hn.info.userGrp.GRP_PER.0", "Employee");
	parentResource.setMessage("hn.info.userGrp.GRP_PRO.0", "Faculty");
	parentResource.setMessage("hn.info.userGrp.GRP_STU.0", "Student");
	parentResource.setMessage("hn.info.userGrp.noGroup.0", "No Group");
	parentResource.setMessage("hn.info.userGrp.not.exist.0", "No Group");
	parentResource.setMessage("hn.info.userOrg.not.exist.0", "No organization");
	parentResource.setMessage("hn.info.calendar.isVisible.1.0", "Visible");
	parentResource.setMessage("hn.info.cant.blockOneself.0", "You can not block yourself.");
	parentResource.setMessage("hn.info.cant.restore.deleteCalendar.0", "When you delete a calendar, it can not be recovered. \\ N Are you sure you want to delete this calendar?");
	parentResource.setMessage("hn.info.change.receptionSetting.0", "I change the reception setting.");
	parentResource.setMessage("hn.info.choose.Feed.0", "Choose a Feed.");
	parentResource.setMessage("hn.info.choose.application.0", "Please select the application.");
	parentResource.setMessage("hn.info.choose.calendar.0", "Choose the calendar.");
	parentResource.setMessage("hn.info.choose.searchValue.0", "Please select a value to search.");
	parentResource.setMessage("hn.info.choose.skin.0", "Choose Skin.");
	parentResource.setMessage("hn.info.choose.skinPath.0", "Please select a skin path");
	parentResource.setMessage("hn.info.chooseEntry.0", "Choose your Entry.");
	parentResource.setMessage("hn.info.confirm.Modify.0", "Do you want to modify?");
	parentResource.setMessage("hn.info.confirm.addCategory.0", "Do you want to add a category?");
	parentResource.setMessage("hn.info.confirm.backup.permanentStoragebox.0", "Are you sure that you want to back up a permanent library?");
	parentResource.setMessage("hn.info.confirm.backup.sentNote.0", "Are you sure you want to backup sent note box?");
	parentResource.setMessage("hn.info.confirm.cancelApproval.0", "Are you sure you want to cancel approval?");
	parentResource.setMessage("hn.info.confirm.cancelSubscription.0", "Do you want to disable a subscription?");
	parentResource.setMessage("hn.info.confirm.change.receptionSetting.0", "Do you want to change the reception setting?");
	parentResource.setMessage("hn.info.confirm.closeEntry.0", "Are you sure you want to Private selected Entry?");
	parentResource.setMessage("hn.info.confirm.delete.0", "Do you want to delete?");
	parentResource.setMessage("hn.info.confirm.delete.calendar.0", "Do you want to delete this calendar?\\nIf you delete this calendar, that included schedule all delete");
	parentResource.setMessage("hn.info.confirm.delete.joint.0", "Do you want to delete this joint calendar?\\n If you delete, that included schedule will be not seen.");
	parentResource.setMessage("hn.info.confirm.delete.schedule.0", "Do you want to delete this schedule?");
	parentResource.setMessage("hn.info.confirm.delete.selectedSkin.0", "Are you sure you want to delete the selected skin?");
	parentResource.setMessage("hn.info.confirm.deleteCategory.0", "Are you sure you want to delete this category?");
	parentResource.setMessage("hn.info.confirm.deleteFeed.0", "Are you sure you want to delete the selected Feed?");
	parentResource.setMessage("hn.info.confirm.empty.receivedNote.0", "Are you sure you want to empty the received box?");
	parentResource.setMessage("hn.info.confirm.empty.receivingCheck.0", "Are you sure you want to empty receipt notification box?");
	parentResource.setMessage("hn.info.confirm.empty.sendNote.0", "Do you want to empty the sender Memo Box?");
	parentResource.setMessage("hn.info.confirm.empty.trash.0", "Are you sure you want to empty the recycle bin?");
	parentResource.setMessage("hn.info.confirm.keep.0", "Would you like to keep?");
	parentResource.setMessage("hn.info.confirm.readingCheck.0", "Are you sure you want to mark all unread notes?");
	parentResource.setMessage("hn.info.confirm.recognize.0", "Are you sure you want to approve?");
	parentResource.setMessage("hn.info.confirm.refuse.0", "Do you want to refuse?");
	parentResource.setMessage("hn.info.confirm.restore.0", "Are you sure you want to recover?");
	parentResource.setMessage("hn.info.confirm.save.0", "Do you want to save?");
	parentResource.setMessage("hn.info.confirm.selectedApplication.0", "Are you sure you want to delete the selected application?");
	parentResource.setMessage("hn.info.confirm.subscribe.0", "Would you like to subscribe?");
	parentResource.setMessage("hn.info.confirm.upload.0", "Do you want to upload {0} file?");
	parentResource.setMessage("hn.info.confirm.wouldYouLikeTo.0", "Would you like to ");
	parentResource.setMessage("hn.info.continueRecursion.0", "Repeats");
	parentResource.setMessage("hn.info.delete.receptionChecklist.0", "The receipt notification list has been deleted.");
	parentResource.setMessage("hn.info.deleteApplication.0", "This application has been removed.");
	parentResource.setMessage("hn.info.deleteBlocklist.0", "The user has been removed from the block list.");
	parentResource.setMessage("hn.info.deleteFeed.0", "The Feed has been deleted.");
	parentResource.setMessage("hn.info.deleteNote.0", "The message has been deleted.");
	parentResource.setMessage("hn.info.deleteSkin.0", "The skin has been removed.");
	parentResource.setMessage("hn.info.each.0", "Each");
	parentResource.setMessage("hn.info.empty.receivedNote.0", "Received note box is empty.");
	parentResource.setMessage("hn.info.empty.receivingCheck.0", "Receipt notification box is empty.");
	parentResource.setMessage("hn.info.empty.sendNote.0", "Send note box is empty.");
	parentResource.setMessage("hn.info.empty.trash.0", "Recycle bin is emtpy.");
	parentResource.setMessage("hn.info.eventPage.detailInfo.0", "Detailed information of the current event page.");
	parentResource.setMessage("hn.info.input.ApplicationCode.0", "Please enter your application code");
	parentResource.setMessage("hn.info.input.ApplicationName.0", "Enter the application name");
	parentResource.setMessage("hn.info.input.ApplicationVersion.0", "Enter the version of the application");
	parentResource.setMessage("hn.info.input.feedName.0", "Enter the Feed name.");
	parentResource.setMessage("hn.info.input.feedURL.0", "Please enter a Feed address.");
	parentResource.setMessage("hn.info.input.searchValue.0", "Please enter a value to search.");
	parentResource.setMessage("hn.info.input.searchValue.overTwoletters.0", "Please enter at least two characters to search value.");
	parentResource.setMessage("hn.info.input.searchWord.0", "Please enter at least two characters to search word.");
	parentResource.setMessage("hn.info.input.skinName.0", "Please enter the skin Name");
	parentResource.setMessage("hn.info.input.userId.0", "Please enter your user ID or name.");
	parentResource.setMessage("hn.info.inputContent.0", "Please enter your details");
	parentResource.setMessage("hn.info.addBlocklist.0", "The user has been added to the block list.");
	parentResource.setMessage("hn.info.admin.calendar.delete.fail.0", "Failed to delete the data.");
	parentResource.setMessage("hn.info.admin.calendar.delete.success.0", "Successfully deleted.");
	parentResource.setMessage("hn.info.admin.calendar.insert.calendarname.0", "Please enter calendar name.");
	parentResource.setMessage("hn.info.admin.calendar.insert.fail.0", "Failed to insert the data.");
	parentResource.setMessage("hn.info.admin.calendar.insert.success.0", "Successfully added.");
	parentResource.setMessage("hn.info.admin.calendar.question.delete.0", "Do you want to delete the data?");
	parentResource.setMessage("hn.info.admin.calendar.question.insert.0", "Do you want to insert the data?");
	parentResource.setMessage("hn.info.admin.calendar.question.update.0", "Do you want to update the data?");
	parentResource.setMessage("hn.info.admin.calendar.select.data.0", "Please select the data.");
	parentResource.setMessage("hn.info.admin.calendar.update.fail.0", "Failed to change the data.");
	parentResource.setMessage("hn.info.admin.calendar.update.success.0", "Successfully changed.");
	parentResource.setMessage("hn.info.alert.file.extension.incorrect.0", "Can not upload for file extension is {0} \\nPlease select to file extension is {1}.");
	parentResource.setMessage("hn.info.application.is.0", "Application is");
	parentResource.setMessage("hn.info.became.0", "ed");
	parentResource.setMessage("hn.info.calendar.isBilingual.0.0", "No bilingual");
	parentResource.setMessage("hn.info.calendar.isBilingual.1.0", "Use");
	parentResource.setMessage("hn.info.calendar.isHoliday.0.0", "No Holiday");
	parentResource.setMessage("hn.info.calendar.isHoliday.1.0", "Holiday");
	parentResource.setMessage("hn.info.calendar.isUse.0.0", "No use");
	parentResource.setMessage("hn.info.calendar.isUse.1.0", "Use");
	parentResource.setMessage("hn.info.calendar.isVisible.0.0", "Not Visible");

}
