function initialize_cf(parentResource) {
	parentResource.setMessage("cf.info.regFail.limitAge.before.0", "나이가 가입조건보다 적습니다.");
	parentResource.setMessage("cf.info.regFail.limitCllg.0", "가입이 불가능한 학부소속입니다.");
	parentResource.setMessage("cf.info.regFail.limitCode.0", "Your residence is not allowed to join");
	parentResource.setMessage("cf.info.regFail.limitMajor.0", "가입이 불가능한 학과\/학부입니다.");
	parentResource.setMessage("cf.info.regFail.limitOrg.0", "가입이 불가능한 조직소속입니다.");
	parentResource.setMessage("cf.info.regFail.limitQuiz.0", "가입 퀴즈가 틀렸습니다.");
	parentResource.setMessage("cf.info.regFail.limitSex.0", "가입이 불가능한 성별입니다.");
	parentResource.setMessage("cf.info.regFail.limitTerm.0", "가입제한 기간입니다.");
	parentResource.setMessage("cf.info.regFail.locCode.notExist.0", "사용자 정보에 지역정보가 없습니다.");
	parentResource.setMessage("cf.info.regFail.majorCode.notExist.0", "사용자 정보에 학과\/전공 정보가 없습니다.");
	parentResource.setMessage("cf.info.regFail.not.answ.0", "답변이 틀립니다.");
	parentResource.setMessage("cf.info.regFail.orgCode.notExist.0", "사용자 정보에 조직정보가 없습니다.");
	parentResource.setMessage("cf.info.regFail.regQstn.cnt.notMatch.0", "질문 갯수가 맞지 않습니다.");
	parentResource.setMessage("cf.info.regFail.sexFlag.notExist.0", "사용자 정보에 성별정보가 없습니다.");
	parentResource.setMessage("cf.info.rejectReason.0", "다음과 같은 사유로 카페 초대가 거부되었습니다.");
	parentResource.setMessage("cf.info.remoteControl.0", "리모컨 하단의 미리보기를 확인하면서 사용하시면 편리합니다.");
	parentResource.setMessage("cf.info.sameBoard.0", "동일 게시판입니다.");
	parentResource.setMessage("cf.info.save.noticeList.0", "공지내역을 저장하시겠습니까?");
	parentResource.setMessage("cf.info.selectBoard.0", "게시판을 선택해주세요.");
	parentResource.setMessage("cf.info.selectFile.0", "파일을 선택하세요.");
	parentResource.setMessage("cf.info.selectLayout.0", "카페 홈에 추가할 게시판의 레이아웃을 선택해 주세요.");
	parentResource.setMessage("cf.info.send.requestEmail.0", "가입을 위해 해당 카페의 카페지기에게 초대요청메일을 발송한 상태입니다.");
	parentResource.setMessage("cf.info.separator.0", "분리자가 설정되었습니다.");
	parentResource.setMessage("cf.info.setting.cafeHome.0", "현재 설정은 카페 홈에만 적용됩니다.");
	parentResource.setMessage("cf.info.shutDown.font.0", "사용중인 폰트가 서비스 종료 되었습니다. 다른 폰트를 선택해 주세요.");
	parentResource.setMessage("cf.info.state.flag.not.10.0", "가입신청 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.10.21.0", "가입신청 또는 가입거부 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.12.0", "초대신청 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.12.22.0", "초대신청 또는 초대거부 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.40.0", "활동중지 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.50.0", "자진탈퇴 상태가 아닙니다.");
	parentResource.setMessage("cf.info.state.flag.not.51.0", "강제탈퇴 상태가 아닙니다.");
	parentResource.setMessage("cf.info.todayActivities.0", "오늘 활동현황");
	parentResource.setMessage("cf.info.ttl.none.board.0", "게시판 없음");
	parentResource.setMessage("cf.info.wantJoin.0", "가입을 원하시면 카페지기에게 초대요청을 보내시기 바랍니다.");
	parentResource.setMessage("cf.info.warning.deleteAll.0", "경고! 카페상태와 관계 없이 카페와 연관된 모든 데이터(게시판 데이터 포함)를 삭제합니다. 삭제하시겠습니까?");
	parentResource.setMessage("cf.prop.basic.info.0", "기본 정보");
	parentResource.setMessage("cf.prop.cafe.basic.info.0", "카페 기본 정보");
	parentResource.setMessage("cf.prop.cafe.info.0", "카페정보");
	parentResource.setMessage("cf.prop.cafe.info.admin.0", "카페 정보 관리");
	parentResource.setMessage("cf.prop.cafe.rank.info.0", "카페 랭킹정보");
	parentResource.setMessage("cf.prop.employee.info.0", "사원정보");
	parentResource.setMessage("cf.prop.etc.info.0", "기타정보");
	parentResource.setMessage("cf.prop.info.area.0", "정보영역");
	parentResource.setMessage("cf.prop.join.info.0", "가입 정보");
	parentResource.setMessage("cf.prop.member.info.admin.0", "회원 정보 관리");
	parentResource.setMessage("cf.prop.my.info.0", "내 정보");
	parentResource.setMessage("cf.prop.my.info.update.0", "내 정보 수정");
	parentResource.setMessage("cf.prop.my.info.view.button.0", "내정보 보기 버튼");
	parentResource.setMessage("cf.prop.operator.info.0", "사업자 정보");
	parentResource.setMessage("cf.error.already.existMenu.0", "이미 카페홈 게시판으로 설정된 메뉴가 존재합니다.");
	parentResource.setMessage("cf.error.already.used.name.0", "이미 사용 중인 카페이름입니다. 다른 이름을 입력하십시오.");
	parentResource.setMessage("cf.error.already.used.url.0", "이미 사용 중인 카페주소입니다. 다른 주소를 입력하십시오.");
	parentResource.setMessage("cf.error.already.used.usernick.0", "이미 사용중인 닉네임입니다.");
	parentResource.setMessage("cf.error.cafejigi.cant.resign.0", "카페지기는 탈퇴할 수 없습니다.");
	parentResource.setMessage("cf.error.cannot.delete.0", "선택된 게시판은 삭제할 수 없습니다.");
	parentResource.setMessage("cf.error.cant.change.same.state.0", "변경하고자 하는 상태를 가진 사용자가 포함되었습니다.");
	parentResource.setMessage("cf.error.cant.change.self.grade.0", "자신의 등급은 변경할 수 없습니다.");
	parentResource.setMessage("cf.error.cant.change.staff.grade.0", "운영진은 운영진의 등급을 변경할 수 없습니다.");
	parentResource.setMessage("cf.error.cant.change.sysop.grade.0", "카페지기의 등급은 변경할 수 없습니다.");
	parentResource.setMessage("cf.error.cant.change.sysop.state.0", "카페지기의 상태를 바꿀 수 없습니다.");
	parentResource.setMessage("cf.error.cant.move2one.0", "선택한 유형의 게시판의 글은 한줄메모장 유형의 게시판으로 이동할 수 없습니다.");
	parentResource.setMessage("cf.error.cant.move2qna.0", "Q\/A형 게시판의 글은 다른 유형의 게시판으로 이동할 수 없습니다.");
	parentResource.setMessage("cf.error.cateId.required.0", "카페 아이디는  필수입니다.");
	parentResource.setMessage("cf.error.closed.cafe.0", "폐쇄된 카페입니다.");
	parentResource.setMessage("cf.error.cmntNm.required.0", "카페이름은 필수입니다.");
	parentResource.setMessage("cf.error.cmntUrl.required.0", "카페 URL은 필수입니다.");
	parentResource.setMessage("cf.error.cnat.change.wx2bjigi.0", "운영진이나 카페지기는 게시판지기가 될 수 없습니다.");
	parentResource.setMessage("cf.error.different.dateType.0", "날짜 형식에 맞지 않습니다.");
	parentResource.setMessage("cf.error.email.not.exist.0", "Email 주소가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.favorMng.request.fail.0", "잘못된 자주가는 카페 목록 변경 요청입니다.");
	parentResource.setMessage("cf.error.gradeNm.fail.0", "잘못된 등급명입니다.");
	parentResource.setMessage("cf.error.grdup.request.fail.0", "잘못된 등급조건 변경 요청입니다.");
	parentResource.setMessage("cf.error.improper.stateFlag.0", "정상적인 회원 상태가 아닙니다.");
	parentResource.setMessage("cf.error.incorrect.dateType.0", "올바른 날짜 형식이 아닙니다.");
	parentResource.setMessage("cf.error.layout.corrupt.0", "개별카페홈 레이아웃 데이터에 오류가 있어서 레이아웃을 변경할 수 없습니다.");
	parentResource.setMessage("cf.error.makerId.required.0", "카페지기 아이디는 필수입니다.");
	parentResource.setMessage("cf.error.menuMng.request.fail.0", "잘못된 메뉴 변경 요청입니다.");
	parentResource.setMessage("cf.error.newUrl.required.0", "새로운 URL은 필수입니다.");
	parentResource.setMessage("cf.error.noPermissions.write.0", "쓰기 권한이 없습니다.");
	parentResource.setMessage("cf.error.not.allow.read.0", "작성자가 글읽기를 허용하지 않았습니다.");
	parentResource.setMessage("cf.error.not.correspondUser.0", "해제하고자 하는 상태에 해당하지 않는 사용자가 포함되었습니다.");
	parentResource.setMessage("cf.error.not.decorate.0", "꾸미기를 더 이상 진행할 수 없습니다. 꾸미기를 종료한 후 다시 시작하십시오");
	parentResource.setMessage("cf.error.not.exist.approval.member.0", "승인대기 중인 회원이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.cafe.0", "존재하지 않는 카페입니다.");
	parentResource.setMessage("cf.error.not.exist.cafe.skin.0", "카페스킨이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.cafe.theme.0", "카페테마가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.cafe2.0", "해당 카페가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.cmnt.0", "존재하지 않는 커뮤니티입니다.");
	parentResource.setMessage("cf.error.not.exist.cmnt.img.0", "카페 대표 이미지가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.colorSet.0", "해당 컬러셋이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.content.0", "등록된 컨텐츠가 없습니다.");
	parentResource.setMessage("cf.error.not.exist.data.0", "데이터가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.department.0", "검색된 부서가 없습니다.");
	parentResource.setMessage("cf.error.not.exist.favor.cafe.0", "등록된 자주가는 카페가 없습니다.");
	parentResource.setMessage("cf.error.not.exist.leaveMember.0", "탈퇴회원이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.member.0", "회원이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.menuId.0", "메뉴 아이디가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.mmbr.cmntVO.cafe.0", "자주가는 카페가 지정되어 있지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.my.cafe.0", "가입한 카페가 없습니다.");
	parentResource.setMessage("cf.error.not.exist.my.cafe2.0", "새로운 카페를 개설하거나, 다양한 카페를 찾아 가입해 보세요.");
	parentResource.setMessage("cf.error.not.exist.post.0", "작성된 글이 없습니다");
	parentResource.setMessage("cf.error.not.exist.rcmd.cafe.0", "추천카페가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.rcnt.cafe.0", "최근 방문한 카페가 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.exist.to.join.cafe.0", "가입신청한 카페가 없습니다.");
	parentResource.setMessage("cf.error.not.exist.wait.levelUp.0", "등업 대기 중인 회원이 존재하지 않습니다.");
	parentResource.setMessage("cf.error.not.set.Board.0", "게시판을 7개를 초과하여 설정할 수 없습니다.");
	parentResource.setMessage("cf.error.not.set.zeroBoard.0", "게시판 갯수는 0개로 설정할 수 없습니다.\\n대신 빈 게시판은 선택할 수 있습니다.");
	parentResource.setMessage("cf.error.open.denied.0", "개설이 거부된 카페입니다.");
	parentResource.setMessage("cf.error.open.request.0", "개설신청 중인 카페입니다.");
	parentResource.setMessage("cf.error.select.wrongPeriod.0", "기간 선택이 잘못 되었습니다.");
	parentResource.setMessage("cf.info.accessCafe.0", "카페지기로부터 가입승인 메일을 받으신 후 카페에 접속하시기 바랍니다.");
	parentResource.setMessage("cf.info.add.recommendCafe.0", "선택된 카페를 추천카페 목록에 추가하시겠습니까?");
	parentResource.setMessage("cf.info.advertise.0", "알립니다!");
	parentResource.setMessage("cf.info.againTryout.0", "잠시 후에 다시 시도 해주십시오.");
	parentResource.setMessage("cf.info.already.cancel.closeCafe.0", "이미 카페 폐쇄를 취소하셨습니다.");
	parentResource.setMessage("cf.info.already.join.0", "이미 가입 하셨습니다.");
	parentResource.setMessage("cf.info.already.permit.0", "이미 승인되었습니다.");
	parentResource.setMessage("cf.info.already.rcmd.cafe.0", "이미 추천등록된 카페입니다.");
	parentResource.setMessage("cf.info.already.rejoin.0", "이미 재가입 하셨습니다.");
	parentResource.setMessage("cf.info.already.request.closeCafe.0", "이미 카페 폐쇄를 신청하셨습니다.");
	parentResource.setMessage("cf.info.already.requestInvitation.0", "이미 초대요청을 하셨습니다.");
	parentResource.setMessage("cf.info.already.requestInvitation.cancel.0", "이미 초대요청을 취소하셨습니다.");
	parentResource.setMessage("cf.info.appoint.sysop.0", "카페지기로 임명");
	parentResource.setMessage("cf.info.board.prop1.0", "선택된 유형의 게시판의 속성을 설정하실 수 있습니다.");
	parentResource.setMessage("cf.info.board.prop2.0", "이미 개설된 카페의 동일 유형 게시판들에도 영향을 미칩니다.");
	parentResource.setMessage("cf.info.by.0", "으로");
	parentResource.setMessage("cf.info.cafeHome.main.0", "카페홈 초기 메뉴로 ");
	parentResource.setMessage("cf.info.canJoin.0", "카페지기로부터 초대 메일을 받으신 후에 해당 카페에 접속하시면 카페에 가입하실 수 있습니다.");
	parentResource.setMessage("cf.info.cancel.closeCafe.0", "선택된 카페의 폐쇄를 해제하시겠습니까?");
	parentResource.setMessage("cf.info.cancel.invitationRequest.0", "초대요청이 정상적으로 취소 처리되었습니다.");
	parentResource.setMessage("cf.info.cancelProcessing.0", "정상적으로 가입 신청 취소 처리 되었습니다.");
	parentResource.setMessage("cf.info.change.recommendList.order.0", "선택된 카페의 추천목록 순서를 변경하시겠습니까?");
	parentResource.setMessage("cf.info.choose.addCafe.0", "추가할 카페를 선택해주세요");
	parentResource.setMessage("cf.info.choose.boardManager.0", "해제하시고자 하는 게시판지기를 선택하십시오.");
	parentResource.setMessage("cf.info.choose.deleteCafe.0", "제거할 카페를 선택해주세요");
	parentResource.setMessage("cf.info.choose.upperMenu.0", "추가할 메뉴의 상위 메뉴를 선택하세요.");
	parentResource.setMessage("cf.info.chooseDesign.0", "마음에 드는 디자인을 선택하세요. ");
	parentResource.setMessage("cf.info.closeCafe.0", "선택된 카페를 강제로 폐쇄하시겠습니까?");
	parentResource.setMessage("cf.info.closing.Info.0", "현재 카페지기를 제외한 회원이 없으므로 카페를 폐쇄할 수 있습니다.");
	parentResource.setMessage("cf.info.closing.Info2.0", "폐쇄가 진행된 후에는 게시글을 포함한 카페 데이터에 대한 복구가 불가능합니다.");
	parentResource.setMessage("cf.info.complete.cafeCreation.0", "카페 생성이 완료되었습니다.");
	parentResource.setMessage("cf.info.complete.joinCafe.0", "카페 회원가입이 완료되었습니다.");
	parentResource.setMessage("cf.info.completeRegistration.modifiabl.0", "신청이 완료되었습니다. 담당자 승인 전까지 수정이 가능합니다.");
	parentResource.setMessage("cf.info.confirm.closeCafe.0", "정말 카페를 폐쇄하시겠습니까?");
	parentResource.setMessage("cf.info.confirm.closeCafe.cancel.0", "카페를 폐쇄를 취소하시겠습니까?");
	parentResource.setMessage("cf.info.confirm.url.0", "사용가능한 카페주소입니다.");
	parentResource.setMessage("cf.info.confirm.usernick.0", "사용 가능한 닉네임입니다.");
	parentResource.setMessage("cf.info.continueModify.0", "계속 수정하시겠습니까?");
	parentResource.setMessage("cf.info.create.department.0", "부서마당을 생성하시겠습니까?");
	parentResource.setMessage("cf.info.deco.useColor.0", "색상을 이용하여 직접 꾸미는 방식입니다.");
	parentResource.setMessage("cf.info.define.iconName.0", "메뉴 아이콘 이름을 정해주세요");
	parentResource.setMessage("cf.info.delete.noticeList.0", "공지내역을 삭제하시겠습니까?");
	parentResource.setMessage("cf.info.delete.recommendCafe.0", "선택된 카페를 추천카페 목록에서 제거하시겠습니까?");
	parentResource.setMessage("cf.info.email.addr.not.exist.0", "이메일 주소가 없습니다.");
	parentResource.setMessage("cf.info.employee.notSeen.0", "해당 직원이 조회되지 않았습니다.");
	parentResource.setMessage("cf.info.ggum.apply.0", "현재 꾸밈 상태를 적용하시겠습니까?");
	parentResource.setMessage("cf.info.ggum.gate.apply.0", "현재 대문 편집 내역을 적용하시겠습니까?");
	parentResource.setMessage("cf.info.goOut.invitationRequest.mail.0", "초대요청 메일이 정상적으로 발송되었습니다.");
	parentResource.setMessage("cf.info.htmlEdit.0", "HTML 편집 후 저장하시면 대문영역에 나타납니다.");
	parentResource.setMessage("cf.info.input.TimesLimit.0", "정책을 사용하시려면 하나 이상의 횟수 제한을 입력하십시오");
	parentResource.setMessage("cf.info.input.onlyNumber.0", "숫자만 입력가능합니다.");
	parentResource.setMessage("cf.info.input.replyList.0", "가입설문의 답변항목을 2개 이상 입력하십시오");
	parentResource.setMessage("cf.info.input.searchWord.0", "검색어를 입력하십시오");
	parentResource.setMessage("cf.info.inputEmail.0", "e-mail을 입력하세요.");
	parentResource.setMessage("cf.info.inviteMail.0", "카페지기의 초대메일은 회원정보에 등록하신 메일주소로 발송됩니다.");
	parentResource.setMessage("cf.info.irreparable.closeCafe.0", "카페가 폐쇄되면 게시글을 포함한 모든 데이터를 복구할 수 없습니다!");
	parentResource.setMessage("cf.info.joinLink.0", "아래 링크를 통해 해당 카페에 가입하실 수 있습니다.");
	parentResource.setMessage("cf.info.keep.board.0", "보관된 게시판은  {0}일간 보관 후 자동삭제 되며, 삭제된 게시판은 복구가 불가능합니다.");
	parentResource.setMessage("cf.info.leaveProcessing.0", "정상적으로 탈퇴 처리 되었습니다.");
	parentResource.setMessage("cf.info.makeTitle.0", "한 번에 쉽고 빠르게 멋진 타이틀을 만들어 보세요");
	parentResource.setMessage("cf.info.makeTitle.easy.0", "한 번에 쉽고 빠르게 멋진 타이틀을 만들어 보아요");
	parentResource.setMessage("cf.info.margin.0", "여백이 설정되었습니다.");
	parentResource.setMessage("cf.info.mustLogin.0", "로그인 하셔야 합니다.");
	parentResource.setMessage("cf.info.myPeople.0", "우리 카페의 쪽지나 Daum카페의&lt;br&gt;유용한 정보를 마이피플로 간편하게 받아볼 수 있습니다.");
	parentResource.setMessage("cf.info.needApprove.0", "회원가입을 위해서는 카페지기의 승인이 필요한 카페입니다.");
	parentResource.setMessage("cf.info.needLogin.0", "로그인을 하셔야 합니다.");
	parentResource.setMessage("cf.info.not.exist.notice.0", "공지글이 존재하지 않습니다.");
	parentResource.setMessage("cf.info.not.existImg.0", "등록된&lt;br&gt;이미지가&lt;br&gt;없습니다.");
	parentResource.setMessage("cf.info.not.use.cafeDeco.0", "현재 브라우저로 버전으로는 카페 꾸미기를 이용하실 수 없습니다.");
	parentResource.setMessage("cf.info.o.chooseMember.0", "선택한 회원을");
	parentResource.setMessage("cf.info.o.joinQuiz.answer.0", "가입퀴즈 정답을");
	parentResource.setMessage("cf.info.o.joinQuiz.question.0", "가입퀴즈 질문을");
	parentResource.setMessage("cf.info.please.selectBoard.0", "게시판을 선택해 주세요.");
	parentResource.setMessage("cf.info.preparing.0", "준비중입니다.");
	parentResource.setMessage("cf.info.privateCafe.0", "비공개 카페입니다.");
	parentResource.setMessage("cf.info.processed.acceptOpen.0", "개설승인이 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.cancelClosing.0", "폐쇄해제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.closing.0", "강제폐쇄가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.deleteCafe.0", "카페삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.deleteComment.0", "댓글(메모) 삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.deleteNotice.0", "게시물 삭제가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.recommendCafe.0", "카페 추천이 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.processed.recommendCafe.cancel.0", "카페 추천 취소가 정상적으로 처리되었습니다.");
	parentResource.setMessage("cf.info.really.cancel.RequestIbvitation.0", "정말 초대요청을 취소하시겠습니까?");
	parentResource.setMessage("cf.info.really.delete.0", "정말 정말 삭제하시겠습니까?");
	parentResource.setMessage("cf.info.really.rejoin.0", "재가입 하시겠습니까?");
	parentResource.setMessage("cf.info.reallyCancel.0", "정말 취소 하시겠습니까?");
	parentResource.setMessage("cf.info.reallyLeave.0", "정말 탈퇴하시겠습니까?");
	parentResource.setMessage("cf.info.recognize.requestEstablishment.0", "선택된 카페의 개설요청을 승인하시겠습니까?");
	parentResource.setMessage("cf.info.reenter.cafeURL.0", "카페 주소를 다시 입력하세요.");
	parentResource.setMessage("cf.info.regFail.birthYyyy.notExist.0", "사용자 정보에 생년월일이 없습니다.");
	parentResource.setMessage("cf.info.regFail.cllgCode.notExist.0", "사용자 정보에 학부 정보가 없습니다.");
	parentResource.setMessage("cf.info.regFail.limitAge..0", "가입할 수 없는 나이입니다.");
	parentResource.setMessage("cf.info.regFail.limitAge.after.0", "Your age is greater than the subscription terms.");

}
