function initialize_eb(parentResource) {
	parentResource.setMessage("eb.info.ttl.mileSum.0", " Accumulated mileage");
	parentResource.setMessage("eb.title.error.header.0", "It is the system message.");
	parentResource.setMessage("eb.info.ttl.work.yn.0", "Work Type");
	parentResource.setMessage("eb.info.ttl.write.cnt.0", "Registrations");
	parentResource.setMessage("eb.info.unit.0", "Unit ");
	parentResource.setMessage("eb.info.unused.attachment.0", "Do not use the function to attach");
	parentResource.setMessage("eb.info.upload.0", "Uploading ...");
	parentResource.setMessage("eb.info.upload.limit.cnt.0", "You have exceeded the number of files that may be attached.");
	parentResource.setMessage("eb.info.upload.limit.size.0", "You have exceeded the volume of files that may be attached.");
	parentResource.setMessage("eb.info.use.anon.0", "The Anonymous (sign before) writing rights than the rating of the selected board has been set.");
	parentResource.setMessage("eb.info.virtual.board.0", "This is a virtual bulletin board.");
	parentResource.setMessage("eb.info.warning.deleteAll.0", "WARNING : All data are deleted. Do you want to delete?");
	parentResource.setMessage("eb.info.writing.board.0", "This is the bulletin board that came to me.");
	parentResource.setMessage("eb.info.ttl.o.mileSum.0", "Cumulative mileage");
	parentResource.setMessage("eb.info.ttl.o.mileSys.0", "system code");
	parentResource.setMessage("eb.info.ttl.o.name.0", "Name");
	parentResource.setMessage("eb.info.ttl.o.password.0", "Password");
	parentResource.setMessage("eb.info.ttl.o.pollBltnCntt.0", "Survey question");
	parentResource.setMessage("eb.info.ttl.o.pollBltnGq.0", "The number of survey question");
	parentResource.setMessage("eb.info.ttl.o.pollCntt.0", "Answer item");
	parentResource.setMessage("eb.info.ttl.o.pollEvalRemark.0", "The contents of grade");
	parentResource.setMessage("eb.info.ttl.o.pollId.0", "Survey ID");
	parentResource.setMessage("eb.info.ttl.o.pollKind.0", "the type of answer item");
	parentResource.setMessage("eb.info.ttl.o.pollNm.0", "Survey name");
	parentResource.setMessage("eb.info.ttl.o.pollReply.0", "Descriptive Answers");
	parentResource.setMessage("eb.info.ttl.o.pollSeq.0", "the number of answer item ");
	parentResource.setMessage("eb.info.ttl.o.prinId.0", "Group \/ Role \/ Grade ID");
	parentResource.setMessage("eb.info.ttl.o.prinType.0", "The division of Group \/ Role \/ Grade");
	parentResource.setMessage("eb.info.ttl.o.userId.0", "User ID");
	parentResource.setMessage("eb.info.ttl.org.cntt.0", "Original Post");
	parentResource.setMessage("eb.info.ttl.organ.0", "Organization");
	parentResource.setMessage("eb.info.ttl.outeropen.0", "Outer open");
	parentResource.setMessage("eb.info.ttl.p.bestRspn.0", "as the best answer");
	parentResource.setMessage("eb.info.ttl.p.dlimit.0", "in limited number of times by the day.");
	parentResource.setMessage("eb.info.ttl.p.mileDatim.0", "in the date and time of the occurrence");
	parentResource.setMessage("eb.info.ttl.p.milePnt.0", "Mileage");
	parentResource.setMessage("eb.info.ttl.p.mileSum.0", "in the cumulative mileage");
	parentResource.setMessage("eb.info.ttl.p.mlimit.0", "In the limited number of times by the month");
	parentResource.setMessage("eb.info.ttl.p.point.0", "In point");
	parentResource.setMessage("eb.info.ttl.p.pollBltnGq.0", "in the number of survey question");
	parentResource.setMessage("eb.info.really.use.default.value.0", "Do you want to restore the default value?");
	parentResource.setMessage("eb.info.recognize.requestEstablishment.0", "Do you confirm the request to open the selected cafe?");
	parentResource.setMessage("eb.info.reference.board.0", "This is an Own Resources Board Type.");
	parentResource.setMessage("eb.info.restorationDefault.0", "Restored to its default value");
	parentResource.setMessage("eb.info.rss.label.add.0", "Add");
	parentResource.setMessage("eb.info.sameCate.0", "The current category and the selected category are the same.");
	parentResource.setMessage("eb.info.save.comprehensiveTable.0", "The posts are stored in the publication integration table.");
	parentResource.setMessage("eb.info.save.exclusiveTable.0", "This post is stored in a table of the bulletin board only.");
	parentResource.setMessage("eb.info.save.required.name.0", "Please enter the title.");
	parentResource.setMessage("eb.info.saveImg.change.0", "You must upload and save the image to change it.");
	parentResource.setMessage("eb.info.select.cate.update.0", "Select a category which will be modified.");
	parentResource.setMessage("eb.info.select.copy.trgtCate.0", "Choose the target category to be copied.");
	parentResource.setMessage("eb.info.select.file.delete.0", "Select the file you want to delete.");
	parentResource.setMessage("eb.info.select.group.auth.0", "Select the group which establish authority.");
	parentResource.setMessage("eb.info.select.move.trgtCateeb.info.move.trgtCate.0", "Select a target category which will be moved or copied.");
	parentResource.setMessage("eb.info.select.multiBltn.0", "Select writing which can read at once (at the same time).");
	parentResource.setMessage("eb.info.select.poll.0", "Please select the answer item.");
	parentResource.setMessage("eb.info.select.role.auth.0", "Select the role which establish authority");
	parentResource.setMessage("eb.info.select.srchTrgt.0", "Please select the search target.");
	parentResource.setMessage("eb.info.select.trgtBoard.0", "Select a target board which will be moved or copied.");
	parentResource.setMessage("eb.info.select.trgtPoll.0", "Select a target survey which will be moved or copied.");
	parentResource.setMessage("eb.info.select.userCalendar.0", "User calendar selection");
	parentResource.setMessage("eb.info.selected.board.0", "Selected Forum");
	parentResource.setMessage("eb.info.set.forbidden.inputWord.0", "Common language which can not use setting");
	parentResource.setMessage("eb.info.setting.AdditionalFunction.0", "Additional function setting is available in board");
	parentResource.setMessage("eb.info.setting.AssistanceAttribute.0", "Secondary Property Settings are available in the bulletin board.");
	parentResource.setMessage("eb.info.setting.extendField.0", "Extended field setting board room");
	parentResource.setMessage("eb.info.settingAuthority.Grade.0", "For graded permission settings, see the bulletin board");
	parentResource.setMessage("eb.info.settingAuthority.Group.0", "The permissions settings by group are listed in the Bulletin Board.");
	parentResource.setMessage("eb.info.settingAuthority.User.0", "The Per-User privilege settings are listed in the Bulletin Board.");
	parentResource.setMessage("eb.info.settingAuthority.board.0", "The role of each setting permissions is board.");
	parentResource.setMessage("eb.info.settingBasic.board.0", "The default features settings are board");
	parentResource.setMessage("eb.info.settingFunction.board.0", "Bulletin Board type settings");
	parentResource.setMessage("eb.info.srchKey.0", "Please enter the search keyword.");
	parentResource.setMessage("eb.info.support.KnowlegeFunction.0", "It supports features such as Naver Knowledge iN.");
	parentResource.setMessage("eb.info.support.surveyFunction.0", "The survey supports the feature.");
	parentResource.setMessage("eb.info.surveyType.0", "Survey type");
	parentResource.setMessage("eb.info.title.download.0", "Download");
	parentResource.setMessage("eb.info.title.preview.0", "Preview");
	parentResource.setMessage("eb.info.title.write.0", "Write");
	parentResource.setMessage("eb.info.toMain.0", "To main");
	parentResource.setMessage("eb.info.ttl.adoption.0", "Adoption");
	parentResource.setMessage("eb.info.ttl.allday.0", "Allday");
	parentResource.setMessage("eb.info.ttl.anon.0", "Anonymous Y\/N");
	parentResource.setMessage("eb.info.ttl.answer.0", "Answer");
	parentResource.setMessage("eb.info.ttl.article.no.0", "Article Unique ID");
	parentResource.setMessage("eb.info.ttl.attach.guide.0", "*Please select an atachment, then click the Add button");
	parentResource.setMessage("eb.info.ttl.attach.limit.0", "*Limit the sizes of individual attached files: 20MB");
	parentResource.setMessage("eb.info.ttl.author.0", "Written by");
	parentResource.setMessage("eb.info.ttl.author.cnt.0", "Writer Count");
	parentResource.setMessage("eb.info.ttl.before.post.0", "Previous");
	parentResource.setMessage("eb.info.ttl.bltnCntt.0", "Contents");
	parentResource.setMessage("eb.info.integratedBoard.gradeCode.0", "Integrated bulletin board common grade code");
	parentResource.setMessage("eb.info.invalid.content.0", "The body contains invalid values.");
	parentResource.setMessage("eb.info.knowledgeType.0", "Knowledge type");
	parentResource.setMessage("eb.info.lateTime.0", "It may take some time since it targets all posts.");
	parentResource.setMessage("eb.info.lateTime.survey.0", "It may take some time to complete all surveys.");
	parentResource.setMessage("eb.info.like.0", "Like");
	parentResource.setMessage("eb.info.liked.0", "Liked");
	parentResource.setMessage("eb.info.limit.commentLength.0", "Please write a comment within 50 characters. (100byte).");
	parentResource.setMessage("eb.info.list.selectedCategory.0", "List of bulletins belonging to the currently selected category");
	parentResource.setMessage("eb.info.message.cautionComment.0", "Words that are offensive to other people or that disregard particular hierarchies are restricted.");
	parentResource.setMessage("eb.info.message.notAllowRead.0", "The author did not allow to read.");
	parentResource.setMessage("eb.info.message.notAllowWriteComent.0", "The author did not allow to write comments.");
	parentResource.setMessage("eb.info.message.reply.0", "Reply to the comment.");
	parentResource.setMessage("eb.info.mileCdMng.0", "You can set the attribute of selected mileage code.");
	parentResource.setMessage("eb.info.mileIo.0", "Increase \/ subtract sortation");
	parentResource.setMessage("eb.info.move.copy.delete.0", "You can move \/ copy \/ delete Posts");
	parentResource.setMessage("eb.info.move.otherCategory.0", "You can move selected survey to another category. ");
	parentResource.setMessage("eb.info.msg.copyUrl.done.0", "URL has been copied.");
	parentResource.setMessage("eb.info.msg.event.selectCategory.0", "Select a category");
	parentResource.setMessage("eb.info.newTerm.should.be.more.than.0.0", "The reference elapsed time for the most recent posting bulletin should be at least 0.");
	parentResource.setMessage("eb.info.noDissent.read.0", "Author did not allow you to read");
	parentResource.setMessage("eb.info.not.apply.cafeFunction.0", "Mobile (smartphone, tablet fish, etc.) do not support some of the cafe functions (management, decorating features, etc.).");
	parentResource.setMessage("eb.info.notUse.extendField.0", "The selected bulletin does not use the Extended field.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.U.0", "Set the permissions that will be given to the users selected with Checkbox.");
	parentResource.setMessage("eb.info.assignedAuthority.Group.0", "Permissions granted to the currently selected group.");
	parentResource.setMessage("eb.error.InvalidContentException.0", "Invalid content.");
	parentResource.setMessage("eb.error.already.bad.0", "Already reported.");
	parentResource.setMessage("eb.error.already.bestLimit.0", "Exceeded the number of BEST selection limit.");
	parentResource.setMessage("eb.error.already.bestSet.0", "It has already been chosen as the BEST  ");
	parentResource.setMessage("eb.error.already.lang.0", "It is the language already existing.");
	parentResource.setMessage("eb.error.already.liked.0", "This post is already &#039;Like&#039;.");
	parentResource.setMessage("eb.error.already.polled.0", "You have already  voted  ");
	parentResource.setMessage("eb.error.already.rcmded.0", "You have already rated  ");
	parentResource.setMessage("eb.error.atch.abnormal.file.0", "This file is not a valid file.");
	parentResource.setMessage("eb.error.atch.limit.maxdown.0", "You have already downloaded attachment files up to limited number.");
	parentResource.setMessage("eb.error.bad.cntt.0", "{1} cannot be used in {0}!");
	parentResource.setMessage("eb.error.bltn.privacy.0", "Personal information patterns have been discovered.");
	parentResource.setMessage("eb.error.bltn.privacy.BANK.0", "Bank account");
	parentResource.setMessage("eb.error.bltn.privacy.CARD.0", "Credit card number");
	parentResource.setMessage("eb.error.bltn.privacy.DRIVER.0", "Driver license number");
	parentResource.setMessage("eb.error.bltn.privacy.HEALTH.0", "Health insurance number");
	parentResource.setMessage("eb.error.bltn.privacy.HP.0", "Phone Number");
	parentResource.setMessage("eb.error.bltn.privacy.PASSPORT.0", "Passport number");
	parentResource.setMessage("eb.error.bltn.privacy.SSN.0", "Resident registration number");
	parentResource.setMessage("eb.error.bltnCntt.required.0", "The content of notice is needed  ");
	parentResource.setMessage("eb.error.bltnNo.already.deleted.0", "This post number does not exist.");
	parentResource.setMessage("eb.error.bltnNo.invalid.0", "Inappropriate number for the post.");
	parentResource.setMessage("eb.error.bltnNo.required.0", "The number for the post is required.");
	parentResource.setMessage("eb.error.bltnSubj.required.0", "Title of post is required.");
	parentResource.setMessage("eb.error.board.inactive.0", "Inactive bulletin board.");
	parentResource.setMessage("eb.error.boardId.invalid.0", "Invalid board ID.");
	parentResource.setMessage("eb.error.boardId.required.0", "Board ID required.");
	parentResource.setMessage("eb.error.boardId.select.0", "Please select a board.");
	parentResource.setMessage("eb.error.cannot.writeComment.0", "Unable to create a comment. Get real name authentication.");
	parentResource.setMessage("eb.error.cannot.writeComment.Login.0", "Unable to create a comment. Please login.");
	parentResource.setMessage("eb.error.cant.creBoard.superCate.0", "Unable to create bulletin boards in top-level categories.");
	parentResource.setMessage("eb.error.cant.delCate.contain.0", "The selected category can not be deleted because an affiliated bulletin exists.");
	parentResource.setMessage("eb.error.cant.delCate.subCate.0", "The selected category can not be deleted because the sub categories exist.");
	parentResource.setMessage("eb.error.cant.delCate.sysCate.0", "You can not delete a system default category.");
	parentResource.setMessage("eb.error.cant.delete.memo.exist.0", "This cannot be deleted since there are comments.");
	parentResource.setMessage("eb.error.cant.delete.reply.exist.0", "This cannot be deleted since there are replies.");
	parentResource.setMessage("eb.error.cant.down.grade.0", "You can\'\'t lower rank anymore.");
	parentResource.setMessage("eb.error.cant.ordDown.0", "You cannot take the order down.");
	parentResource.setMessage("eb.error.cant.ordUp.0", "You cannot take the orderp up.");
	parentResource.setMessage("eb.error.cant.read.file.0", "Cannot read the file.");
	parentResource.setMessage("eb.error.cant.up.grade.0", "Cannot raise the grade anymore.");
	parentResource.setMessage("eb.error.cant.write.file.0", "This file is read only.");
	parentResource.setMessage("eb.error.cant.writeComment.login.0", "Cannot create a comment. Please login.");
	parentResource.setMessage("eb.error.cant.writeComment.realName.0", "Cannot create a comment. Please get real name authentication.");
	parentResource.setMessage("eb.error.cateId.required.0", "Category ID required.");
	parentResource.setMessage("eb.error.confirm.surveyRecipient.0", "Connot confirm the survey recipients.");
	parentResource.setMessage("eb.error.delete.byManager.0", "It has been deleted by the administrator.");
	parentResource.setMessage("eb.error.duplicated.0", " Duplicate material.");
	parentResource.setMessage("eb.error.exist.boardId.0", "The Board ID is already in use.");
	parentResource.setMessage("eb.error.exist.virtual.board.0", "There is a virtual bulletin board ({0}) that uses this bulletin board as an actual bulletin board.");
	parentResource.setMessage("eb.error.extension.invalid.0", "Invalid file extension.");
	parentResource.setMessage("eb.error.extension.prohibit.0", "Uploading files with these extensions is not allowed.");
	parentResource.setMessage("eb.error.file.delete.0", "Encountered an error when deleting file.");
	parentResource.setMessage("eb.error.file.format.invalid.0", "File format is invalid.");
	parentResource.setMessage("eb.error.fileNm.invalid.0", "Invalid filename.");
	parentResource.setMessage("eb.error.grade.invalid.0", "Access is blocked ");
	parentResource.setMessage("eb.error.grade.userExist.0", "There are users in the rating. First remove the belonging user (\/ group \/ role).");
	parentResource.setMessage("eb.error.invalid.ip.0", "Invalid IP address.");
	parentResource.setMessage("eb.error.invalid.pass.0", "Please check your password.");
	parentResource.setMessage("eb.error.invalid.referer.0", "Not a valid referrer.");
	parentResource.setMessage("eb.error.invalid.request.0", "Invalid request.");
	parentResource.setMessage("eb.error.invalid.right.0", "Insufficient privileges");
	parentResource.setMessage("eb.error.invalid.term.0", "It would not be ready to save at one time. Please try again in a moment.");
	parentResource.setMessage("eb.info.note.label.add.0", "Add");
	parentResource.setMessage("eb.info.o.cateNm.0", "Category name");
	parentResource.setMessage("eb.info.o.changeFeed.0", "Changing the information about feed application");
	parentResource.setMessage("eb.info.o.gradeNm.0", "Grade name");
	parentResource.setMessage("eb.info.o.lang.0", "Language");
	parentResource.setMessage("eb.info.o.reasonCode.0", "The reason code");
	parentResource.setMessage("eb.info.o.recommendList.order.0", "The order of recommended list");
	parentResource.setMessage("eb.info.o.requestFeed.0", "Feed application");
	parentResource.setMessage("eb.info.p.listSetCnt.0", "In the list count of the list screen ");
	parentResource.setMessage("eb.info.p.recommendList.order.0", "In the order of recommended list");
	parentResource.setMessage("eb.info.participate.0", "Normally it has been involved.");
	parentResource.setMessage("eb.info.point.limit.input.0", "The maximum points which you can input is {0}points.");
	parentResource.setMessage("eb.info.poll.chkEvalRange.0", "Start score can not be greater than the end score.");
	parentResource.setMessage("eb.info.poll.dupEval.0", "There is the duplicated grade section. Adjust the duplicated grade section.");
	parentResource.setMessage("eb.info.poll.limit.item.0", "Seeing the survey is possible up to nine survey.");
	parentResource.setMessage("eb.info.poll.min.item.0", "Seeing the survey is possible at least two survey.");
	parentResource.setMessage("eb.info.poll.notSelect.0", "I do not have selected survey.");
	parentResource.setMessage("eb.info.pollBltn.notSelect.0", "I do not have selected questionnaire.");
	parentResource.setMessage("eb.info.pollBltnCntt.0", "Questionnaire");
	parentResource.setMessage("eb.info.pollBltnGq.0", "Questionnaire number");
	parentResource.setMessage("eb.info.pollEval.0", "Rating");
	parentResource.setMessage("eb.info.pollEval.notSelect.0", "These questionnaires are not rated.");
	parentResource.setMessage("eb.info.pollPoll.already.desc.0", "The descriptive answer already exists.");
	parentResource.setMessage("eb.info.pollPoll.notSelect.0", "The selected item is not answered.");
	parentResource.setMessage("eb.info.processed.acceptOpen.0", "Opened approval has been processed successfully.");
	parentResource.setMessage("eb.info.processed.cancelClosing.0", "Closed-off has been processed successfully.");
	parentResource.setMessage("eb.info.processed.closing.0", "Forced closure has been processed normally.");
	parentResource.setMessage("eb.info.processed.deleteCafe.0", "Deleting cafe has been processed normally.");
	parentResource.setMessage("eb.info.processed.deleteComment.0", "Deleting comment is successfully processed.");
	parentResource.setMessage("eb.info.processed.deleteNotice.0", "Deleting post have been properly processed");
	parentResource.setMessage("eb.info.processed.recommendCafe.0", "Cafe recommendation has been successfully processed.");
	parentResource.setMessage("eb.info.processed.recommendCafe.cancel.0", "The cafe recommendation cancellations have been successfully processed.");
	parentResource.setMessage("eb.info.o.boardTtl.0", "Board Title");
	parentResource.setMessage("eb.title.p.extn.info.0", "Extended field information ");
	parentResource.setMessage("eb.info.assignedAuthority.Role.0", "Permissions granted to the currently selected role.");
	parentResource.setMessage("eb.error.last.boardCateBoard.0", "Can not delete because it is the only category specific in the current bulletin.");
	parentResource.setMessage("eb.error.make.atch.dir.0", "Failed to create attachment directory.");
	parentResource.setMessage("eb.error.memoCntt.required.0", "Memo content is required.");
	parentResource.setMessage("eb.error.mmb.over.0", "Automatically deleted because of excessive number of reports.");
	parentResource.setMessage("eb.error.moveBltn.extn.not.match.0", "Extension field table mismatch.");
	parentResource.setMessage("eb.error.must.auth.realMan.0", "You need to have your real name certified.");
	parentResource.setMessage("eb.error.need.login.0", "You need to login.");
	parentResource.setMessage("eb.error.no.attachedBoard.0", "The attached bulletin does not exist.");
	parentResource.setMessage("eb.error.not.allow.replyComment.0", "The author did not allow commenting");
	parentResource.setMessage("eb.error.not.allowComment.0", "The author did not allow comments.");
	parentResource.setMessage("eb.error.not.allowReply.0", "The author did not allow to write comments.");
	parentResource.setMessage("eb.error.not.exist.0", "Records of {0} are not exist.");
	parentResource.setMessage("eb.error.not.exist.board.0", "No actual posts exist in virtual or integrated bulletins.");
	parentResource.setMessage("eb.error.not.exist.boardId.0", "Bulletin Board ID does not exist.");
	parentResource.setMessage("eb.error.not.exist.file.0", "File does not exist.");
	parentResource.setMessage("eb.error.not.exist.id.0", "The ID does not exist.");
	parentResource.setMessage("eb.error.not.exist.pollCntt.0", "The speed response item does not exist.");
	parentResource.setMessage("eb.error.not.exist.registeredContent.0", "No registered contents.");
	parentResource.setMessage("eb.error.not.exist.registeredNotice.0", "No registered posts.");
	parentResource.setMessage("eb.error.not.exist.registeredReply.0", "No registered reply.");
	parentResource.setMessage("eb.error.not.exist.replyList.0", "Answers History of the answer item does not exist.");
	parentResource.setMessage("eb.error.not.exist.surveyGrademark.0", "The assigned survey rating does not exist.");
	parentResource.setMessage("eb.error.not.exist.surveyQuestion.0", "No questions registered.");
	parentResource.setMessage("eb.error.not.exist.text.0", "No posts registered.");
	parentResource.setMessage("eb.error.not.existMethod.0", "Error: No such method exists.");
	parentResource.setMessage("eb.error.notType.0", "The target grant type is not user \/ group \/ role specific.");
	parentResource.setMessage("eb.error.notice.limit.0", "**");
	parentResource.setMessage("eb.error.orgDelYn.change.fromM.0", "Changed the deletion policy of post with replies from the current [display delete only] to another.");
	parentResource.setMessage("eb.error.orgDelYn.real.delete.0", "Actually delete the existing tombstoned posts. Do you really want to change it?");
	parentResource.setMessage("eb.error.owntbl.conflict.0", "Please check whether the boards in the same category match the independent tables.");
	parentResource.setMessage("eb.error.parameter.invalid.0", "Invalid parameter value.");
	parentResource.setMessage("eb.error.poll.inactive.0", "This questionnaire is not active.");
	parentResource.setMessage("eb.error.pollId.already.deleted.0", "This survey ID does not exist.");
	parentResource.setMessage("eb.error.pollSeq.required.0", "The voting sequence is required.");
	parentResource.setMessage("eb.error.secret.0", "This is confidential. You do not have permission.");
	parentResource.setMessage("eb.error.upload.atch.file.0", "File upload failed.");
	parentResource.setMessage("eb.error.userPass.required.0", "User password is required.");
	parentResource.setMessage("eb.info.Class.ExtendedField.0", "Extended Field Table Class");
	parentResource.setMessage("eb.info.NoLimit.0", "No Limit");
	parentResource.setMessage("eb.info.add.recommendCafe.0", "Do you want to add the selected cafe on the recommendation list?");
	parentResource.setMessage("eb.info.after.0", "After");
	parentResource.setMessage("eb.info.all.numberOfvotes.0", "The total number of votes");
	parentResource.setMessage("eb.info.alreadyJoin.0", "You have already participated.");
	parentResource.setMessage("eb.info.anon.notUse.0", "The selected bulletin board has the anonymous and real name authentication bulletin disabled.");
	parentResource.setMessage("eb.info.anyone.0", "Anybody");
	parentResource.setMessage("eb.info.anyone.login.0", "Anybody (After login)");
	parentResource.setMessage("eb.info.anyone.notlogin.0", "Anybody (Before login)");
	parentResource.setMessage("eb.info.assert.del.0", "Are you sure you want to delete it?");
	parentResource.setMessage("eb.info.assignGroup.curGrade.0", "Group assigned to the current rating");
	parentResource.setMessage("eb.info.assignGroup.curUser.0", "Groups that belong to the current target");
	parentResource.setMessage("eb.info.assignGroup.grade.0", "Group assignments by grade");
	parentResource.setMessage("eb.info.assignRole.curGrade.0", "Role assigned to current grade");
	parentResource.setMessage("eb.info.assignRole.curUser.0", "The role that belongs to the current subjects");
	parentResource.setMessage("eb.info.assignRole.grade.0", "Role assignment by grade");
	parentResource.setMessage("eb.info.assignUser.0", "Current assigned user");
	parentResource.setMessage("eb.info.assignUser.curGrade.0", "Users assigned to the current grade");
	parentResource.setMessage("eb.info.assignUser.curUser.0", "Users belonging to the current target");
	parentResource.setMessage("eb.info.assignUser.grade.0", "Assign User by Grade");
	parentResource.setMessage("eb.info.assignedAuthority.0", "Permissions granted to the currently selected user type.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.0", "Set the permissions you want to give to the type of user you select with the checkbox.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.G.0", "Set the permissions to be given to the selected groups with the checkbox.");
	parentResource.setMessage("eb.info.assignedAuthority.Checkbox.R.0", "Set the permissions that will be given to the selected roles with the checkbox.");
	parentResource.setMessage("eb.info.ttl.p.pollEvalFrom.0", "from grade");
	parentResource.setMessage("eb.info.ttl.p.pollEvalTo.0", "to grade");
	parentResource.setMessage("eb.info.ttl.p.pollId.0", "in Survey ID");
	parentResource.setMessage("eb.info.ttl.p.pollPnt.0", "in the score of answer item");
	parentResource.setMessage("eb.info.ttl.p.pollSeq.0", "the number of answer item");
	parentResource.setMessage("eb.info.ttl.p.tlimit.0", "At the timely limit count");
	parentResource.setMessage("eb.info.ttl.p.wlimit.0", "At the weekly limit count");
	parentResource.setMessage("eb.info.ttl.p.ylimit.0", "At the yearly limit count");
	parentResource.setMessage("eb.info.ttl.password.0", "Password");
	parentResource.setMessage("eb.info.ttl.passwordGetter.0", "Password Confirm ");
	parentResource.setMessage("eb.info.ttl.place.0", "Place");
	parentResource.setMessage("eb.info.ttl.place.en.0", "Place(English)");
	parentResource.setMessage("eb.info.ttl.place.ko.0", "Place(Korean)");
	parentResource.setMessage("eb.info.ttl.pollEvalRemark.0", "The contents of grade");
	parentResource.setMessage("eb.info.ttl.question.0", "Question");
	parentResource.setMessage("eb.info.ttl.read.date.0", "Read Date");
	parentResource.setMessage("eb.info.ttl.readYn.0", "Read Y\/N");
	parentResource.setMessage("eb.info.ttl.reply.cnt.0", "Reply count");
	parentResource.setMessage("eb.info.ttl.replyYn.0", "Reply Y\/N");
	parentResource.setMessage("eb.info.ttl.schedule.0", "Schedule");
	parentResource.setMessage("eb.info.ttl.search.detail.0", "Detail Options");
	parentResource.setMessage("eb.info.ttl.secret.0", "Secret");
	parentResource.setMessage("eb.info.ttl.select.lang.0", "Language");
	parentResource.setMessage("eb.info.ttl.select.lang.bilingual.0", "Bilingual");
	parentResource.setMessage("eb.info.ttl.select.lang.en.0", "English");
	parentResource.setMessage("eb.info.ttl.select.lang.ko.0", "Korean");
	parentResource.setMessage("eb.info.ttl.seq.0", "No");
	parentResource.setMessage("eb.info.ttl.show.org.bltn.0", "Show Original Post");
	parentResource.setMessage("eb.info.ttl.stts.am.0", "API board");
	parentResource.setMessage("eb.info.ttl.stts.ap.0", "API board");
	parentResource.setMessage("eb.info.ttl.stts.em.0", "Offcie Board");
	parentResource.setMessage("eb.info.ttl.stts.ep.0", "Office Board");
	parentResource.setMessage("eb.info.ttl.stts.in.0", "Integrated board");
	parentResource.setMessage("eb.info.ttl.term.0", "Published Term");
	parentResource.setMessage("eb.info.ttl.topbltn.0", "Most Read Post");
	parentResource.setMessage("eb.info.ttl.view.cntt.0", "Detail View");
	parentResource.setMessage("eb.info.ttl.work.flag.0", "Main Notice");
	parentResource.setMessage("eb.info.ttl.bltnCntt.en.0", "Contents(English)");
	parentResource.setMessage("eb.info.ttl.bltnCntt.ko.0", "Contents(Korean)");
	parentResource.setMessage("eb.info.ttl.bltnSubj.0", "Title");
	parentResource.setMessage("eb.info.ttl.bltnSubj.en.0", "Subject(English)");
	parentResource.setMessage("eb.info.ttl.bltnSubj.ko.0", "Subject(Korean)");
	parentResource.setMessage("eb.info.ttl.bltnWriter.0", "Writer");
	parentResource.setMessage("eb.info.ttl.board.choose.0", "Choose Board");
	parentResource.setMessage("eb.info.ttl.boardNm.0", "Board Name");
	parentResource.setMessage("eb.info.ttl.btn.all.clear.0", "Reset");
	parentResource.setMessage("eb.info.ttl.btn.all.subs.0", "Receive all alarm");
	parentResource.setMessage("eb.info.ttl.cate.desc.en.0", "Abbreviation(English)");
	parentResource.setMessage("eb.info.ttl.cate.desc.ko.0", "Abbreviation(Korean)");
	parentResource.setMessage("eb.info.ttl.cate.id.0", "Category ID");
	parentResource.setMessage("eb.info.ttl.cate.nm.en.0", "Category Name(English)");
	parentResource.setMessage("eb.info.ttl.cate.nm.ko.0", "Category Name(Korean)");
	parentResource.setMessage("eb.info.ttl.commentYn.0", "Comment Y\/N");
	parentResource.setMessage("eb.info.ttl.copyUrl.0", "Copy URL");
	parentResource.setMessage("eb.info.ttl.date.0", "Date");
	parentResource.setMessage("eb.info.ttl.displayYn.0", "Dispaly Y\/N");
	parentResource.setMessage("eb.info.ttl.do.recommend.0", "Post Evaluation");
	parentResource.setMessage("eb.info.ttl.email.0", "Email");
	parentResource.setMessage("eb.info.ttl.hide.org.bltn.0", "Hide Original Post");
	parentResource.setMessage("eb.info.ttl.hits.0", "Hits");
	parentResource.setMessage("eb.info.ttl.input.0", "Input");
	parentResource.setMessage("eb.info.ttl.job.0", "Job");
	parentResource.setMessage("eb.info.ttl.l.gradeId.0", "* Grade ID *");
	parentResource.setMessage("eb.info.ttl.l.gradeNm.0", "* Grade name *");
	parentResource.setMessage("eb.info.ttl.l.groupId.0", "* Group ID *");
	parentResource.setMessage("eb.info.ttl.l.groupNm.0", "* Group Name *");
	parentResource.setMessage("eb.info.ttl.l.id.0", "* ID *");
	parentResource.setMessage("eb.info.ttl.l.mileCd.0", "* Mileage code  *");
	parentResource.setMessage("eb.info.ttl.l.mileNm.0", "* Mileage name *");
	parentResource.setMessage("eb.info.ttl.l.name.0", "* Name *");
	parentResource.setMessage("eb.info.ttl.l.roleId.0", "* Role ID *");
	parentResource.setMessage("eb.info.ttl.l.roleNm.0", "* Role name *");
	parentResource.setMessage("eb.info.ttl.l.userId.0", "* User ID *");
	parentResource.setMessage("eb.info.ttl.like.0", "Like");
	parentResource.setMessage("eb.info.ttl.load.0", "Load");
	parentResource.setMessage("eb.info.ttl.memo.0", "Comment");
	parentResource.setMessage("eb.info.ttl.memo.cnt.0", "Comments");
	parentResource.setMessage("eb.info.ttl.memoReply.0", "Memo Reply");
	parentResource.setMessage("eb.info.ttl.multi.write.0", "Posting Multiple Registration");
	parentResource.setMessage("eb.info.ttl.mybltn.0", "My post");
	parentResource.setMessage("eb.info.ttl.name.0", "Name");
	parentResource.setMessage("eb.info.ttl.next.post.0", "Next");
	parentResource.setMessage("eb.info.ttl.notice.0", "Notice");
	parentResource.setMessage("eb.info.ttl.notice.not.0", "Normal");
	parentResource.setMessage("eb.info.ttl.notice.top.0", "Top Notice");
	parentResource.setMessage("eb.info.ttl.noticePeriod.0", "Notice Period");
	parentResource.setMessage("eb.info.ttl.noticePeriod.unlimited.0", "Unlimited");
	parentResource.setMessage("eb.info.ttl.noticePeriod.until.0", "Until");
	parentResource.setMessage("eb.info.ttl.noticeYn.0", "Notice");
	parentResource.setMessage("eb.info.ttl.o.bltnCntt.0", "body text");
	parentResource.setMessage("eb.info.ttl.o.bltnSubj.0", "Title");
	parentResource.setMessage("eb.info.ttl.o.domainId.0", "Domain ID");
	parentResource.setMessage("eb.info.ttl.o.file.0", "File");
	parentResource.setMessage("eb.info.ttl.o.memo.0", "Comment");
	parentResource.setMessage("eb.info.ttl.o.mileActive.0", "Activation availability ( yes or no )");
	parentResource.setMessage("eb.info.ttl.o.mileCd.0", "Mileage code");
	parentResource.setMessage("eb.info.ttl.o.mileDatim.0", "the date and time of the occurrence");
	parentResource.setMessage("eb.info.ttl.o.mileIo.0", "Increase \/ Reduction division");
	parentResource.setMessage("eb.info.ttl.o.mileNm.0", "Mileage name");
	parentResource.setMessage("eb.info.ttl.o.milePnt.0", "Mileage");
	parentResource.setMessage("eb.info.ttl.o.mileSttg.0", "Mileage Policies");
	parentResource.setMessage("eb.info.provide.imageBoard.0", "It provides a list of only the posts that are integrated and have images attached.");
	parentResource.setMessage("eb.info.provide.mergeBoard.0", "Provides an integrated list of all bulletins in the same category.");
	parentResource.setMessage("eb.info.provide.movieBoard.0", "Integrated and provide  posts that has attached video file");
	parentResource.setMessage("eb.info.provide.myownBoard.0", "Integrated and provides a list of all the posts you have created.");
	parentResource.setMessage("eb.info.provide.newestBoard.0", "Integrated and provide a list of the latest posts");
	parentResource.setMessage("eb.info.provide.popularBoard.0", "Provides a list of posts that are consolidated and have a high number of hits.");
	parentResource.setMessage("eb.info.provide.tomeBoard.0", "Integrated and provide all replies to me");
	parentResource.setMessage("eb.info.pseudoBoard.0", "Virtual bulletin board");
	parentResource.setMessage("eb.info.pseudoBoardAuth.0", "Permissions for virtual bulletins are based on the original bulletin settings.");
	parentResource.setMessage("eb.info.qna.answers.0", "Answers");
	parentResource.setMessage("eb.info.raiseCnt.should.be.more.than.0.0", "The elapsed time of the popular writing type board must be over 0.");
	parentResource.setMessage("eb.info.really.delete.0", "Do you really want to delete?");
	parentResource.setMessage("eb.info.input.independentTableName.0", "Enter independent table root name.");
	parentResource.setMessage("eb.info.input.interruptAccess.ID.0", "Enter ID to block access to bulletin board separating with ,");
	parentResource.setMessage("eb.info.input.interruptAccess.IP.0", "Enter IP to block bulletin board access, separating with ,");
	parentResource.setMessage("eb.info.input.searchValue.0", "Please enter the value to search.");
	parentResource.setMessage("eb.info.input.searchValue.overTwoletters.0", "Please enter at least two characters for search.");
	parentResource.setMessage("eb.info.input.searchWord.0", "Please enter your search term");
	parentResource.setMessage("eb.info.input.set.forbidden.inputWord.0", "When entering a post, enter the input limit word, separated by ,");
	parentResource.setMessage("eb.info.input.skinName.0", "Please enter the name of skin");
	parentResource.setMessage("eb.info.input.timesLimit.best.0", "Please enter the Level=Number Limit of best article, separated by ,");
	parentResource.setMessage("eb.info.integrated.board.0", "is an \"integrated bulletin board\".");
	parentResource.setMessage("eb.info.confirm.vote.0", "Would you like to participate in the survey?");
	parentResource.setMessage("eb.info.controlAnswer.0", "You can create \/ edit \/ delete answer item details.");
	parentResource.setMessage("eb.info.controlMileage.0", "You can create \/ modify \/ delete mileage details.");
	parentResource.setMessage("eb.info.controlMileage.Code.0", "You can create \/ edit \/ delete mileage codes.");
	parentResource.setMessage("eb.info.controlMileage.policy.0", "You can create \/ modify \/ delete mileage policies by group \/ role.");
	parentResource.setMessage("eb.info.controlSurvey.0", "You can create \/ edit \/ delete surveys.");
	parentResource.setMessage("eb.info.controlSurvey.question.0", "You can create \/ modify \/ delete question items.");
	parentResource.setMessage("eb.info.controlSurvey.score.0", "You can create \/ edit \/ delete survey ratings.");
	parentResource.setMessage("eb.info.create.department.0", "Do you want to create a department yard?");
	parentResource.setMessage("eb.info.create.newSurvey.0", "You can copy the selected survey to create a new survey.");
	parentResource.setMessage("eb.info.date.o.invalid.0", "Invalid date.");
	parentResource.setMessage("eb.info.define.iconNam.0", "Please choose a name for the menu icon.");
	parentResource.setMessage("eb.info.delete.recommendCafe.0", "Are you sure you want to remove the selected cafe from the list of recommended cafes?");
	parentResource.setMessage("eb.info.deleteApplication.0", "This application has been removed.");
	parentResource.setMessage("eb.info.deleteFeed.0", "The feed has been deleted.");
	parentResource.setMessage("eb.info.deleteSkin.0", "The skin has been removed.");
	parentResource.setMessage("eb.info.deleteText.0", "Deleted article.");
	parentResource.setMessage("eb.info.deleted.post.0", "Already deleted article.");
	parentResource.setMessage("eb.info.dependGroup.0", "This bulletin does not have a self-rating, so it relies on group information of a common rating.");
	parentResource.setMessage("eb.info.dependRole.0", "This bulletin does not have a self-rating, so it relies on role information of a common rating.");
	parentResource.setMessage("eb.info.dependUser.0", "This bulletin does not have a self-rating, so it relies on user information of a common rating.");
	parentResource.setMessage("eb.info.dependence.setting.0", "It depends on the setting.");
	parentResource.setMessage("eb.info.desc.not.exist.bltn.0", "No articles found.");
	parentResource.setMessage("eb.info.desc.not.exist.board.0", "No boards found.");
	parentResource.setMessage("eb.info.desc.operation.0", "This board is operated in KAIST Office Board(https:\/\/board.kaist.ac.kr).");
	parentResource.setMessage("eb.info.desc.push.select.board.0", "Please select a bulletin board to receive notification.");
	parentResource.setMessage("eb.info.descriptiveAnswer.0", "This answer item is descriptive.");
	parentResource.setMessage("eb.info.descriptiveAnswer.item.0", "This answer item is descriptive.");
	parentResource.setMessage("eb.info.designated.notice.0", "Designated as notification");
	parentResource.setMessage("eb.info.designated.top.notice.0", "Designated as top notification");
	parentResource.setMessage("eb.info.dont.need.input.0", "Not entered.");
	parentResource.setMessage("eb.info.edit.default.0", "You are editing a default value that affects all bulletins that do not have their own settings.");
	parentResource.setMessage("eb.info.editDefault.0", "Edit defaults");
	parentResource.setMessage("eb.info.evaluationLevel.0", "5 = Very Good, 4 = Good, 3 = Average");
	parentResource.setMessage("eb.info.example.0", "Example");
	parentResource.setMessage("eb.info.excelDownload.0", "You can download the survey results in Excel file.");
	parentResource.setMessage("eb.info.express.delete.0", "In case of use, do not delete from DB. Just mark as deleted.");
	parentResource.setMessage("eb.info.file.0", "Please input a file.");
	parentResource.setMessage("eb.info.forbidden.inputWord2.0", "Dog; tossers; Fxx");
	parentResource.setMessage("eb.info.freeWrite.0", "Please fill out the story freely. Please fill in less than 200 characters.");
	parentResource.setMessage("eb.info.grade.required.0", "The grade code is needed.");
	parentResource.setMessage("eb.info.gradecode.selectedBoard.0", "Independent grade code of the currently selected board");
	parentResource.setMessage("eb.info.groupRole.0", "Group \/ roll classification");
	parentResource.setMessage("eb.info.hnevent.common.chg.0", "Change");
	parentResource.setMessage("eb.info.how.respondentType.0", "What are the types of respondents? (Total number of participants 100 people)");
	parentResource.setMessage("eb.info.how.respondentType.question.0", "What are the types of respondents?");
	parentResource.setMessage("eb.info.imageTest.0", "Image test");
	parentResource.setMessage("eb.info.independentTable.detailList.0", "Independence table details.");
	parentResource.setMessage("eb.info.input.ApplicationCode.0", "Please enter your application code");
	parentResource.setMessage("eb.info.input.ApplicationName.0", "Please enter the application name.");
	parentResource.setMessage("eb.info.input.ApplicationVersion.0", "Please enter the version of the application");
	parentResource.setMessage("eb.info.input.AttachmentfileExtension.0", "Please enter the file extension to allow attachment separating with ,");
	parentResource.setMessage("eb.info.input.ImgFileName.0", "Enter the name of the image file in the selected skin directory!");
	parentResource.setMessage("eb.info.input.NoAttachmentfileExtension.0", "Please enter the file extension to ban attachment separating with ,");
	parentResource.setMessage("eb.info.input.TimesLimit.0", "Please enter at least one number limit to enable policy.");
	parentResource.setMessage("eb.info.input.TwoMinute.0", "When you enter a post, you can re-enter after 2 minutes, i.e. you can enter it only once for 2 minut");
	parentResource.setMessage("eb.info.input.accessible.IP.0", "Enter IP to allow bulletin board access separating with ,");
	parentResource.setMessage("eb.info.input.evaluationLevel.0", "Please enter Score=Description of level of article evaluation separating with ,");
	parentResource.setMessage("eb.info.input.feedName.0", "Enter the feed name.");
	parentResource.setMessage("eb.info.input.feedURL.0", "Please enter the feed address.");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.0", "Enter a prohibited word when typing a nickname (nickname) separating with ,");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.example.0", "ex)Manager;Operator");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.title.0", "Enter the entry limit word when entering the subject \/ body separating with ,");
	parentResource.setMessage("eb.info.input.forbidden.inputWord.title.example.0", "ex)Fool,BoneHead");
	parentResource.setMessage("eb.info.cancel.closeCafe.0", "Are you sure you want to unclos the selected cafe?");
	parentResource.setMessage("eb.info.cant.bad.0", "You cannot use {0}!");
	parentResource.setMessage("eb.info.cant.copy.board.domain.0", "You can not copy bulletin boards to categories that belong to different domains.");
	parentResource.setMessage("eb.info.cant.copy.in.same.board.0", "Can not copy within the same bulletin board.");
	parentResource.setMessage("eb.info.cant.move.board.domain.0", "You can not move bulletins to categories that belong to different domains.");
	parentResource.setMessage("eb.info.cant.move.in.same.board.0", "Can not move within the same bulletin board.");
	parentResource.setMessage("eb.info.cases.0", "Per case");
	parentResource.setMessage("eb.info.change.recommendList.order.0", "Do you want to change the order of recommended lists for the selected cafes?");
	parentResource.setMessage("eb.info.check.MileageCode.policyList.0", "Select a mileage code to view the code details and list of mileage policies.");
	parentResource.setMessage("eb.info.check.answerItem.0", "You can inquire the answer item by selecting the answer item.");
	parentResource.setMessage("eb.info.check.answerResult.0", "You can select the users who want to check the response result.");
	parentResource.setMessage("eb.info.check.email.addr.format.0", "Your email address is not valid. Please check again!");
	parentResource.setMessage("eb.info.check.independentTable.0", "You can look up independent tables with table root names.");
	parentResource.setMessage("eb.info.check.independentTable.detail.0", "You can inquire the details of the independent table by clicking the table root name.");
	parentResource.setMessage("eb.info.check.mileagePolicyList.U.0", "Click on the user group or roll to view the mileage policy by User\/Roll.");
	parentResource.setMessage("eb.info.check.question.replyList.0", "Click on the questionnaire to view the list of questions and answers.");
	parentResource.setMessage("eb.info.check.replyResult.0", "Click the User ID to view the selected user\'s response results.");
	parentResource.setMessage("eb.info.checkMileage.0", "You can inquire mileage details by clicking the date of occurrence.");
	parentResource.setMessage("eb.info.choose.Feed.0", "Choose a feed.");
	parentResource.setMessage("eb.info.choose.application.0", "Please select an application.");
	parentResource.setMessage("eb.info.choose.authorize.respondents.0", "Please select the type of person you would like to participate in the survey.");
	parentResource.setMessage("eb.info.choose.calendar.0", "Choose a calendar.");
	parentResource.setMessage("eb.info.choose.searchMileage.0", "Please select mileage search criteria.");
	parentResource.setMessage("eb.info.choose.searchMileageCode.0", "Please select mileage code search criteria.");
	parentResource.setMessage("eb.info.choose.searchValue.0", "Select a value to search for.");
	parentResource.setMessage("eb.info.choose.skin.0", "Choose a skin.");
	parentResource.setMessage("eb.info.choose.skinPath.0", "Please select a skin path.");
	parentResource.setMessage("eb.info.chooseBoard.0", "Select the target board");
	parentResource.setMessage("eb.info.chooseEntry.0", "Choose an entry.");
	parentResource.setMessage("eb.info.chooseGrade.G.0", "Select the grade to which you want to assign the group.");
	parentResource.setMessage("eb.info.chooseGrade.R.0", "Select the grade to which you want to assign roles.");
	parentResource.setMessage("eb.info.chooseGrade.U.0", "Select the grade to which you want to assign users.");
	parentResource.setMessage("eb.info.chooseText.0", "Selected post (s)");
	parentResource.setMessage("eb.info.chooseType.portalDesign.0", "Select your preferred type of portal system design.");
	parentResource.setMessage("eb.info.chooseType.portalDesign.people.0", "Select your preferred type of portal system design. (Total number of participants 100 people)");
	parentResource.setMessage("eb.info.chooseType.promotionVideo.0", "Select your preferred type of video clip from the Credit Guarantee Foundation.");
	parentResource.setMessage("eb.info.closeCafe.0", "Do you want to force the closure of the selected cafe?");
	parentResource.setMessage("eb.info.confirm.Modify.0", "Do you want to modify?");
	parentResource.setMessage("eb.info.confirm.active.0", "Are you sure you want to activate?");
	parentResource.setMessage("eb.info.confirm.addCategory.0", "Do you want to add a category?");
	parentResource.setMessage("eb.info.confirm.bookmark.add.0", "Would you like to clip it?");
	parentResource.setMessage("eb.info.confirm.cancelApproval.0", "Are you sure you want to cancel the approval?");
	parentResource.setMessage("eb.info.confirm.closeEntry.0", "Do you want to keep the selected entries private?");
	parentResource.setMessage("eb.info.confirm.copy.0", "Are you sure you want to copy it?");
	parentResource.setMessage("eb.info.confirm.create.0", "Would you like to create {0}?");
	parentResource.setMessage("eb.info.confirm.create.board.0", "Would you like to create the bulletin board in the category {0} ?");
	parentResource.setMessage("eb.info.confirm.create.poll.0", "Would you like to create the survey in the category {0} ?");
	parentResource.setMessage("eb.info.confirm.del.0", "Are you sure you want to delete it?");
	parentResource.setMessage("eb.info.confirm.delete.selectedSkin.0", "Do you want to delete the selected skins?");
	parentResource.setMessage("eb.info.confirm.deleteCategory.0", "Do you want to delete this category?");
	parentResource.setMessage("eb.info.confirm.deleteFeed.0", "Do you want to delete the selected feeds?");
	parentResource.setMessage("eb.info.confirm.inactive.0", "Are you sure you want to deactivate?");
	parentResource.setMessage("eb.info.confirm.like.0", "Would you like to display good impression ?");
	parentResource.setMessage("eb.info.confirm.move.0", "Are you sure you want to move?");
	parentResource.setMessage("eb.info.confirm.permit.0", "Do you confirm the approval of this post?");
	parentResource.setMessage("eb.info.confirm.prohibit.0", "Do you want to ban this post?");
	parentResource.setMessage("eb.info.confirm.recognize.0", "Do you want to approve?");
	parentResource.setMessage("eb.info.confirm.recommend.0", "Do you want to evaluate?");
	parentResource.setMessage("eb.info.confirm.refuse.0", "Do you want to refuse?");
	parentResource.setMessage("eb.info.confirm.report.0", "Do you want to report?");
	parentResource.setMessage("eb.info.confirm.rewrite.0", "Do you want to rewrite? You cannot restore the data which has been entered until now.");
	parentResource.setMessage("eb.info.confirm.selectRspn.0", "Would you like to pick this reply?");
	parentResource.setMessage("eb.info.confirm.selectedApplication.0", "Do you want to delete the selected application?");
	parentResource.setMessage("eb.info.confirm.spam.0", "Do you really want to spam?");
	parentResource.setMessage("eb.info.assignedAuthority.User.0", "Permissions granted to the currently selected user.");
	parentResource.setMessage("eb.info.attach.reorg.0", "Successfully reorganized.");
	parentResource.setMessage("eb.info.authority.Access.0", "Restrictions settings");
	parentResource.setMessage("eb.info.authority.Anyone.0", "Permission setting to Everyone");
	parentResource.setMessage("eb.info.authority.Grade.0", "Permission setting by Grade");
	parentResource.setMessage("eb.info.authority.Group.0", "Permission setting by Group");
	parentResource.setMessage("eb.info.authority.Role.0", "Permission setting by Role");
	parentResource.setMessage("eb.info.authority.User.0", "Permission setting by User");
	parentResource.setMessage("eb.info.authorize.respondents.0", "Survey participants can be assigned to all users or per users \/ groups \/ roles.");
	parentResource.setMessage("eb.info.before.0", "Before");
	parentResource.setMessage("eb.info.bltn.notSelected.0", "No posts are selected.");
	parentResource.setMessage("eb.info.bltnExtnProp.update.0", "Select the information of the extended field which will be modified.");
	parentResource.setMessage("eb.info.board.notSelect.0", "No selected bulletin board.");
	parentResource.setMessage("eb.info.boardId.ok.0", "Available board ID.");
	parentResource.setMessage("eb.info.boardTbl.0", "Select the table to save the post.");
	parentResource.setMessage("eb.info.btn.edit.0", "Editing");
	parentResource.setMessage("eb.info.btn.write.0", "Writing");
	parentResource.setMessage("eb.info.o.boardNm.0", "Board Name");
	parentResource.setMessage("eb.info.o.surveyNm.0", "Survey name");
	parentResource.setMessage("eb.info.o.surveyExp.0", "Survey Description");
	parentResource.setMessage("eb.info.o.title.0", "Extension Field  Title");

}
