function initialize_ev(parentResource) {
	parentResource.setMessage("ev.info.updateSystemPortlet.0", "If system portlet does wrong change, system error will be occurred because system portlet is used internally.");
	parentResource.setMessage("ev.info.user.Welcome.0", "Welcome");
	parentResource.setMessage("ev.info.user.character.0", "Please enter the first character of the ID in lower English character.");
	parentResource.setMessage("ev.info.user.disabledAccount.0", "Your account has been withdrawn or suspended.");
	parentResource.setMessage("ev.info.user.failToConfirmForName.0", "Fail to confirm real name.");
	parentResource.setMessage("ev.info.user.invalidConfirmPassword.0", "Confirm password is not corrected.");
	parentResource.setMessage("ev.info.user.invalidPassword.0", "Password is not corrected.");
	parentResource.setMessage("ev.info.user.invalidRegNo.0", "Enter correct your registry number.");
	parentResource.setMessage("ev.info.user.invalidUserEmail.0", "Enter correct your E-mail.");
	parentResource.setMessage("ev.info.user.invalidUserHp.0", "Enter correct your mobile phone number.");
	parentResource.setMessage("ev.info.user.invalidUserId.0", "Enter correct your ID, length 6~12,Alphabetic character,number and special character (_).");
	parentResource.setMessage("ev.info.user.invalidUserIdOrInfo.0", "Correct ID or user information do not exist.");
	parentResource.setMessage("ev.info.user.requiredAgree.0", "Do not agree for terms and conditions.");
	parentResource.setMessage("ev.info.user.requiredEnglish.0", "Enter correct your ID, length 5~12,Alphabetic character,number and special character (_).");
	parentResource.setMessage("ev.info.user.requiredNumber.0", "Enter number type.");
	parentResource.setMessage("ev.info.user.requiredOverlapCheck.0", "Please check overlap ID.");
	parentResource.setMessage("ev.info.wait.0", "Please wait a moment...");
	parentResource.setMessage("ev.info.warning.system.update.0", "Please be careful for update system portlet is very important");
	parentResource.setMessage("ev.info.what.addFunction.0", "What are the features that need to be added to the portal system? (Participants 100)");
	parentResource.setMessage("ev.info.what.addFunction.question.0", "What are the features that need to be added to the portal system?");
	parentResource.setMessage("ev.msg.selectGoogleAddEvent.schedule.add.error.0", "An error occurred while adding the schedule. Please try again.");
	parentResource.setMessage("ev.info.message.success.update.0", "Successfully changed.");
	parentResource.setMessage("ev.info.modified.0", "Page was modified. Do you save modified data ?");
	parentResource.setMessage("ev.info.mypage.portlet.error.add.0", "Failed to add the portlet");
	parentResource.setMessage("ev.info.mypage.portlet.error.already.0", "The portlet already exists.");
	parentResource.setMessage("ev.info.mypage.portlet.error.location.0", "This portlet may not enter the designated position.");
	parentResource.setMessage("ev.info.mypage.portlet.error.location.list.0", "Movement within the portlet list is impossible.");
	parentResource.setMessage("ev.info.mypage.portlet.error.move.0", "Failed to move the portlet");
	parentResource.setMessage("ev.info.notFoundData.0", "Not found data");
	parentResource.setMessage("ev.info.o.cancel.0", "Cancel");
	parentResource.setMessage("ev.info.o.registration.0", "Registration");
	parentResource.setMessage("ev.info.page.editPortlet.0", "Edit Portlet:");
	parentResource.setMessage("ev.info.page.removePortlet.0", "Remove Portlet");
	parentResource.setMessage("ev.info.pageEditing.Layout.0", "Edit Layout");
	parentResource.setMessage("ev.info.pageEditingPageTheme.0", "Page Theme");
	parentResource.setMessage("ev.info.permission.generateFolder.0", "Would you like to add all subordinate pages of the selected folder ?");
	parentResource.setMessage("ev.info.portalAboutMessage.0", "This program is protected by copyright law. Replicating all or part of the program from unauthorized or distribution may result in severe civil and criminal law, it will be prosecuted.");
	parentResource.setMessage("ev.info.portalAboutVersion.0", "Version");
	parentResource.setMessage("ev.info.portlet.SelectorName.0", "Select Portlet");
	parentResource.setMessage("ev.info.portlet.image.0", "Enter the registered icon file name size by 22x22 pixel");
	parentResource.setMessage("ev.info.portlet.resourcebundle.0", "Enter the resource name in the class path");
	parentResource.setMessage("ev.info.querySize.0", "Total result size is {0}");
	parentResource.setMessage("ev.info.quick.add.0", "Add a present page on quick-menu");
	parentResource.setMessage("ev.info.quick.remove.0", "Delete quick-menu");
	parentResource.setMessage("ev.info.reload.0", "All portlets in Database will be substitute by portletxml in file Are you sure?");
	parentResource.setMessage("ev.info.remove.0", "Are you sure to delete?");
	parentResource.setMessage("ev.info.remove.can.not.0", "You can not delete because it is set as the main page");
	parentResource.setMessage("ev.info.removeFolder.0", "You can not delete Folder");
	parentResource.setMessage("ev.info.requiredName.0", "Please enter a title");
	parentResource.setMessage("ev.info.reset.0", "Are you sure to reset?");
	parentResource.setMessage("ev.info.restore.0", "Are you sure to restore?");
	parentResource.setMessage("ev.info.resultSize.0", "Total count is {0}.");
	parentResource.setMessage("ev.info.search.searchUser.0", "Find the user according to search.");
	parentResource.setMessage("ev.info.select.appname.0", "Select Portlet Application");
	parentResource.setMessage("ev.info.select.copyPage.0", "The location which copy selection ");
	parentResource.setMessage("ev.info.select.movePage.0", "The location you want to move selection");
	parentResource.setMessage("ev.info.select.onlyone.0", "Please choose only one");
	parentResource.setMessage("ev.info.setting.accessRight.0", "Setting permission to access posts");
	parentResource.setMessage("ev.info.stop.0", "Are you sure to stop ?");
	parentResource.setMessage("ev.info.success.add.0", "Successfully added.");
	parentResource.setMessage("ev.info.success.copy.0", "Successfully copied.");
	parentResource.setMessage("ev.info.success.delete.0", "Successfully deleted.");
	parentResource.setMessage("ev.info.success.move.0", "Successfully moved.");
	parentResource.setMessage("ev.info.success.reload.0", "Successfully reloaded.");
	parentResource.setMessage("ev.info.success.remove.0", "Successfully removed.");
	parentResource.setMessage("ev.info.success.restore.0", "Successfully restored.");
	parentResource.setMessage("ev.info.success.update.0", "Successfully updated.");
	parentResource.setMessage("ev.info.success.write.0", "Successfully saved as portlet.xml");
	parentResource.setMessage("ev.info.successAdd.0", "Successfully added");
	parentResource.setMessage("ev.info.successRemove.0", "Successfully deleted");
	parentResource.setMessage("ev.info.successUpdate.0", "Successfully updated.");
	parentResource.setMessage("ev.info.template.0", "Template");
	parentResource.setMessage("ev.info.title.0", "Title");
	parentResource.setMessage("ev.info.title.notice.0", "notice");
	parentResource.setMessage("ev.info.tree.groupTabTitle.0", "Group Category");
	parentResource.setMessage("ev.info.tree.node.copy.0", "Do you want to copy {0} to {1} ?");
	parentResource.setMessage("ev.info.tree.node.copyAll.0", "Would you like to copy all the pages of low-path ?");
	parentResource.setMessage("ev.info.tree.node.folder.remove.0", "It will be deleted all node under {0}. Are you sure ?");
	parentResource.setMessage("ev.info.tree.node.move.0", "Do you want to move {0} to {1} ?");
	parentResource.setMessage("ev.info.tree.node.remove.0", "Are you sure delete : {0} ?");
	parentResource.setMessage("ev.info.tree.pageTabTitle.0", "Page Category");
	parentResource.setMessage("ev.info.tree.roleTabTitle.0", "Role Category");
	parentResource.setMessage("ev.info.tree.tabTitle.0", "Category Tree");
	parentResource.setMessage("ev.info.tree.title.0", "Site tree");
	parentResource.setMessage("ev.info.uniqueOk.0", "This name is available.");
	parentResource.setMessage("ev.info.designate.notice.0", "Specified in the notice");
	parentResource.setMessage("ev.info.detailEvent.service.update.0", "The updating of the service. We apologize for any inconvenience to use.");
	parentResource.setMessage("ev.info.detailEvent.url.form.wrong.0", "The URL is malformed.");
	parentResource.setMessage("ev.info.domain.movePage.0", "Only same domain is possible to move.");
	parentResource.setMessage("ev.info.empty.0", "There is no registered information.");
	parentResource.setMessage("ev.info.file.save.0", "File is saved.");
	parentResource.setMessage("ev.info.file.successupload.0", "uploaded");
	parentResource.setMessage("ev.info.fileresultSize.0", "The whole hits of file are {0} hits.");
	parentResource.setMessage("ev.info.forbiden.deleteAdmin.0", "Can not delete admin.");
	parentResource.setMessage("ev.info.forbiden.deleteRoot.0", "You can not delete top-level nodes.");
	parentResource.setMessage("ev.info.forbiden.hangul.0", "Please enter ascii code only");
	parentResource.setMessage("ev.error.user.ErrorCode.3.0", "This user account is now disabled. Please contact the administrator for detailed information.");
	parentResource.setMessage("ev.error.user.ErrorCode.3001.0", "The administrator is available only on the specified PC.");
	parentResource.setMessage("ev.error.user.ErrorCode.4.0", "It is an invalid password. Warning : You can only login once for this account.");
	parentResource.setMessage("ev.error.user.ErrorCode.5.0", "The password for this user account is disabled. Please contact your administrator.");
	parentResource.setMessage("ev.error.user.ErrorCode.6.0", "The password of this user account is expired. Please contact the administrator.");
	parentResource.setMessage("ev.error.user.ErrorCode.8.0", "You have exceeded the number of password errors. Please contact your administrator.");
	parentResource.setMessage("ev.error.user.ErrorCode.9.0", "The new password and its confirmation do not match.");
	parentResource.setMessage("ev.error.user.ErrorCode.98.0", "This page is inaccessible.");
	parentResource.setMessage("ev.error.user.ErrorCode.EmptyAnswer.0", "Enter security text.");
	parentResource.setMessage("ev.error.user.ErrorCode.EmptyPass.0", "Enter your password");
	parentResource.setMessage("ev.error.user.ErrorCode.EmptyPassword.0", "Enter your password");
	parentResource.setMessage("ev.error.user.ErrorCode.EmptyUserID.0", "Please enter user ID");
	parentResource.setMessage("ev.error.user.ErrorCode.WrongAnswer.0", "Security text is incorrect.");
	parentResource.setMessage("ev.error.validation.0", "{0}？？(？？) ？？？？？？吏？ ？？？？ 媛？？？？？？.");
	parentResource.setMessage("ev.error.validation.byte.0", "{0} must be a byte type.");
	parentResource.setMessage("ev.error.validation.creditCard.0", "{0} is not a valid number of credit card.");
	parentResource.setMessage("ev.error.validation.date.0", "{0} is not a date type.");
	parentResource.setMessage("ev.error.validation.double.0", "{0} must be a double type.");
	parentResource.setMessage("ev.error.validation.email.0", "{0} is the invalid email address.");
	parentResource.setMessage("ev.error.validation.float.0", "{0} must be a float value.");
	parentResource.setMessage("ev.error.validation.floatRange.0", "{0} must be a value between {1} and {2}.");
	parentResource.setMessage("ev.error.validation.intRange.0", "{0} must be a value between {1} and {2}.");
	parentResource.setMessage("ev.error.validation.integer.0", "{0} must be a integer value.");
	parentResource.setMessage("ev.error.validation.korean.0", "{0} is not a Korean.");
	parentResource.setMessage("ev.error.validation.long.0", "{0} must be a long type.");
	parentResource.setMessage("ev.error.validation.mask.0", "{0} is not a valid value.");
	parentResource.setMessage("ev.error.validation.maxlength.0", "{0} can not be entered more than {1} characters.");
	parentResource.setMessage("ev.error.validation.minlength.0", "{0} must be entered more than {1} characters.");
	parentResource.setMessage("ev.error.validation.range.0", "{0} must be a value between {1} and {2}.");
	parentResource.setMessage("ev.error.validation.required.0", "{0} is  a required input values.");
	parentResource.setMessage("ev.error.validation.short.0", "{0} must be a short value.");
	parentResource.setMessage("ev.error.validation.ssn.0", "{0} is not a valid resident registration number.");
	parentResource.setMessage("ev.info.forbiden.updateRoot.0", "You can not modify the top-level node.");
	parentResource.setMessage("ev.info.generateUserMenu.0", "Would you like to create a menu of the selected users? ");
	parentResource.setMessage("ev.info.icon.addPortlet.0", "Add portlet");
	parentResource.setMessage("ev.info.icon.editPage.0", "Edit page");
	parentResource.setMessage("ev.info.icon.editPortlet.0", "Portlet attribute edit");
	parentResource.setMessage("ev.info.icon.movePortlet.0", "Portlet movement");
	parentResource.setMessage("ev.info.icon.removePortlet.0", "Portlet deletion");
	parentResource.setMessage("ev.info.icon.savePage.0", "Save page");
	parentResource.setMessage("ev.info.ignoreAlterations.0", "Permission to access posts has been changed but not applied. Do you want to ignore the changes?");
	parentResource.setMessage("ev.info.init.password.0", "Password reset to user ID.Are you sure you want to proceed?");
	parentResource.setMessage("ev.info.insertEventByUser.processing.0", "It is being processed.");
	parentResource.setMessage("ev.info.join.satisfactionInvestigation.0", "Would you like to participate in satisfaction survey?");
	parentResource.setMessage("ev.info.join.satisfactionInvestigation.Error.0", "Sorry. An error occurred while processing the satisfaction suvey. Please try again later.");
	parentResource.setMessage("ev.info.join.satisfactionInvestigation.Login.0", "To participate in the satisfaction survey, you must first log in.");
	parentResource.setMessage("ev.info.join.satisfactionInvestigation.OK.0", "You have successfully participated in satisfaction surveys. Thank you for your participation.");
	parentResource.setMessage("ev.info.layout.0", "Layout");
	parentResource.setMessage("ev.info.limit.Attachment.0", "You can attach files up to 10, full capacity can not exceed 100 Mbyte.");
	parentResource.setMessage("ev.info.link.noimg.0", "It is registered as the default image.");
	parentResource.setMessage("ev.info.link.noimgreg.0", "Registered as the default image.");
	parentResource.setMessage("ev.info.mainEvent.register.0", "Main event can register within latest 30 days until 7 case.");
	parentResource.setMessage("ev.info.menu.addCategory.0", "Add Category");
	parentResource.setMessage("ev.info.menu.addGroup.0", "Add group");
	parentResource.setMessage("ev.info.menu.addPage.0", "Add Page");
	parentResource.setMessage("ev.info.menu.addRole.0", "add role");
	parentResource.setMessage("ev.info.menu.copyPage.0", "Copy page");
	parentResource.setMessage("ev.info.menu.delete.0", "Delete");
	parentResource.setMessage("ev.info.menu.deletePage.0", "Delete page");
	parentResource.setMessage("ev.info.menu.loadExcel.0", "Excel input (Import)");
	parentResource.setMessage("ev.info.menu.moveDown.0", "Move Down");
	parentResource.setMessage("ev.info.menu.movePage.0", "Move page");
	parentResource.setMessage("ev.info.menu.moveUp.0", "Move Up");
	parentResource.setMessage("ev.info.menu.refresh.0", "Refresh");
	parentResource.setMessage("ev.info.menu.saveExcel.0", "Excel output (Export)");
	parentResource.setMessage("ev.info.menu.upload.0", "Uploading");
	parentResource.setMessage("ev.info.message.book.empty.0", "Scrap list not found");
	parentResource.setMessage("ev.info.message.fav.empty.0", "Your favorites have not been registered.");
	parentResource.setMessage("ev.info.message.hotlink.empty.0", "The menu has not been registered or you have no authority.");
	parentResource.setMessage("ev.info.message.kaist.board.0", "Board");
	parentResource.setMessage("ev.info.message.kaist.etc.0", "Etc");
	parentResource.setMessage("ev.info.message.kaist.notice.0", "Notice");
	parentResource.setMessage("ev.info.message.mysetting.checknum.0", "Only numbers may be entered.");
	parentResource.setMessage("ev.info.message.mysetting.del.0", "Are you sure you want to delete this?");
	parentResource.setMessage("ev.info.message.mysetting.init.0", "Would you like to initialize the shortcut? Stored immediately after initialization.");
	parentResource.setMessage("ev.info.message.mysetting.notvalue.0", "There is no input value. Please check.");
	parentResource.setMessage("ev.info.message.mysetting.save.0", "Saved");
	parentResource.setMessage("ev.info.message.quicklink.empty.0", "The menu has not been registered or you have no authority.");
	parentResource.setMessage("ev.info.message.quicklink.invalid.ip.0", "This function can not be used in connected IP .");
	parentResource.setMessage("ev.info.message.remove.0", "Successfully deleted.");
	parentResource.setMessage("ev.info.message.search.0", "Please enter search word.");
	parentResource.setMessage("ev.info.message.search.noinput.0", "Please enter search word.");
	parentResource.setMessage("ev.info.message.search.notype.0", "Please select the search type.");
	parentResource.setMessage("ev.info.message.search.searchLength.0", "Please enter at least two characters search word.");
	parentResource.setMessage("ev.info.message.success.add.0", "Successfully added.");
	parentResource.setMessage("ev.info.ResultSize.0", "Total result size is {0}");
	parentResource.setMessage("ev.info.active.0", "Are you sure to active portlet ?");
	parentResource.setMessage("ev.info.addFile.0", "Add File");
	parentResource.setMessage("ev.info.breakdown.useFunction.0", "Function History");
	parentResource.setMessage("ev.info.categoryList.selectedBoard.0", "List of post categories for the currently selected bulletin");
	parentResource.setMessage("ev.info.changeCategory.0", "Are you sure you want to change the category?");
	parentResource.setMessage("ev.info.choiceOnlyone.0", "Please select only one row.");
	parentResource.setMessage("ev.info.choose.score.0", "Please select the scores");
	parentResource.setMessage("ev.info.click.searchUser.0", "Click the User ID to inquire the usage status of selected users by bulletin board.");
	parentResource.setMessage("ev.info.clickBoard.searchUser.0", "Click the bulletin board to inquire the selected bulletin board \/ user usage details.");
	parentResource.setMessage("ev.info.clickUser.searchUser.0", "Click the user name to inquire the selected bulletin board \/ user usage details.");
	parentResource.setMessage("ev.info.columnSizeOver.0", "Total column size is too big(100)");
	parentResource.setMessage("ev.info.columnsizeOver.0", "The size of the whole colum can not be higher than 100.");
	parentResource.setMessage("ev.info.deleteFile.0", "Delete Files");
	parentResource.setMessage("ev.info.designate.mostNotice.0", "Designated as the highest notice.");
	parentResource.setMessage("ev.error.update.link.req.0", "Duplicate API addresses. Please re-enter.");
	parentResource.setMessage("ev.error.update.link.svc.0", "Duplicate service code. Please re-enter");
	parentResource.setMessage("ev.error.upload.file.select.0", "Select file to upload.");
	parentResource.setMessage("ev.error.upload.limit.cnt.0", "The maximum number of attached file is exceed");
	parentResource.setMessage("ev.error.user.ErrorCode.1.0", "It is an invalid username.");
	parentResource.setMessage("ev.error.user.ErrorCode.100.0", "You do not have permission to use the system. Please contact the administrator.");
	parentResource.setMessage("ev.error.user.ErrorCode.2.0", "It is an invalid password.");
	parentResource.setMessage("ev.error.user.ErrorCode.2001.0", "The user on the certificate and the login user are different.");
	parentResource.setMessage("ev.error.user.ErrorCode.2002.0", "You must login with the certificate.");
	parentResource.setMessage("ev.error.domain.commonremove.0", "common can not be deleted.");
	parentResource.setMessage("ev.error.domain.remove.0", "Please delete after deleting in domain management");
	parentResource.setMessage("ev.error.duplicated.0", "It is a name that already exists. Please use a different name.");
	parentResource.setMessage("ev.error.duplicatedLang.0", "lt is the language that already exists. Please select a different language.");
	parentResource.setMessage("ev.error.exceed.mypageNumber.0", "My page can not add more than {0}.");
	parentResource.setMessage("ev.error.file.savefail.0", "Please use it after selecting the file which possible to edit.");
	parentResource.setMessage("ev.error.insert.link.req.0", "API 二쇱？媛？ 以？났？？？？？？. ？？？？ ？？？？？？ 二쇱？？？");
	parentResource.setMessage("ev.error.insert.link.svc.0", "Duplicate service code. Please re-enter");
	parentResource.setMessage("ev.error.insufficientPermissions.0", "You do not have the authority. Please contact your administrator.");
	parentResource.setMessage("ev.error.mail.failToSendEmail.0", "The computer failed to send email.");
	parentResource.setMessage("ev.error.mypage.max.0", "You may add up to three pages at maximum.");
	parentResource.setMessage("ev.error.noAuthority.read.0", "You do not have permission to read this post.");
	parentResource.setMessage("ev.error.noAuthority.write.0", "You do not have write permissions.");
	parentResource.setMessage("ev.error.not.exist.bulletinBoard.0", "There is no registered posts");
	parentResource.setMessage("ev.error.not.exist.page.0", "It is a non-existent page.");
	parentResource.setMessage("ev.error.not.existText.0", "There is no registered writing.");
	parentResource.setMessage("ev.error.not.use.rightMousebutton.0", "It restricts the right to use!");
	parentResource.setMessage("ev.error.not.use.shortcutKey.copy.0", "Copy shortcuts can not be used.");
	parentResource.setMessage("ev.error.noteError.error.0", "Error occurs");
	parentResource.setMessage("ev.error.password.0", "Please check your password. Password and password confirmation must be the same.");
	parentResource.setMessage("ev.error.selectExcelFile.0", "Please select the Excel (xlsx) files.");
	parentResource.setMessage("ev.error.selectPage.0", "Please select the page.");
	parentResource.setMessage("ev.error.selectPortlet.0", "Please choose the portlet.");
	parentResource.setMessage("ev.error.tree.ceateGroupRoot.0", "You can not add the group.");
	parentResource.setMessage("ev.error.tree.ceatePageRoot.0", "The page can not be added.");
	parentResource.setMessage("ev.error.tree.copyPageRoot.0", "A Page can not be copied");
	parentResource.setMessage("ev.error.tree.createRoleRoot.0", "You can not add the role.");
	parentResource.setMessage("ev.error.tree.deleteGroupRoot.0", "You can not delete the group.");
	parentResource.setMessage("ev.error.tree.deletePageRoot.0", "A page can not be deleted.");
	parentResource.setMessage("ev.error.tree.deleteRoleRoot.0", "You can not delete the role.");
	parentResource.setMessage("ev.error.tree.moveDenied.0", "You can not move for this node.");
	parentResource.setMessage("ev.error.tree.moveDeniedPageRoot.0", "The page can not be moved.");
	parentResource.setMessage("ev.error.tree.moveDownGroupRoot.0", "You can not  move down the group.");
	parentResource.setMessage("ev.error.tree.moveDownPageRoot.0", "The page can not be moved down.");
	parentResource.setMessage("ev.error.tree.moveDownRoleRoot.0", "The role can not move down.");
	parentResource.setMessage("ev.error.tree.moveUpGroupRoot.0", "You can not  move up the group.");
	parentResource.setMessage("ev.error.tree.moveUpPageRoot.0", "The page can not be moved up");
	parentResource.setMessage("ev.error.tree.moveUpRoleRoot.0", "The role can not move up.");
	parentResource.setMessage("ev.error.selectUser.0", "Please choose user");
	parentResource.setMessage("ev.error.selectUserOrRole.0", "Please choose a user or role");
	parentResource.setMessage("ev.error.range.date.0", "Period error. Check start and finish dates.");

}
