function initialize_cf(parentResource) {
	parentResource.setMessage("cf.prop.member.info.admin.0", "Account Management");
	parentResource.setMessage("cf.prop.my.info.0", "My Info");
	parentResource.setMessage("cf.prop.my.info.update.0", "Update my info");
	parentResource.setMessage("cf.prop.my.info.view.button.0", "View my info button");
	parentResource.setMessage("cf.error.not.exist.cmnt.img.0", "The representative image of the cafe does not exist.");
	parentResource.setMessage("cf.error.not.exist.colorSet.0", "The corresponding color set does not exist.");
	parentResource.setMessage("cf.error.not.exist.content.0", "No content registered.");
	parentResource.setMessage("cf.error.not.exist.data.0", "Data does not exist.");
	parentResource.setMessage("cf.error.not.exist.department.0", "No department found.");
	parentResource.setMessage("cf.error.not.exist.favor.cafe.0", "There is no registered favorite cafe.");
	parentResource.setMessage("cf.error.not.exist.leaveMember.0", "There are no resigning members.");
	parentResource.setMessage("cf.error.not.exist.member.0", "Member does not exist.");
	parentResource.setMessage("cf.error.not.exist.menuId.0", "Menu ID does not exist.");
	parentResource.setMessage("cf.error.not.exist.mmbr.cmntVO.cafe.0", "There is no designated favorite cafe.");
	parentResource.setMessage("cf.error.not.exist.my.cafe.0", "There is no cafe you joined.");
	parentResource.setMessage("cf.error.not.exist.my.cafe2.0", "Open a new cafe or find a variety of cafes to sign up for.");
	parentResource.setMessage("cf.error.not.exist.post.0", "Do not exsit the post.");
	parentResource.setMessage("cf.error.not.exist.rcmd.cafe.0", "Suggested cafe does not exist.");
	parentResource.setMessage("cf.error.not.exist.rcnt.cafe.0", "Recently visited cafe does not exist.");
	parentResource.setMessage("cf.error.not.exist.to.join.cafe.0", "You do not have a cafe to join.");
	parentResource.setMessage("cf.error.not.exist.wait.levelUp.0", "There are no members waiting for level up.");
	parentResource.setMessage("cf.error.not.set.Board.0", "You can not set more than seven bulletin boards.");
	parentResource.setMessage("cf.error.not.set.zeroBoard.0", "You can not set the number of bulletin boards to 0. Instead, you can select a blank bulletin board.");
	parentResource.setMessage("cf.error.open.denied.0", "Opening this cafe is denied.");
	parentResource.setMessage("cf.error.open.request.0", "This cafe is currently applying to open.");
	parentResource.setMessage("cf.error.select.wrongPeriod.0", "Invalid period selection.");
	parentResource.setMessage("cf.info.accessCafe.0", "Please access the cafe after receiving the sign - up mail from the cafe manager.");
	parentResource.setMessage("cf.info.add.recommendCafe.0", "Do you want to add the selected cafe to the list of recommended cafes?");
	parentResource.setMessage("cf.info.advertise.0", "Advertise!");
	parentResource.setMessage("cf.info.againTryout.0", "Please try again later.");
	parentResource.setMessage("cf.info.already.cancel.closeCafe.0", "You have already canceled the cafe closure.");
	parentResource.setMessage("cf.info.already.join.0", "You have already signed up.");
	parentResource.setMessage("cf.info.already.permit.0", "Already approved.");
	parentResource.setMessage("cf.info.already.rcmd.cafe.0", "It is already a recommended and registered cafe.");
	parentResource.setMessage("cf.info.already.rejoin.0", "You have already rejoined.");
	parentResource.setMessage("cf.info.already.request.closeCafe.0", "You have already applied for cafes closed.");
	parentResource.setMessage("cf.info.already.requestInvitation.0", "You have already requested an invitation.");
	parentResource.setMessage("cf.info.already.requestInvitation.cancel.0", "You have already canceled the invitation request.");
	parentResource.setMessage("cf.info.appoint.sysop.0", "Appointed as a sysop");
	parentResource.setMessage("cf.info.board.prop1.0", "You can set the type of board selected property.");
	parentResource.setMessage("cf.info.board.prop2.0", "Even with the same type of board that has already been opened cafe affects.");
	parentResource.setMessage("cf.info.by.0", "**by");
	parentResource.setMessage("cf.info.cafeHome.main.0", "Set cafe home as main");
	parentResource.setMessage("cf.info.canJoin.0", "After receiving an invitation email from the cafe manager, you can join the cafe by accessing it.");
	parentResource.setMessage("cf.info.cancel.closeCafe.0", "Are you sure you want to cancle the closure of selected cafe?");
	parentResource.setMessage("cf.info.cancel.invitationRequest.0", "The invitation request has been successfully canceled.");
	parentResource.setMessage("cf.info.cancelProcessing.0", "The application has been successfully canceled.");
	parentResource.setMessage("cf.info.change.recommendList.order.0", "Do you want to change the order of recommended lists for the selected cafes?");
	parentResource.setMessage("cf.info.choose.addCafe.0", "Please select a cafe to add.");
	parentResource.setMessage("cf.info.choose.boardManager.0", "Please select the bulletin board manager you want to release.");
	parentResource.setMessage("cf.info.choose.deleteCafe.0", "Please select a cafe to remove.");
	parentResource.setMessage("cf.info.choose.upperMenu.0", "Please select the top menu of the menu to add.");
	parentResource.setMessage("cf.info.chooseDesign.0", "Choose the design you like.");
	parentResource.setMessage("cf.info.closeCafe.0", "Do you want to force the closure of the selected cafe?");
	parentResource.setMessage("cf.info.closing.Info.0", "Currently, there are no members except the cafe manager, so you can close the cafe.");
	parentResource.setMessage("cf.info.closing.Info2.0", "Once the closure has been carried out, the cafe data, including postings, can not be recovered.");
	parentResource.setMessage("cf.info.complete.cafeCreation.0", "Cafe creation is complete.");
	parentResource.setMessage("cf.info.complete.joinCafe.0", "Sign-Up for cafe is complete.");
	parentResource.setMessage("cf.info.completeRegistration.modifiabl.0", "Application is complete. It is possible to correct it before the approval of the person in charge.");
	parentResource.setMessage("cf.info.confirm.closeCafe.0", "Are you sure you want to close the cafe?");
	parentResource.setMessage("cf.info.confirm.closeCafe.cancel.0", "Are you sure you want to cancel closing of the cafe?");
	parentResource.setMessage("cf.info.confirm.url.0", "Available cafe address.");
	parentResource.setMessage("cf.info.confirm.usernick.0", "Available nickname.");
	parentResource.setMessage("cf.info.continueModify.0", "Continue editing?");
	parentResource.setMessage("cf.prop.join.info.0", "Join Information");
	parentResource.setMessage("cf.error.already.existMenu.0", "There exists a menu already set as a cafe home board.");
	parentResource.setMessage("cf.error.already.used.name.0", "This is the cafe name already in use. Please enter another name.");
	parentResource.setMessage("cf.error.already.used.url.0", "This is the cafe url already in use. Please enter a different url.");
	parentResource.setMessage("cf.error.already.used.usernick.0", "This nickname is already in use.");
	parentResource.setMessage("cf.error.cafejigi.cant.resign.0", "The cafe manager cannot leave a cafe.");
	parentResource.setMessage("cf.error.cannot.delete.0", "These boards can not be deleted.");
	parentResource.setMessage("cf.error.cant.change.same.state.0", "Include users with the same status you want to change.");
	parentResource.setMessage("cf.error.cant.change.self.grade.0", "You can not change your own grade.");
	parentResource.setMessage("cf.error.cant.change.staff.grade.0", "The staff can not change the grades of the staff.");
	parentResource.setMessage("cf.error.cant.change.sysop.grade.0", "You can not change the grade of the cafe manager.");
	parentResource.setMessage("cf.error.cant.change.sysop.state.0", "You can not change the state of cafe manager.");
	parentResource.setMessage("cf.error.cant.move2one.0", "Text from bulletin boards of the selected type can not be moved to that of the 1-line notepad type.");
	parentResource.setMessage("cf.error.cant.move2qna.0", "Text in a Q\/A type bulletin can not be moved to another type of bulletin.");
	parentResource.setMessage("cf.error.cateId.required.0", "Cafe ID is required.");
	parentResource.setMessage("cf.error.closed.cafe.0", "It is a closed cafe.");
	parentResource.setMessage("cf.error.cmntNm.required.0", "Cafe name is required.");
	parentResource.setMessage("cf.error.cmntUrl.required.0", "Cafe URL is required.");
	parentResource.setMessage("cf.error.cnat.change.wx2bjigi.0", "The management or the cafe manager can not be a bulletin board manager.");
	parentResource.setMessage("cf.error.different.dateType.0", "Invalid date format.");
	parentResource.setMessage("cf.error.email.not.exist.0", "The e-mail address does not exist.");
	parentResource.setMessage("cf.error.favorMng.request.fail.0", "Invalid request to change list of favorite cafes.");
	parentResource.setMessage("cf.error.gradeNm.fail.0", "Invalid grade name.");
	parentResource.setMessage("cf.error.grdup.request.fail.0", "Invalid grade condition change request.");
	parentResource.setMessage("cf.error.improper.stateFlag.0", "This is not a normal member status.");
	parentResource.setMessage("cf.error.incorrect.dateType.0", "This is not a valid date format.");
	parentResource.setMessage("cf.error.layout.corrupt.0", "Error in the individual cafe home layout data. Cannot change the layout.");
	parentResource.setMessage("cf.error.makerId.required.0", "Cafe manager ID is required.");
	parentResource.setMessage("cf.error.menuMng.request.fail.0", "Invalid menu change request.");
	parentResource.setMessage("cf.error.newUrl.required.0", "A new URL is required.");
	parentResource.setMessage("cf.error.noPermissions.write.0", "You do not have permission to write.");
	parentResource.setMessage("cf.error.not.allow.read.0", "The author did not allow to read the post.");
	parentResource.setMessage("cf.error.not.correspondUser.0", "A user that does not correspond to the state you want to release is included.");
	parentResource.setMessage("cf.error.not.decorate.0", "You can not proceed with decorating anymore. Finish and start it over.");
	parentResource.setMessage("cf.error.not.exist.approval.member.0", "There are no members waiting for approval.");
	parentResource.setMessage("cf.error.not.exist.cafe.0", "This cafe does not exist.");
	parentResource.setMessage("cf.prop.info.area.0", "Information Area");
	parentResource.setMessage("cf.info.create.department.0", "Do you want to create a department yard?");
	parentResource.setMessage("cf.info.deco.useColor.0", "Color is the way to decorate on your own.");
	parentResource.setMessage("cf.info.define.iconName.0", "Please choose a name for the menu icon.");
	parentResource.setMessage("cf.info.delete.noticeList.0", "Are you sure you want to delete the announcement?");
	parentResource.setMessage("cf.info.delete.recommendCafe.0", "Are you sure you want to remove the selected cafe from the list of recommended cafes?");
	parentResource.setMessage("cf.info.email.addr.not.exist.0", "No email address.");
	parentResource.setMessage("cf.info.employee.notSeen.0", "The employee was not seen.");
	parentResource.setMessage("cf.info.ggum.apply.0", "Do you want to apply the current decoration status?");
	parentResource.setMessage("cf.info.ggum.gate.apply.0", "Do you want to apply the current gate edit details?");
	parentResource.setMessage("cf.info.goOut.invitationRequest.mail.0", "The invitation request mail has been sent successfully.");
	parentResource.setMessage("cf.info.htmlEdit.0", "Edit HTML and save to appear in the gateway area.");
	parentResource.setMessage("cf.info.input.TimesLimit.0", "Please enter at least one limit in count to use the policy.");
	parentResource.setMessage("cf.info.input.onlyNumber.0", "Only numbers can be entered.");
	parentResource.setMessage("cf.info.input.replyList.0", "Please enter at least 2 answers to the subscription questionnaire.");
	parentResource.setMessage("cf.info.input.searchWord.0", "Please enter a search term.");
	parentResource.setMessage("cf.info.inputEmail.0", "Please enter your e-mail.");
	parentResource.setMessage("cf.info.inviteMail.0", "The invitation mail of the sysop will be sent to the e-mail address registered with the member info.");
	parentResource.setMessage("cf.info.irreparable.closeCafe.0", "Once the cafe is closed, all data, including postings, can not be recovered!");
	parentResource.setMessage("cf.info.joinLink.0", "You can sign up for the cafe at the link below.");
	parentResource.setMessage("cf.info.keep.board.0", "Archived bulletins will be automatically deleted after {0} days, and it can not be restored.");
	parentResource.setMessage("cf.info.leaveProcessing.0", "Successfully unsubscribed.");
	parentResource.setMessage("cf.info.makeTitle.0", "Create great titles quickly and easily at once.");
	parentResource.setMessage("cf.info.makeTitle.easy.0", "Create a great title quickly and easily at once.");
	parentResource.setMessage("cf.info.margin.0", "Margins are set.");
	parentResource.setMessage("cf.info.mustLogin.0", "You need to login.");
	parentResource.setMessage("cf.info.myPeople.0", "You can easily receive the messages from our cafe or useful information of Daum cafe by My People.");
	parentResource.setMessage("cf.info.needApprove.0", "It is a cafe that requires the approval of a cafe manager.");
	parentResource.setMessage("cf.info.needLogin.0", "You need to login.");
	parentResource.setMessage("cf.info.not.exist.notice.0", "Notification does not exist.");
	parentResource.setMessage("cf.info.not.existImg.0", "There are no registered images.");
	parentResource.setMessage("cf.info.not.use.cafeDeco.0", "You can not use the current version of browser to decorate cafes.");
	parentResource.setMessage("cf.info.o.chooseMember.0", "Selected members");
	parentResource.setMessage("cf.info.o.joinQuiz.answer.0", "Join the quiz answers");
	parentResource.setMessage("cf.info.o.joinQuiz.question.0", "the question of quiz for join");
	parentResource.setMessage("cf.info.please.selectBoard.0", "Please select a bulletin board.");
	parentResource.setMessage("cf.info.preparing.0", "Coming soon.");
	parentResource.setMessage("cf.info.privateCafe.0", "This is a private cafe.");
	parentResource.setMessage("cf.info.processed.acceptOpen.0", "Opening approval has been successfully processed.");
	parentResource.setMessage("cf.info.processed.cancelClosing.0", "Release of closure has been successfully processed.");
	parentResource.setMessage("cf.info.processed.closing.0", "Forced closure has been successfully processed.");
	parentResource.setMessage("cf.info.processed.deleteCafe.0", "Cafe deletion has been successfully processed.");
	parentResource.setMessage("cf.info.processed.deleteComment.0", "Comment (memo) was successfully deleted.");
	parentResource.setMessage("cf.info.processed.deleteNotice.0", "Deleting post has been successfully processed.");
	parentResource.setMessage("cf.info.processed.recommendCafe.0", "Cafe recommendation has been successfully processed.");
	parentResource.setMessage("cf.info.processed.recommendCafe.cancel.0", "Cancellation of cafe recommendation has been successfully processed.");
	parentResource.setMessage("cf.info.really.cancel.RequestIbvitation.0", "Are you sure you want to cancel the invitation request?");
	parentResource.setMessage("cf.info.really.delete.0", "Do you really want to delete it?");
	parentResource.setMessage("cf.info.really.rejoin.0", "Would you like to rejoin?");
	parentResource.setMessage("cf.info.reallyCancel.0", "Are you sure you want to cancel?");
	parentResource.setMessage("cf.info.reallyLeave.0", "Are you sure you want to leave?");
	parentResource.setMessage("cf.info.recognize.requestEstablishment.0", "Do you confirm the request to open the selected cafe?");
	parentResource.setMessage("cf.info.reenter.cafeURL.0", "Please re-enter the cafe address.");
	parentResource.setMessage("cf.info.regFail.birthYyyy.notExist.0", "User information has no date of birth.");
	parentResource.setMessage("cf.info.regFail.cllgCode.notExist.0", "User information has no college department info.");
	parentResource.setMessage("cf.info.regFail.limitAge..0", "You can not join in this age.");
	parentResource.setMessage("cf.info.regFail.limitAge.after.0", "Your age is greater than that of the subscription terms.");
	parentResource.setMessage("cf.prop.operator.info.0", "Company Information");
	parentResource.setMessage("cf.error.not.exist.cafe.skin.0", "Cafe skin does not exist.");
	parentResource.setMessage("cf.error.not.exist.cafe.theme.0", "Cafe theme does not exist.");
	parentResource.setMessage("cf.error.not.exist.cafe2.0", "The cafe does not exist.");
	parentResource.setMessage("cf.error.not.exist.cmnt.0", "This community does not exist.");
	parentResource.setMessage("cf.prop.basic.info.0", "Basic Information");
	parentResource.setMessage("cf.info.regFail.limitAge.before.0", "Your age is less than that of the subscription terms.");
	parentResource.setMessage("cf.info.regFail.limitCllg.0", "Member of the department that is not eligible for joining.");
	parentResource.setMessage("cf.info.regFail.limitCode.0", "This is a non-registerable residence.");
	parentResource.setMessage("cf.info.regFail.limitMajor.0", "This is an unenrollable department.");
	parentResource.setMessage("cf.info.regFail.limitOrg.0", "Member of an organization that can not join.");
	parentResource.setMessage("cf.info.regFail.limitQuiz.0", "Answer for quiz is wrong.");
	parentResource.setMessage("cf.info.regFail.limitSex.0", "This cafe is opened to a specific gender.");
	parentResource.setMessage("cf.info.regFail.limitTerm.0", "Join is limited for now.");
	parentResource.setMessage("cf.info.regFail.locCode.notExist.0", "No region information in user information.");
	parentResource.setMessage("cf.info.regFail.majorCode.notExist.0", "No department\/major code in your user info.");
	parentResource.setMessage("cf.info.regFail.not.answ.0", "The answer is wrong.");
	parentResource.setMessage("cf.info.regFail.orgCode.notExist.0", "No organization code in your user info.");
	parentResource.setMessage("cf.info.regFail.regQstn.cnt.notMatch.0", "Incorrect number of questions.");
	parentResource.setMessage("cf.info.regFail.sexFlag.notExist.0", "No gender code in your user info.");
	parentResource.setMessage("cf.info.rejectReason.0", "The cafe invitation has been rejected for the following reasons.");
	parentResource.setMessage("cf.info.remoteControl.0", "It is convenient to use while checking the preview on the bottom of the remote control.");
	parentResource.setMessage("cf.info.sameBoard.0", "It is the same board.");
	parentResource.setMessage("cf.info.save.noticeList.0", "Do you want to save the notice details?");
	parentResource.setMessage("cf.info.selectBoard.0", "Please select a board.");
	parentResource.setMessage("cf.info.selectFile.0", "Please select a file.");
	parentResource.setMessage("cf.info.selectLayout.0", "Please select the layout of the bulletin board to be added to the cafe home.");
	parentResource.setMessage("cf.info.send.requestEmail.0", "You have sent an invitation request email to sysop of selected cafe to sign up.");
	parentResource.setMessage("cf.info.separator.0", "The separator is set.");
	parentResource.setMessage("cf.info.setting.cafeHome.0", "The current setting applies only to Cafe Home.");
	parentResource.setMessage("cf.info.shutDown.font.0", " The font you are using has been shut down. Please choose a different font.");
	parentResource.setMessage("cf.info.state.flag.not.10.0", "You are not on a subscription status.");
	parentResource.setMessage("cf.info.state.flag.not.10.21.0", "You are not on the status of applying or rejection for subscription.");
	parentResource.setMessage("cf.info.state.flag.not.12.0", "You are not on the status of request for invitation.");
	parentResource.setMessage("cf.info.state.flag.not.12.22.0", "You are not on the status of request or rejection for invitation.");
	parentResource.setMessage("cf.info.state.flag.not.40.0", "You are not in inactive status.");
	parentResource.setMessage("cf.info.state.flag.not.50.0", "You are not in voluntary withdrawal status.");
	parentResource.setMessage("cf.info.state.flag.not.51.0", "You are not in forced withdrawal status.");
	parentResource.setMessage("cf.info.todayActivities.0", "Activities Today");
	parentResource.setMessage("cf.info.ttl.none.board.0", "No Board");
	parentResource.setMessage("cf.info.wantJoin.0", "If you want to join, please send an invitation request to sysop.");
	parentResource.setMessage("cf.info.warning.deleteAll.0", "WARNING!. Delete all data of cafe regardless of its status. Are you sure you want to delete?");
	parentResource.setMessage("cf.prop.employee.info.0", "Employee information");
	parentResource.setMessage("cf.prop.etc.info.0", "More information");
	parentResource.setMessage("cf.prop.cafe.basic.info.0", "Cafe Basic information");
	parentResource.setMessage("cf.prop.cafe.info.0", "Cafe Information");
	parentResource.setMessage("cf.prop.cafe.info.admin.0", "Cafe Information Management");
	parentResource.setMessage("cf.prop.cafe.rank.info.0", "Cafe ranking information");

}
