function initialize_hn(parentResource) {
	parentResource.setMessage("hn.error.fail.getSchedule.0", "오늘의 일정을 불러오는데 실패하였습니다.");
	parentResource.setMessage("hn.error.not.exist.openSchedule.0", "공개 일정이 없습니다.");
	parentResource.setMessage("hn.error.not.exist.schedule.0", "일정이 없습니다.");
	parentResource.setMessage("hn.error.not.exist.selectedNote.0", "선택된 쪽지가 없습니다.");
	parentResource.setMessage("hn.info.addBlocklist.0", "해당 사용자가 차단목록에 추가되었습니다.");
	parentResource.setMessage("hn.info.admin.calendar.delete.fail.0", "데이터 삭제에 실패하였습니다.");
	parentResource.setMessage("hn.info.admin.calendar.delete.success.0", "성공적으로 삭제되었습니다.");
	parentResource.setMessage("hn.info.admin.calendar.insert.calendarname.0", "캘린더 이름을 입력해주세요.");
	parentResource.setMessage("hn.info.admin.calendar.insert.fail.0", "데이터 추가가 실패하였습니다.");
	parentResource.setMessage("hn.info.admin.calendar.insert.success.0", "성공적으로 추가되었습니다.");
	parentResource.setMessage("hn.info.admin.calendar.question.delete.0", "데이터를 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.admin.calendar.question.insert.0", "데이터를 추가하시겠습니까?");
	parentResource.setMessage("hn.info.admin.calendar.question.update.0", "데이터를 변경하시겠습니까?");
	parentResource.setMessage("hn.info.admin.calendar.select.data.0", "데이터를 선택해주세요.");
	parentResource.setMessage("hn.info.admin.calendar.update.fail.0", "데이터 변경에 실패하였습니다.");
	parentResource.setMessage("hn.info.admin.calendar.update.success.0", "성공적으로 변경되었습니다.");
	parentResource.setMessage("hn.info.alert.file.extension.incorrect.0", "확장자가   {0}  인 파일은 업로드 할 수 없습니다.\\n확장자가   {1}  인 파일을 선택해주세요.");
	parentResource.setMessage("hn.info.application.is.0", "어플리케이션이");
	parentResource.setMessage("hn.info.became.0", "되었습니다.");
	parentResource.setMessage("hn.info.calendar.isBilingual.0.0", "사용안함");
	parentResource.setMessage("hn.info.calendar.isBilingual.1.0", "사용");
	parentResource.setMessage("hn.info.calendar.isHoliday.0.0", "휴일아님");
	parentResource.setMessage("hn.info.calendar.isHoliday.1.0", "휴일");
	parentResource.setMessage("hn.info.calendar.isUse.0.0", "사용안함");
	parentResource.setMessage("hn.info.calendar.isUse.1.0", "사용");
	parentResource.setMessage("hn.info.calendar.isVisible.0.0", "표시안함");
	parentResource.setMessage("hn.info.calendar.isVisible.1.0", "표시");
	parentResource.setMessage("hn.info.cant.blockOneself.0", "자기 자신은 차단 할 수 없습니다.");
	parentResource.setMessage("hn.info.cant.restore.deleteCalendar.0", "캘린더를 삭제하면 복구할 수 없습니다.\\n이 캘린더를 지우시겠습니까?");
	parentResource.setMessage("hn.info.change.receptionSetting.0", "수신설정을 변경하였습니다.");
	parentResource.setMessage("hn.info.choose.Feed.0", "Feed를 선택하세요.");
	parentResource.setMessage("hn.info.choose.application.0", "어플리케이션을 선택하세요.");
	parentResource.setMessage("hn.info.choose.calendar.0", "캘린더를 선택하세요.");
	parentResource.setMessage("hn.info.choose.searchValue.0", "검색할 값을 선택해주세요.");
	parentResource.setMessage("hn.info.choose.skin.0", "스킨을 선택하세요.");
	parentResource.setMessage("hn.info.choose.skinPath.0", "스킨 경로를 선택하세요");
	parentResource.setMessage("hn.info.chooseEntry.0", "Entry를 선택하세요.");
	parentResource.setMessage("hn.info.confirm.Modify.0", "수정 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.addCategory.0", "카테고리를 추가하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.backup.permanentStoragebox.0", "영구 보관함을 백업하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.backup.sentNote.0", "보낸 쪽지함을 백업하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.cancelApproval.0", "승인취소 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.cancelSubscription.0", "구독을 해제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.change.receptionSetting.0", "수신 설정을 변경하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.closeEntry.0", "선택된 Entry들을 비공개 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.delete.0", "삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.delete.calendar.0", "캘린더를 삭제하시겠습니까?\\n삭제하면 이 캘린더에 속한 모든 일정이 같이삭제되어 복구할 수 없습니다.");
	parentResource.setMessage("hn.info.confirm.delete.joint.0", "다른 사람이 공유한 캘린더입니다.\\n삭제하면 공유된 모든 일정이 보이지 않게됩니다.");
	parentResource.setMessage("hn.info.confirm.delete.schedule.0", "일정을 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.delete.selectedSkin.0", "선택된 스킨들을 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.deleteCategory.0", "카테고리를 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.deleteFeed.0", "선택된 Feed들을 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.empty.receivedNote.0", "받은쪽지함을 비우시겠습니까?");
	parentResource.setMessage("hn.info.confirm.empty.receivingCheck.0", "수신확인함을 비우시겠습니까?");
	parentResource.setMessage("hn.info.confirm.empty.sendNote.0", "보낸쪽지함을 비우시겠습니까?");
	parentResource.setMessage("hn.info.confirm.empty.trash.0", "휴지통을 비우시겠습니까?");
	parentResource.setMessage("hn.info.confirm.keep.0", "보관하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.readingCheck.0", "안읽은 쪽지를 모두 읽음표시 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.recognize.0", "승인 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.refuse.0", "거절 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.restore.0", "복구하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.save.0", "저장하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.selectedApplication.0", "선택된 어플리케이션들을 삭제하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.subscribe.0", "구독 하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.upload.0", "선택된   {0}   파일을 업로드하시겠습니까?");
	parentResource.setMessage("hn.info.confirm.wouldYouLikeTo.0", "하시겠습니까?");
	parentResource.setMessage("hn.info.continueRecursion.0", "계속 반복");
	parentResource.setMessage("hn.info.delete.receptionChecklist.0", "수신확인 목록이 삭제되었습니다.");
	parentResource.setMessage("hn.info.deleteApplication.0", "어플리케이션이 삭제되었습니다.");
	parentResource.setMessage("hn.info.deleteBlocklist.0", "해당 사용자가 차단목록에서 제거 되었습니다.");
	parentResource.setMessage("hn.info.deleteFeed.0", "Feed가 삭제되었습니다.");
	parentResource.setMessage("hn.info.deleteNote.0", "쪽지가 삭제되었습니다.");
	parentResource.setMessage("hn.info.deleteSkin.0", "스킨이 삭제되었습니다.");
	parentResource.setMessage("hn.info.each.0", "마다");
	parentResource.setMessage("hn.info.empty.receivedNote.0", "받은쪽지함을 비웠습니다.");
	parentResource.setMessage("hn.info.empty.receivingCheck.0", "수신확인함을 비웠습니다.");
	parentResource.setMessage("hn.info.empty.sendNote.0", "보낸쪽지함을 비웠습니다.");
	parentResource.setMessage("hn.info.empty.trash.0", "휴지통을 비웠습니다.");
	parentResource.setMessage("hn.info.eventPage.detailInfo.0", "현재 이벤트 페이지의 자세한 정보입니다.");
	parentResource.setMessage("hn.info.input.ApplicationCode.0", "어플리케이션 코드를 입력하세요");
	parentResource.setMessage("hn.info.input.ApplicationName.0", "어플리케이션 이름을 입력하세요");
	parentResource.setMessage("hn.info.input.ApplicationVersion.0", "어플리케이션 버전을 입력하세요");
	parentResource.setMessage("hn.info.input.feedName.0", "Feed 이름을 입력하세요.");
	parentResource.setMessage("hn.info.input.feedURL.0", "Feed 주소를 입력하세요.");
	parentResource.setMessage("hn.info.input.searchValue.0", "검색할 값을 입력해주세요.");
	parentResource.setMessage("hn.info.input.searchValue.overTwoletters.0", "검색 할 값은 두글자 이상을 입력해주세요.");
	parentResource.setMessage("hn.info.input.searchWord.0", "검색어를 2글자 이상 입력해주세요.");
	parentResource.setMessage("hn.info.input.skinName.0", "스킨명을 입력하세요");
	parentResource.setMessage("hn.info.input.userId.0", "사용자 아이디 혹은 이름을 입력하세요.");
	parentResource.setMessage("hn.info.inputContent.0", "내용을 입력하세요");
	parentResource.setMessage("hn.info.inputTitle.0", "제목을 입력하세요");
	parentResource.setMessage("hn.info.invalid.delete.owner.0", "기본 캘린더는 삭제할 수 없습니다.");
	parentResource.setMessage("hn.info.keepNote.0", "쪽지가 보관되었습니다.");
	parentResource.setMessage("hn.info.not.exist.registeredBanner.0", "등록된 배너목록이 없습니다.");
	parentResource.setMessage("hn.info.note.delete.0", "선택된 쪽지를 지우시겠습니까?");
	parentResource.setMessage("hn.info.permanent.deleteNote.0", "쪽지가 영구삭제되었습니다.");
	parentResource.setMessage("hn.info.readingCheck.0", "앉읽은 쪽지를 모두 읽음표시 하였습니다.");
	parentResource.setMessage("hn.info.registeredBanner.0", "등록된 배너 입니다.");
	parentResource.setMessage("hn.info.required.calendar.name.0", "캘린더 이름을 입력해주세요.");
	parentResource.setMessage("hn.info.required.schedule.rrule.until.0", "반복 종료일을 지정해주세요.");
	parentResource.setMessage("hn.info.restoreNote.0", "쪽지가 복구되었습니다.");
	parentResource.setMessage("hn.info.save.changePoint.0", "변경 사항을 저장하시겠습니까?");
	parentResource.setMessage("hn.info.save.invaild.date.0", "날짜 선택이 잘못되었습니다.");
	parentResource.setMessage("hn.info.save.invaild.time.0", "시간 선택이 잘못되었습니다.");
	parentResource.setMessage("hn.info.save.required.calendar.name.0", "캘린더 제목을 입력해주세요.");
	parentResource.setMessage("hn.info.save.required.schedule.name.0", "일정 제목을 입력해주세요.");
	parentResource.setMessage("hn.info.save.required.schedule.nameList.0", "일정 제목을 각 언어 모두 입력해주세요.");
	parentResource.setMessage("hn.info.schedule.empty.0", "등록된 일정이 없습니다.");
	parentResource.setMessage("hn.info.schedule.rrule.byday.all.0", "모든 요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.fr.0", "금요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.mo.0", "월요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.sa.0", "토요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.su.0", "일요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.th.0", "목요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.tu.0", "화요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.we.0", "수요일");
	parentResource.setMessage("hn.info.schedule.rrule.byday.weekdays.0", "주중");
	parentResource.setMessage("hn.info.schedule.rrule.noRepeat.0", "반복일정이 해제됩니다.");
	parentResource.setMessage("hn.info.search.required.words.0", "검색어를 두 단어 이상 입력해주세요.");
	parentResource.setMessage("hn.info.selectReceiver.0", "받는 사람을 선택하세요");
	parentResource.setMessage("hn.info.shippedNote.0", "쪽지가 발송되었습니다.");
	parentResource.setMessage("hn.info.skin.is.0", "스킨이");
	parentResource.setMessage("hn.info.title.calendar.permissions.r.0", "일정 보기");
	parentResource.setMessage("hn.info.title.calendar.permissions.ru.0", "일정 변경");
	parentResource.setMessage("hn.info.title.name.title.0", "제목");
	parentResource.setMessage("hn.info.title.name.title.en.0", "제목(English)");
	parentResource.setMessage("hn.info.title.name.title.ko.0", "제목(Korean)");
	parentResource.setMessage("hn.info.userGrp.GRP_OUT.0", "외부인");
	parentResource.setMessage("hn.info.userGrp.GRP_PER.0", "직원");
	parentResource.setMessage("hn.info.userGrp.GRP_PRO.0", "교원");
	parentResource.setMessage("hn.info.userGrp.GRP_STU.0", "학생");
	parentResource.setMessage("hn.info.userGrp.noGroup.0", "그룹없음");
	parentResource.setMessage("hn.info.userGrp.not.exist.0", "그룹없음");
	parentResource.setMessage("hn.info.userOrg.not.exist.0", "소속없음");

}
